// Generated by scripts/sync-conditions.ts from protocols/predefined/00-conditions.npps.
// DO NOT EDIT BY HAND — edit the .npps registry and re-run:
//     bun scripts/sync-conditions.ts
// Apple (iOS + macOS)

import Foundation

/// The bundled condition registry — standard condition names paired with an
/// external definition link. Protocols reference these by name through their
/// `conditions` field. See NP-COND-LINK-001.
enum NPBundledConditions {

    static let all: [NPConditionDefinition] = [
        NPConditionDefinition(
            name: "Alzheimer's Disease",
            id: "41000001-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Alzheimer%27s_disease",
            code: "8A20",
            description: nil
        ),
        NPConditionDefinition(
            name: "Dementia",
            id: "41000002-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Dementia",
            code: "6D8Z",
            description: nil
        ),
        NPConditionDefinition(
            name: "Mild Cognitive Impairment",
            id: "41000003-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Mild_cognitive_impairment",
            code: "6D71",
            description: nil
        ),
        NPConditionDefinition(
            name: "Major Depressive Disorder",
            id: "41000004-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Major_depressive_disorder",
            code: "6A70",
            description: nil
        ),
        NPConditionDefinition(
            name: "Generalized Anxiety Disorder",
            id: "41000005-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Generalized_anxiety_disorder",
            code: "6B00",
            description: nil
        ),
        NPConditionDefinition(
            name: "Traumatic Brain Injury",
            id: "41000006-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Traumatic_brain_injury",
            code: "NA07",
            description: nil
        ),
        NPConditionDefinition(
            name: "Post-Concussion Syndrome",
            id: "41000007-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Post-concussion_syndrome",
            code: "8A8E",
            description: nil
        ),
        NPConditionDefinition(
            name: "Autism Spectrum Disorder",
            id: "41000008-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Autism_spectrum_disorder",
            code: "6A02",
            description: nil
        ),
        NPConditionDefinition(
            name: "Parkinson's Disease",
            id: "41000009-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Parkinson%27s_disease",
            code: "8A00.0",
            description: nil
        ),
        NPConditionDefinition(
            name: "Stroke",
            id: "41000010-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Stroke",
            code: "8B20",
            description: nil
        ),
        NPConditionDefinition(
            name: "Aphasia",
            id: "41000011-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Aphasia",
            code: "MA80.1",
            description: nil
        ),
        NPConditionDefinition(
            name: "Epilepsy",
            id: "41000012-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Epilepsy",
            code: "8A6Z",
            description: nil
        ),
        NPConditionDefinition(
            name: "Post-Traumatic Stress Disorder",
            id: "41000013-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Post-traumatic_stress_disorder",
            code: "6B40",
            description: nil
        ),
        NPConditionDefinition(
            name: "Substance Use Disorder",
            id: "41000014-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Substance_use_disorder",
            code: "6C4Z",
            description: nil
        ),
        NPConditionDefinition(
            name: "Attention Deficit Hyperactivity Disorder",
            id: "41000015-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Attention_deficit_hyperactivity_disorder",
            code: "6A05",
            description: nil
        ),
        NPConditionDefinition(
            name: "Schizophrenia",
            id: "41000016-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Schizophrenia",
            code: "6A20",
            description: nil
        ),
        NPConditionDefinition(
            name: "Tinnitus",
            id: "41000017-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Tinnitus",
            code: "MC41",
            description: nil
        ),
        NPConditionDefinition(
            name: "Fibromyalgia",
            id: "41000018-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Fibromyalgia",
            code: "MG30.01",
            description: nil
        ),
        NPConditionDefinition(
            name: "Chronic Pain",
            id: "41000019-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Chronic_pain",
            code: "MG30",
            description: nil
        ),
        NPConditionDefinition(
            name: "Neuropathic Pain",
            id: "41000020-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Neuropathic_pain",
            code: "8E43",
            description: nil
        ),
        NPConditionDefinition(
            name: "Multiple Sclerosis",
            id: "41000021-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Multiple_sclerosis",
            code: "8A40",
            description: nil
        ),
        NPConditionDefinition(
            name: "Insomnia",
            id: "41000022-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Insomnia",
            code: "7A00",
            description: nil
        ),
        NPConditionDefinition(
            name: "Migraine",
            id: "41000023-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Migraine",
            code: "8A80",
            description: nil
        ),
        NPConditionDefinition(
            name: "Cluster Headache",
            id: "41000024-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Cluster_headache",
            code: "8A81",
            description: nil
        ),
        NPConditionDefinition(
            name: "Essential Tremor",
            id: "41000025-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Essential_tremor",
            code: "8A04.1",
            description: nil
        ),
        NPConditionDefinition(
            name: "Disorders of Consciousness",
            id: "41000026-0000-0000-0000-000000000000",
            link: "https://en.wikipedia.org/wiki/Disorders_of_consciousness",
            code: nil,
            description: nil
        ),
    ]

    /// Name → definition, for resolving a protocol's `conditions` entries.
    static let byName: [String: NPConditionDefinition] =
        Dictionary(uniqueKeysWithValues: all.map { ($0.name, $0) })
}
