import Foundation

/// The bundled condition registry — standard condition names paired with an
/// external definition link. Protocols reference these by name through their
/// `conditions` field. See NP-COND-LINK-001.
///
/// Read from `protocols/predefined/00-conditions.npps` in the app bundle, via
/// the same namespace the protocol library is built from. This used to be a
/// Swift transcription generated by `scripts/sync-conditions.ts`, which existed
/// only because this parser had no `condition` block; it gained one in
/// NP-NPPS-REF-001 Rev 10, so the registry now has one representation rather
/// than two that a forgotten script run could separate.
enum NPBundledConditions {

    static var all: [NPConditionDefinition] {
        // Sorted by name so the order is stable for pickers and tests; the
        // namespace keys by name and makes no order promise.
        NPBundledProtocols.namespace.conditions.values.sorted { $0.name < $1.name }
    }

    /// Name → definition, for resolving a protocol's `conditions` entries.
    static var byName: [String: NPConditionDefinition] {
        NPBundledProtocols.namespace.conditions
    }
}
