import Foundation

// GENERATED by scripts/sync-constants.ts from common/npps/constants.json. DO NOT EDIT: change the JSON and re-run it.

/// Every hardware ceiling and fixed device figure the apps and the shared validator use. The firmware enforces them
/// independently; no dosage limit or clinician override can exceed them.
enum NPHardwareLimits {
    /// PBM Transcranial / Intranasal (shared firmware limit)
    static let PBM_DUTY_CYCLE_MAX_PERCENT: Int = 25
    /// pending RISK-03 regulatory opinion
    static let PBM_PULSED_PEAK_MW_CM2: Double = 400.0
    static let PBM_CW_MAX_MW_CM2: Double = 200.0
    /// Deep 1170 nm PBM ceiling (CLAUDE.md §3: ≤1,000 mW/cm², TEC-stabilised).
    static let PBM_DEEP_MAX_MW_CM2: Double = 1000.0
    /// Aggregate PBM irradiance ceiling (OI-PBM-05, three-channel combined). Pending RISK-03 regulatory
    /// opinion scope expansion (Q4–Q6).
    static let PBM_AGGREGATE_MAX_MW_CM2: Double = 600.0
    /// BES / tACS (consumer: Brainwave Entrainment Stimulation)
    static let BES_TACS_MAX_MILLIAMPS: Double = 1.0
    static let BES_TACS_MIN_HZ: Double = 0.5
    static let BES_TACS_MAX_HZ: Double = 40.0
    /// tDCS (consumer: Cortical Priming Stimulation)
    static let TDCS_MIN_MILLIAMPS: Double = 0.1
    static let TDCS_MAX_MILLIAMPS: Double = 2.0
    /// OI-CHARGE-04 (closed 2026-09-09): this IS checked here now. There is no web electrode-area constant
    /// to add, because there is no longer a global electrode area on any client — the area is authored per
    /// protocol (TDCSParams.electrodeAreaCm2), travels in the signed session descriptor, and the safety MCU
    /// derives its charge limit from that same declared number. What used to be a 35-vs-25 disagreement
    /// between the app's assumption and the enforcer's is now one transmitted value. OI-CHARGE-05 (a)(d)
    /// 2026-09-15: RENAMED AND RE-SOURCED. This used to be `tdcsMaxChargeDensityUCcm2: 40.0`, a misnomer
    /// that concealed a 1000× divergence — `I(mA) × t(s) / A(cm²)` is mC/cm², so the clients enforced 40
    /// mC/cm² while the safety MCU enforced 40 µC/cm². The name now states the unit AND the period, because
    /// both were ambiguous and each hid a different defect: the unit hid the 1000×, and the missing period
    /// hid that a per-phase pulsed figure was being applied to a DC session dose. 150 mC/cm² per session
    /// per electrode, derived rather than asserted (the old 40 had no source anywhere in the tree — the
    /// citation chain was circular). Bounds the conventional large-pad human tDCS envelope: the
    /// most-exposed large RCT protocol in docs/tdcs_database_full.csv is Brunoni ELECT-TDCS 2013/2017 at 2
    /// mA × 30 min on 25 cm² = 144 mC/cm². Margin check: 35× below Liebetanz 2009's measured rat epicranial
    /// DC lesion threshold of 5,240 mC/cm². Full derivation: NP-DT-001 DI-SAFE-01.
    static let TDCS_MAX_SESSION_CHARGE_DENSITY_MC_CM2: Double = 150.0
    /// Per-PHASE ceiling for the charge-balanced biphasic modalities — BES/tACS, VNS, cervical VNS,
    /// clinical tACS (OI-CHARGE-05 (b)). 40 µC/cm² is a real and correct figure in this form (Shannon 1992
    /// / McCreery 1990 pulsed charge-injection limits); it is the number the tree has always carried, now
    /// applied to the waveform class it is actually about. Net charge on these modalities is ~zero by
    /// construction, so a session-cumulative dose is not a physical quantity for them and is not checked.
    static let PULSED_MAX_PHASE_CHARGE_DENSITY_UC_CM2: Double = 40.0
    /// Electrode areas for the modalities whose electrodes are FIXED PARTS OF THE PRODUCT rather than a
    /// user-chosen consumable. The tDCS pad is authored per protocol precisely because the user picks it
    /// (OI-CHARGE-04); the BES pads, auricular clip and cervical collar are not swappable, so their area is
    /// a device property both the app and firmware may hold. ⚠ PROVISIONAL — NOT MEASURED (OI-CHARGE-07).
    /// Mirrors firmware/hub_control/include/np_hub_config.h. A SMALLER area is a SMALLER charge budget, so
    /// these may be revised down freely and may only be revised up against a measurement.
    static let BES_ELECTRODE_AREA_CM2: Double = 25.0
    static let VNS_ELECTRODE_AREA_CM2: Double = 0.5
    static let CERVICAL_VNS_ELECTRODE_AREA_CM2: Double = 2.0
    /// Pulse width (seconds) the firmware substitutes when a descriptor declares none: np_mod_cvns.c and
    /// np_session_runner.c both default to 250 µs. The pre-flight must use the same number or it validates
    /// a different waveform than the one that runs.
    static let VNS_DEFAULT_PULSE_WIDTH_SECONDS: Double = 0.00025
    /// Largest declarable per-electrode area: the wire field (np_mod_tdcs_params_t.electrode_area_mcm2) is
    /// a uint16 of milli-cm², so 65535 mcm². Not a clinical limit — an encoding ceiling, well above any
    /// real pad (a large sponge is 35 cm²).
    static let TDCS_MAX_ELECTRODE_AREA_CM2: Double = 65.535
    /// What a NEW tDCS block is seeded with in an editor (a large sponge pad). It is not a limit: the area
    /// is authored per protocol, travels in the signed descriptor, and the safety MCU derives its charge
    /// limit from that declared number (OI-CHARGE-04).
    static let TDCS_DEFAULT_ELECTRODE_AREA_CM2: Double = 35.0
    /// hardware-enforced minimum ramp
    static let TDCS_RAMP_SECONDS: Int = 30
    static let TDCS_MAX_ELECTRODE_PAIRS: Int = 3
    /// VNS (auricular)
    static let VNS_MAX_MILLIAMPS: Double = 2.0
    static let VNS_MIN_HZ: Double = 1.0
    static let VNS_MAX_HZ: Double = 25.0
    /// Visual stimulation
    static let VISUAL_MAX_HZ: Double = 100.0
    /// photoparoxysmal risk zone — clinician unlock required
    static let VISUAL_HIGH_RISK_MIN_HZ: Double = 3.0
    /// firmware halts goggles, <200ms, if EEG shows photoparoxysmal response
    static let VISUAL_HIGH_RISK_MAX_HZ: Double = 30.0
    /// Clinical tACS (T2 only)
    static let CLINICAL_TACS_MAX_MILLIAMPS: Double = 4.0
    /// One driver channel per T2 cap electrode (NP-FW-HD-001 §6.4, NP_HD_DRIVER_CHANNELS). OI-TACS-01: the
    /// hub wire mask carried only 16 bits until 2026-09-07, so every encoder clamped here;
    /// np_mod_clin_tacs_params_t now has a third mask byte and 21 is deliverable, not just authorable.
    static let CLINICAL_TACS_MAX_CHANNELS: Int = 21
    /// HD-tDCS (T2 only, sLORETA-guided 4×1 ring montage)
    static let HD_TDCS_MAX_MILLIAMPS_PER_ELECTRODE: Double = 2.0
    /// Bikson lab 3.5mm electrode safety limit
    static let HD_TDCS_MAX_CURRENT_DENSITY_A_M2: Double = 6.0
    /// Per-phase ceiling on the HD electrode (µC/cm²); Class B np_hd_stim.c aborts at 95% of it. Same
    /// quantity as pulsedMaxPhaseChargeDensityUCcm2, kept separate because the T2 software abort is a
    /// distinct control from the Class C interlock.
    static let HD_TDCS_MAX_CHARGE_DENSITY_UC_CM2: Double = 40.0
    /// HD-tDCS 3.5mm Ag/AgCl sintered electrode: π × (0.175 cm)². Mirrors NP_HD_ELECTRODE_AREA_CM2.
    /// Measured geometry, unlike the three above.
    static let HD_TDCS_ELECTRODE_AREA_CM2: Double = 0.0962
    /// Cervical VNS (T2 accessory, cardiac interlock always active)
    static let CERVICAL_VNS_MAX_MILLIAMPS: Double = 2.0
    /// 40Hz Vibrotactile (provisional accessory)
    static let VIBROTACTILE_FREQUENCY_HZ: Double = 40.0
    static let VIBROTACTILE_FREQ_TOLERANCE_HZ: Double = 0.5
    static let VIBROTACTILE_MAX_G: Double = 1.2
    static let VIBROTACTILE_MIN_G: Double = 0.6
}

/// Return codes of the shared core's C ABI (common/npps-ffi/include/neurone_npps.h). A refusal (1) and an internal error
/// (2) carry a UTF-8 message in the output buffer; a bad argument (3) carries none.
enum NppsStatus {
    /// Success: the output buffer holds the result.
    static let OK: Int32 = 0
    /// The core refused the input; the buffer holds the refusal message.
    static let REFUSED: Int32 = 1
    /// The core panicked; the buffer holds a message.
    static let INTERNAL_ERROR: Int32 = 2
    /// A null pointer or non-UTF-8 input; no buffer.
    static let BAD_ARGUMENT: Int32 = 3
}

/// The 16-bit id of each characteristic (every name ends in _ID, so SESSION_STATE_ID is never mistaken for the session
/// state itself) of the NeurOne BLE service. The 128-bit UUID is the base with its second group replaced by the id
/// (4E455550-XXXX-1000-8000-00805F9B34FB), so the base is written once, here, and every runtime builds its UUIDs from it.
/// `hub: true` marks a characteristic the hub firmware publishes; only those reach the firmware header, because a
/// firmware reference is what the consumable-trigger gate reads as 'the hub produces it'. `required: true` marks the
/// characteristics an app must find before it treats a hub as fully resolved; the others are optional, or T2 only, or not
/// yet published (OI-WA-03).
enum GattIds {
    /// The NeurOne custom service.
    static let SERVICE_ID: Int = 0x0001
    /// NOTIFY 4 B.
    static let SESSION_STATE_ID: Int = 0x0002
    /// NOTIFY 4 B.
    static let SESSION_STATUS_ID: Int = 0x0003
    /// NOTIFY 4 B.
    static let HRV_COHERENCE_ID: Int = 0x0004
    /// NOTIFY 4 B.
    static let PACER_PHASE_ID: Int = 0x0005
    /// NOTIFY 4 B.
    static let IMPEDANCE_RESULT_ID: Int = 0x0006
    /// READ/NOTIFY 8 B, WRITE 1 B (OI-ACC-08).
    static let CONSUMABLE_STATUS_ID: Int = 0x0007
    /// WRITE, signed protocol blob.
    static let PROTOCOL_UPLOAD_ID: Int = 0x0008
    /// WRITE, triggers an EDF+ download.
    static let EDF_REQUEST_ID: Int = 0x0009
    /// WRITE/NOTIFY.
    static let OTA_COMMAND_ID: Int = 0x000A
    /// NOTIFY.
    static let OTA_STATUS_ID: Int = 0x000B
    /// WRITE.
    static let CALIBRATION_CMD_ID: Int = 0x000C
    /// READ/NOTIFY, variable length socket-keyed module-status frames.
    static let ZONE_MODULE_STATUS_ID: Int = 0x000D
    /// NOTIFY.
    static let SHDR_UPLOAD_STATUS_ID: Int = 0x000E
    /// WRITE 1 B (0x01 = stop). Placeholder pending hub BLE firmware (OI-WA-03).
    static let SESSION_STOP_ID: Int = 0x000F
    /// READ 32 B, hub-provisioned TRNG warranty token (OI-WA-03).
    static let WARRANTY_TOKEN_ID: Int = 0x0010
    /// READ/NOTIFY 4 B little-endian uint32: bits 23:16 major, 15:8 minor, 7:0 patch.
    static let FIRMWARE_VERSION_ID: Int = 0x0011
    /// READ/NOTIFY, variable length, read once at link.
    static let SOCKET_MAP_ID: Int = 0x0012
    /// NOTIFY 4 B, cervical VNS gel pad contact result, T2 only (OI-ACC-07). Not published by the hub yet.
    static let CVNS_PAD_STATUS_ID: Int = 0x0013
    /// READ/NOTIFY 4+8n B, cervical VNS offline-fault summary and re-enable state (NP-SW-FAULTMSG-001).
    static let CVNS_FAULT_STATUS_ID: Int = 0x0014
    /// WRITE 1 B 0x01, the wearer's re-enable confirmation after a cardiac cutoff.
    static let CVNS_REENABLE_CONFIRM_ID: Int = 0x0015
    /// WRITE 4 B, little-endian opaque tag of the person using the device.
    static let ACTIVE_USER_ID: Int = 0x0016
    /// READ 32 B, encrypted link only (NP-FW-HUB-001 §4.2, OI-AND-WIRE-02).
    static let DEVICE_SERIAL_ID: Int = 0x0017
}

/// The 128-bit UUID of each id above: 4E455550-0000-1000-8000-00805F9B34FB with its second group replaced.
enum GattUuidStrings {
    /// The NeurOne custom service.
    static let SERVICE_ID: String = "4E455550-0001-1000-8000-00805F9B34FB"
    /// NOTIFY 4 B.
    static let SESSION_STATE_ID: String = "4E455550-0002-1000-8000-00805F9B34FB"
    /// NOTIFY 4 B.
    static let SESSION_STATUS_ID: String = "4E455550-0003-1000-8000-00805F9B34FB"
    /// NOTIFY 4 B.
    static let HRV_COHERENCE_ID: String = "4E455550-0004-1000-8000-00805F9B34FB"
    /// NOTIFY 4 B.
    static let PACER_PHASE_ID: String = "4E455550-0005-1000-8000-00805F9B34FB"
    /// NOTIFY 4 B.
    static let IMPEDANCE_RESULT_ID: String = "4E455550-0006-1000-8000-00805F9B34FB"
    /// READ/NOTIFY 8 B, WRITE 1 B (OI-ACC-08).
    static let CONSUMABLE_STATUS_ID: String = "4E455550-0007-1000-8000-00805F9B34FB"
    /// WRITE, signed protocol blob.
    static let PROTOCOL_UPLOAD_ID: String = "4E455550-0008-1000-8000-00805F9B34FB"
    /// WRITE, triggers an EDF+ download.
    static let EDF_REQUEST_ID: String = "4E455550-0009-1000-8000-00805F9B34FB"
    /// WRITE/NOTIFY.
    static let OTA_COMMAND_ID: String = "4E455550-000A-1000-8000-00805F9B34FB"
    /// NOTIFY.
    static let OTA_STATUS_ID: String = "4E455550-000B-1000-8000-00805F9B34FB"
    /// WRITE.
    static let CALIBRATION_CMD_ID: String = "4E455550-000C-1000-8000-00805F9B34FB"
    /// READ/NOTIFY, variable length socket-keyed module-status frames.
    static let ZONE_MODULE_STATUS_ID: String = "4E455550-000D-1000-8000-00805F9B34FB"
    /// NOTIFY.
    static let SHDR_UPLOAD_STATUS_ID: String = "4E455550-000E-1000-8000-00805F9B34FB"
    /// WRITE 1 B (0x01 = stop). Placeholder pending hub BLE firmware (OI-WA-03).
    static let SESSION_STOP_ID: String = "4E455550-000F-1000-8000-00805F9B34FB"
    /// READ 32 B, hub-provisioned TRNG warranty token (OI-WA-03).
    static let WARRANTY_TOKEN_ID: String = "4E455550-0010-1000-8000-00805F9B34FB"
    /// READ/NOTIFY 4 B little-endian uint32: bits 23:16 major, 15:8 minor, 7:0 patch.
    static let FIRMWARE_VERSION_ID: String = "4E455550-0011-1000-8000-00805F9B34FB"
    /// READ/NOTIFY, variable length, read once at link.
    static let SOCKET_MAP_ID: String = "4E455550-0012-1000-8000-00805F9B34FB"
    /// NOTIFY 4 B, cervical VNS gel pad contact result, T2 only (OI-ACC-07). Not published by the hub yet.
    static let CVNS_PAD_STATUS_ID: String = "4E455550-0013-1000-8000-00805F9B34FB"
    /// READ/NOTIFY 4+8n B, cervical VNS offline-fault summary and re-enable state (NP-SW-FAULTMSG-001).
    static let CVNS_FAULT_STATUS_ID: String = "4E455550-0014-1000-8000-00805F9B34FB"
    /// WRITE 1 B 0x01, the wearer's re-enable confirmation after a cardiac cutoff.
    static let CVNS_REENABLE_CONFIRM_ID: String = "4E455550-0015-1000-8000-00805F9B34FB"
    /// WRITE 4 B, little-endian opaque tag of the person using the device.
    static let ACTIVE_USER_ID: String = "4E455550-0016-1000-8000-00805F9B34FB"
    /// READ 32 B, encrypted link only (NP-FW-HUB-001 §4.2, OI-AND-WIRE-02).
    static let DEVICE_SERIAL_ID: String = "4E455550-0017-1000-8000-00805F9B34FB"
    static let REQUIRED_IDS: [String] = [
        SESSION_STATE_ID,
        SESSION_STATUS_ID,
        HRV_COHERENCE_ID,
        PACER_PHASE_ID,
        IMPEDANCE_RESULT_ID,
        CONSUMABLE_STATUS_ID,
        PROTOCOL_UPLOAD_ID,
        EDF_REQUEST_ID,
        OTA_COMMAND_ID,
        OTA_STATUS_ID,
        CALIBRATION_CMD_ID,
        ZONE_MODULE_STATUS_ID,
        SHDR_UPLOAD_STATUS_ID,
        SESSION_STOP_ID,
    ]
}

/// Fixed value lengths of the NeurOne BLE service, in bytes.
enum GattSizes {
    /// The hub's replay-guard serial (DEVICE_SERIAL characteristic, NP-FW-HUB-001 §4.2): exactly this many
    /// bytes, never padded or truncated.
    static let DEVICE_SERIAL_LEN: Int = 32
}

/// The anonymisation floors a study descriptor must meet before a user may be asked to consent to it (CLAUDE.md §5.3,
/// §6.3). Locked; the device is the only place they can be enforced, because the anonymisation happens on the device.
enum ConsentLimits {
    /// A descriptor's k must be at least this.
    static let MINIMUM_K_ANONYMITY: Int = 10
    /// A descriptor's date rounding must be at least this many days (one week).
    static let MINIMUM_DATE_ROUNDING_DAYS: Int = 7
}

/// The CVNS_FAULT_STATUS frame (NP-SW-FAULTMSG-001): a 4-byte header then up to MAX_WIRE_RECORDS records of RECORD_LEN
/// bytes. The hub writes it and the apps parse it.
enum CvfsWire {
    /// Byte 0 of the frame.
    static let WIRE_VERSION: Int = 1
    /// Header bytes before the first record.
    static let HEADER_LEN: Int = 4
    /// Bytes in one fault record.
    static let RECORD_LEN: Int = 8
    /// Most records one frame carries.
    static let MAX_WIRE_RECORDS: Int = 4
}

/// The ZONE_MODULE_STATUS notification frame (np_zone_notify.h): a 4-byte header then fixed-size records, either status
/// records or socket-map records. The hub writes it and both apps parse it. Version 2 is the static/dynamic split: status
/// records dropped from 4 to 3 bytes when anatomy moved into the socket map. Version 1 (anatomy inline on every change)
/// was never deployed, and version 0 was the retired 5-byte payload with no version byte, so a hub still speaking it
/// decodes as 0 and is rejected rather than misread.
enum ZoneNotify {
    /// Byte 0 of every frame.
    static let FORMAT_VERSION: UInt8 = 0x02
    /// Header bytes before the first record: byte 0 format version, byte 1 flags (including the frame kind
    /// bit), byte 2 fragment index (0-based), byte 3 record count in this fragment.
    static let HEADER_BYTES: Int = 4
    /// Status record: socket id (1-based), module type, flags.
    static let STATUS_REC_BYTES: Int = 3
    /// Map record: socket id (1-based), flags, then x_mm, y_mm, z_mm as int16 little-endian.
    static let MAP_REC_BYTES: Int = 8
    /// Largest 1-based socket id the wire can carry. Firmware ids are 0-based over NP_HEXMAP_MAX_SOCKETS
    /// (128), so the 1-based domain is 1..128, exactly a uint8_t's usable range above zero. Pinned by a
    /// static assert in np_zone_notify.c against NP_HEXMAP_MAX_SOCKETS.
    static let MAX_SOCKET_ID: UInt8 = 128
    /// Frame flag (byte 1): this fragment belongs to a full snapshot. Clear = incremental delta naming only
    /// the sockets that changed. Socket-map frames are always snapshots.
    static let FLAG_SNAPSHOT: UInt8 = 0x01
    /// Frame flag (byte 1): final fragment of this frame sequence. A snapshot is committed by the app only
    /// when a fragment carrying this flag arrives.
    static let FLAG_LAST: UInt8 = 0x02
    /// Frame flag (byte 1), the frame KIND: set = socket-map records, clear = status records. The two
    /// shapes differ in size, so a decoder that assumed the wrong one would misparse rather than fail; the
    /// kind is on the wire so it can be checked, not inferred from which characteristic delivered it.
    static let FLAG_MAP: UInt8 = 0x04
    /// Status-record flag (record byte 2): a module is seated and confirmed in this socket. Clear = socket
    /// is empty (a removal, or an empty socket in a snapshot).
    static let REC_PRESENT: UInt8 = 0x01
    /// Status-record flag (record byte 2): the module failed identification (unrecognised type, bad
    /// contact, failed debounce). PRESENT is clear whenever FAULT is set: an unidentified module is never
    /// reported as usable.
    static let REC_FAULT: UInt8 = 0x02
    /// Map-record flag (record byte 1): this socket is physically wired in this shell. Clear = the address
    /// exists in the geometry table but the shell does not populate it.
    static let MAP_WIRED: UInt8 = 0x01
}

/// Sizes and flags of the signed session descriptor the apps build and the hub verifies (NP-FW-HUB-001 §4).
enum HubDescriptorWire {
    /// The session UUID, the UHDR key.
    static let UUID_LEN: Int = 16
    /// The Ed25519 signature at the end of the blob.
    static let SIG_LEN: Int = 64
    /// Descriptor flag bit 0, computed by the app. It carries no authority: no firmware decision reads it,
    /// because whether a protocol is T2 comes from its modality set and whether this unit may run one is
    /// the safety MCU's signed tier identity (RISK-PWRSRC-10).
    static let FLAG_T2_TIER: UInt8 = 1
}

/// Sizes of the BLE writes the apps make: the Mode 2 protocol upload and the OTA image. Both apps chunk to these.
enum BleTransfer {
    /// The BLE 5 ATT MTU write ceiling, in bytes.
    static let MAX_WRITE_SIZE: Int = 512
    /// The most a START chunk carries (512 − 1 header − 2 length); also the single-chunk threshold.
    static let MAX_CHUNK_PAYLOAD: Int = 509
    /// The most a CONT or END chunk carries (512 − 1 header).
    static let MAX_CONT_PAYLOAD: Int = 511
    /// ATT_MTU(512) − 3 ATT header − 1 OTA opcode − 2 chunk index leaves 506; 496 keeps a margin for GATT
    /// stack overhead.
    static let OTA_CHUNK_SIZE: Int = 496
}

/// The cervical VNS gel-pad assembly.
enum CvnsPad {
    /// Pads checked every session: the bilateral gel-pad assembly, left and right.
    static let CVNS_ELECTRODE_COUNT: Int = 2
}

/// Storage keys and tags both apps use, written once so iOS (UserDefaults) and Android (the key-value store) cannot drift
/// apart.
enum PersistedKeys {
    /// Characterisation enrolment flag. Distinct from WARRANTY_CONSENT_KEY by design: a shared key would
    /// make the two consents one consent.
    static let ENROLMENT_KEY: String = "np.characterisation.enrolled"
    /// Consent generation. Incremented on every grant, never reset by withdrawal. It travels with each
    /// uploaded record so a row cannot outlive the grant that authorised it: a device that withdrew and
    /// later re-enrolled produces records under a new epoch, and rows from the old one are identifiable for
    /// deletion without needing a clock to order them.
    static let CONSENT_EPOCH_KEY: String = "np.characterisation.consent-epoch"
    /// The programme this device is enrolled in. Consent to programme N does not authorise programme N+1;
    /// the firmware rejects a mismatch and emits a standard-only record.
    static let PROGRAMME_ID_KEY: String = "np.characterisation.programme-id"
    /// Current programme generation. A new programme takes a new id and requires fresh enrolment; it does
    /// not inherit this one's participants.
    static let CURRENT_PROGRAMME_ID: Int = 1
    /// Set when the user actively completes the consent onboarding flow (taps Done on the final layer).
    /// Distinct from np.onboarding.consent-shown, which is set when the view appears. Not set when the user
    /// presses Skip, because skipping defers all data decisions including research analytics. Cleared by
    /// blanket research consent withdrawal, because blanket withdrawal implies full data-collection
    /// opt-out. Not the same as the warranty consent key: research and warranty consent are independent and
    /// must never share a key.
    static let RESEARCH_ANALYTICS_KEY: String = "np.research.consent-granted"
    /// Prefix of the per-user key recording the last acknowledged cervical fault session.
    static let CERVICAL_FAULT_LEDGER_KEY: String = "np.cvns.fault-ledger.last-acknowledged-session"
    /// Consumable replacements waiting for the hub to acknowledge.
    static let CONSUMABLE_RESET_KEY: String = "np.consumable.pending-resets"
    /// Per-consumable reminder snooze counts.
    static let SNOOZE_KEY: String = "np.consumable.snooze-counts"
    /// Study participations the user has joined.
    static let PARTICIPATION_KEY: String = "np.consent.study-participations"
    /// Locally stored research suggestions.
    static let RESEARCH_SUGGESTIONS_KEY: String = "np.research.suggestions"
    /// The on-device session history.
    static let SESSION_HISTORY_KEY: String = "np.session.history"
    /// The first hardware setup has completed.
    static let FIRST_SETUP_KEY: String = "np.setup.first-complete"
    /// Persists age-gate completion (ISC-87).
    static let AGE_CONFIRMED_KEY: String = "np.onboarding.age-confirmed"
    /// Domain-separation tag at the head of the canonical form a study descriptor is signed over.
    static let STUDY_DESCRIPTOR_VERSION: String = "NP-STUDY-DESCRIPTOR-V1"
}
