/**
 * HelmetModel — Three.js scene graph for the NeurOne helmet.
 *
 * Physical starting point: Neuronic 1070 Light (dome-style, full-scalp coverage).
 * NeurOne additions: ~80 snap-in hex-tile PBM sockets (NP-HEX-ZM-001), integrated
 * goggles, over-ear audio cups, occipital hub + Boa dial, spring-decoupled EEG
 * pods, VNS auricular clip.
 *
 * Coordinate frame:  +Y up,  +Z toward viewer (front of helmet),  +X right.
 * Head center at origin; crown at Y ≈ +1.0.
 *
 * Zone-module geometry note: the helmet used to model 5 large, fixed,
 * position-unique zone-module slots (ZM-01..05). That architecture is
 * retired — see docs/np_hex_zm_001.md. The socket positions and named zones
 * below come from simulator/js/sockets.generated.js, generated by
 * scripts/generate-simulator-data.ts from the real socket lattice
 * (hardware/np_socket_map.json) and the real named zones
 * (protocols/predefined/00-zones.npps) — not hand-authored here.
 */

import * as THREE from 'three';
import { WL, IMPEDANCE_COLORS } from './colors.js';
import { SOCKETS, ZONES, SOCKET_ZONE_NAMES } from './sockets.generated.js';

// ── shell geometry parameters ────────────────────────────────────────────────
const SHELL_R    = 1.02;
const SHELL_SX   = 0.80;   // lateral compression (head is narrower than tall)
const SHELL_SY   = 1.02;   // slight vertical stretch
const SHELL_SZ   = 0.92;   // front-to-back slightly shallower

// ── EEG electrode positions ───────────────────────────────────────────────────
const EEG_POSITIONS = [
  { name: 'Fp1', phi:  0.28 * Math.PI, theta: 0.14 * Math.PI },
  { name: 'Fp2', phi: -0.28 * Math.PI, theta: 0.14 * Math.PI },
  { name: 'F3',  phi:  0.38 * Math.PI, theta: 0.28 * Math.PI },
  { name: 'F4',  phi: -0.38 * Math.PI, theta: 0.28 * Math.PI },
  { name: 'C3',  phi:  0.52 * Math.PI, theta: 0.38 * Math.PI },
  { name: 'C4',  phi: -0.52 * Math.PI, theta: 0.38 * Math.PI },
  { name: 'P3',  phi:  0.68 * Math.PI, theta: 0.46 * Math.PI },
  { name: 'P4',  phi: -0.68 * Math.PI, theta: 0.46 * Math.PI },
];

// ─────────────────────────────────────────────────────────────────────────────

export class HelmetModel {
  constructor(scene) {
    this.scene   = scene;
    this.group   = new THREE.Group();
    this.sockets = {};        // socket id (1..80) → SocketObject
    this.eeg     = {};        // 'Fp1' … 'P4' → EEGObject
    this.parts   = {};        // named mesh references for accessories

    // name → NPZoneDefinition-shaped object ({ name, sockets, description })
    this._zonesByName = Object.fromEntries(ZONES.map(z => [z.name, z]));

    this._build();
    scene.add(this.group);
  }

  // ─── public ────────────────────────────────────────────────────────────────

  /**
   * Install/remove modules across every socket belonging to a named zone
   * (see protocols/predefined/00-zones.npps). A socket may belong to more
   * than one zone (midline sockets belong to both hemisphere zones of their
   * lobe) — the most recent configureZone() call wins for those sockets.
   */
  configureZone(zoneName, { installed, wavelengths, frequency }) {
    const zone = this._zonesByName[zoneName];
    if (!zone) return;

    zone.sockets.forEach(socketId => {
      const s = this.sockets[socketId];
      if (!s) return;
      s.installed   = !!installed;
      s.wavelengths = wavelengths ?? [];
      s.frequency   = frequency ?? 10;

      // Tiles are opaque (see _buildSockets) — installed/idle state is
      // conveyed by base color + emissive, not opacity. Using real
      // transparency for this was the direct cause of the z-fighting "bite"
      // artifacts between overlapping/adjacent tiles: Three.js sorts
      // transparent objects per-object (not per-pixel), so neighboring
      // semi-transparent tiles punched holes in each other depending on draw
      // order. Opaque materials use the depth buffer correctly instead.
      const mat = s.mesh.material;
      if (!s.installed) {
        mat.color.setHex(0x0a0a16);
        mat.emissiveIntensity = 0;
      } else {
        mat.color.setHex(0x14141f);
        const primaryWL = WL[s.wavelengths[0]];
        mat.emissive.setHex(primaryWL ? primaryWL.threeHex : 0x334455);
      }
    });
  }

  /** Configure which accessories are present. */
  setAccessory(name, visible) {
    if (name === 'intranasal') {
      if (!this._probeAnim) return;
      if (visible) {
        // Allow reversal mid-animation: carry over partial progress
        if (this._probeAnim.mode === 'docked' || this._probeAnim.mode === 'removing') {
          const carry = this._probeAnim.mode === 'removing' ? 1 - this._probeAnim.progress : 0;
          this._probeAnim.mode = 'inserting';
          this._probeAnim.progress = carry;
        }
      } else {
        if (this._probeAnim.mode === 'inserted' || this._probeAnim.mode === 'inserting') {
          const carry = this._probeAnim.mode === 'inserting' ? 1 - this._probeAnim.progress : 0;
          this._probeAnim.mode = 'removing';
          this._probeAnim.progress = carry;
        }
      }
      return;
    }
    if (this.parts[name]) this.parts[name].visible = visible;
  }

  /** Called every animation frame with the current session snapshot. */
  update(wallTimeSec, snap) {
    const dt = this._lastWallTime !== undefined
      ? Math.min(wallTimeSec - this._lastWallTime, 0.1)
      : 0;
    this._lastWallTime = wallTimeSec;

    const t = wallTimeSec;

    // ── PBM socket glow ────────────────────────────────────────────────────
    SOCKETS.forEach(cfg => {
      const s = this.sockets[cfg.id];
      if (!s || !s.installed) return;

      const socketTargeted = s.zoneNames.some(zn => snap.pbm.zones.includes(zn));
      const pbmActive  = snap.pbm.active && socketTargeted;
      const freq       = snap.pbm.frequency;
      const duty       = snap.pbm.dutyCycle;
      const rampI      = snap.pbm.intensity;

      let pulse = 0;
      if (pbmActive) {
        if (freq === 0) {
          // CW
          pulse = rampI;
        } else {
          // Pulsed — square wave based on wallTime, phase-offset per socket so
          // 80 sockets don't flash in perfect lockstep (matches the mild
          // ±15-25% irradiance non-uniformity noted in CLAUDE.md §3).
          const phase = (t * freq + cfg.id * 0.013) % 1;
          pulse = phase < duty ? rampI : 0;
        }
      }

      s.mesh.material.emissiveIntensity = pbmActive ? 0.2 + pulse * 1.3 : 0.05;
    });

    // ── EEG electrodes ─────────────────────────────────────────────────────
    EEG_POSITIONS.forEach(pos => {
      const e = this.eeg[pos.name];
      if (!e) return;
      const impKey = snap.eeg.impedance[pos.name] ?? 'off';
      const col = IMPEDANCE_COLORS[snap.eeg.active ? impKey : 'off'];
      e.material.emissive.setHex(col.three);
      e.material.emissiveIntensity = snap.eeg.active ? 0.8 : 0;
    });

    // ── Visual goggles ─────────────────────────────────────────────────────
    if (this.parts.goggle_left_lens && this.parts.goggle_right_lens) {
      const vis = snap.visual;
      let vPulse = 0;
      if (vis.active) {
        const vPhase = (t * vis.frequency) % 1;
        vPulse = vPhase < 0.5 ? 1 : 0;
      }
      [this.parts.goggle_left_lens, this.parts.goggle_right_lens].forEach(mat => {
        mat.emissive.setHex(vPulse ? 0xFF2200 : 0x000000);
        mat.emissiveIntensity = vPulse * 0.9;
      });
    }

    // ── Hub status LEDs ────────────────────────────────────────────────────
    // CLAUDE.md §4.7: the session LED's pulse is what lets a caregiver confirm
    // the protocol is actively running from across the room — it must stop
    // pulsing on pause, not just when fully stopped, or a paused session looks
    // identical to a running one.
    const live = snap.running && !snap.paused;
    if (this.parts.hubLedPower) {
      const breathe = 0.4 + 0.4 * Math.sin(t * 1.5);
      this.parts.hubLedPower.material.emissiveIntensity = snap.running ? 0.9 : breathe;
    }
    if (this.parts.hubLedSession) {
      // Pulse at session frequency / 4 for visible indication across room
      const sessionFreq = snap.pbm.frequency || 1;
      const sPhase = (t * (sessionFreq / 4)) % 1;
      this.parts.hubLedSession.material.emissiveIntensity = live
        ? (sPhase < 0.5 ? 0.9 : 0.1)
        : (snap.running ? 0.3 : 0); // paused: dim steady, not pulsing; stopped: off
    }

    // ── VNS clip (auricular) ───────────────────────────────────────────────
    if (this.parts.vnsClip) {
      this.parts.vnsClip.visible = snap.vns.active;
      if (snap.vns.active && this.parts.vnsClipMat) {
        const vnsPhase = (t * snap.vns.frequency) % 1;
        const vnsPulse = vnsPhase < 0.5 ? 0.8 : 0.1;
        this.parts.vnsClipMat.emissiveIntensity = vnsPulse;
      }
    }

    // ── Mastoid haptic pad ─────────────────────────────────────────────────
    if (this.parts.hapticPad) {
      if (snap.pbm?.active && this.parts.hapticPadMat) {
        // Vibrate at 40 Hz visually
        const hPhase = (t * 40) % 1;
        const hPulse = hPhase < 0.5 ? 1 : 0;
        this.parts.hapticPadMat.emissiveIntensity = 0.05 + hPulse * 0.4;
      }
    }

    // ── TMS coil ───────────────────────────────────────────────────────────
    this._updateTMSCoil(wallTimeSec, snap);

    // ── Intranasal Y-probe insertion / removal animation ───────────────────
    this._updateProbeAnimation(dt, snap);
  }

  /**
   * Returns an array of { id, name, installed, screenX, screenY, visible }
   * (screen coords) for zone label placement by the HTML overlay system.
   * One label per named zone that currently has at least one installed
   * socket, positioned at the centroid of that zone's installed sockets
   * (80 individual per-socket labels would be unreadable clutter).
   */
  getZoneLabelPositions(camera, renderer) {
    const positions = [];
    const w = renderer.domElement.clientWidth;
    const h = renderer.domElement.clientHeight;

    ZONES.forEach(zone => {
      const installedMeshes = zone.sockets
        .map(id => this.sockets[id])
        .filter(s => s && s.installed);
      if (installedMeshes.length === 0) return;

      const centroid = new THREE.Vector3();
      installedMeshes.forEach(s => centroid.add(s.center));
      centroid.divideScalar(installedMeshes.length);

      const ndc = centroid.clone().project(camera);
      positions.push({
        id: zone.name,
        name: zone.name,
        installed: true,
        screenX: ((ndc.x + 1) / 2) * w,
        screenY: ((-ndc.y + 1) / 2) * h,
        visible: ndc.z < 1, // behind camera test (rough)
      });
    });
    return positions;
  }

  // ─── build helpers ─────────────────────────────────────────────────────────

  _build() {
    this._buildHead();
    this._buildShell();
    this._buildSockets();
    this._buildEEGPods();
    this._buildGoggles();
    this._buildEarCups();
    this._buildHub();
    this._buildOccipitalArch();
    this._buildVNSClip();
    this._buildMastoidPad();
    this._buildIntranasal();
    this._buildTMSCoil();
  }

  _buildHead() {
    // Opaque mannequin head/neck/shoulders — toggled with setDisplayMode().
    // "Floating" mode (no support, product-shot style) is the default; the
    // real device is worn on a head, so "On mannequin" exists to show that
    // context on request rather than always showing a faint see-through ghost.
    const mannequin = new THREE.Group();

    const mat = new THREE.MeshStandardMaterial({
      color: 0xe8c9a3, roughness: 0.85, metalness: 0,
    });

    const headG = new THREE.SphereGeometry(0.95, 48, 48);
    const head = new THREE.Mesh(headG, mat);
    head.scale.set(0.78, 1.0, 0.88);
    head.position.set(0, -0.04, 0);
    mannequin.add(head);

    const neckG = new THREE.CylinderGeometry(0.27, 0.30, 0.55, 24);
    const neck  = new THREE.Mesh(neckG, mat);
    neck.position.set(0, -1.03, 0);
    mannequin.add(neck);

    // Simple shoulder hint (truncated cone) so "on mannequin" reads as a
    // head-and-shoulders mannequin, not a floating ball on a stick.
    const shoulderG = new THREE.CylinderGeometry(0.62, 0.95, 0.62, 32, 1, false);
    const shoulder = new THREE.Mesh(shoulderG, mat);
    shoulder.position.set(0, -1.62, 0);
    mannequin.add(shoulder);

    mannequin.visible = false; // default: floating, no mannequin
    this.group.add(mannequin);
    this.parts.mannequin = mannequin;
  }

  /** 'floating' (no support, default) or 'mannequin' (head/neck/shoulders visible). */
  setDisplayMode(mode) {
    if (this.parts.mannequin) this.parts.mannequin.visible = (mode === 'mannequin');
  }

  _buildShell() {
    // Main CFRP dome — upper ~62% of ellipsoid
    const geo = new THREE.SphereGeometry(
      SHELL_R, 64, 32,
      0, Math.PI * 2,   // full azimuth
      0, Math.PI * 0.62 // polar extent (top to just below equator)
    );
    const mat = new THREE.MeshStandardMaterial({
      color: 0x111122,
      roughness: 0.28,
      metalness: 0.55,
      side: THREE.FrontSide,
      envMapIntensity: 1.0,
    });
    const shell = new THREE.Mesh(geo, mat);
    shell.scale.set(SHELL_SX, SHELL_SY, SHELL_SZ);
    shell.castShadow    = true;
    shell.receiveShadow = true;
    this.group.add(shell);
    this.parts.shell = shell;

    // Bottom rim ring
    const rimG = new THREE.TorusGeometry(SHELL_R * 0.98, 0.018, 8, 64);
    const rimM = new THREE.MeshStandardMaterial({ color: 0x2a3050, roughness: 0.5, metalness: 0.7 });
    const rim  = new THREE.Mesh(rimG, rimM);
    rim.rotation.x = Math.PI / 2;
    rim.scale.set(SHELL_SX * 0.99, 1, SHELL_SZ * 0.99);
    rim.position.y = -0.14;
    this.group.add(rim);
  }

  /**
   * Builds the ~80 hex-tile PBM sockets (NP-HEX-ZM-001), on the INNER
   * (concave, scalp-facing) surface — NP-HEX-ZM-001 §3.4: "the tiling
   * surface is the innermost (emitting-face) surface... a module's
   * scalp-facing face sits no closer to the head than the clear window."
   * Modules emit inward toward the scalp, through the opaque CFRP shell's
   * interior — not outward through it — so they're only visible looking
   * into the helmet's cavity (see the "Inside" camera preset in app.js),
   * matching how the real hardware would actually look from outside (dark,
   * because the shielded shell hides everything happening inside).
   *
   * Each tile's 6 corners are individually projected (sockets.generated.js,
   * built by scripts/generate-simulator-data.ts) rather than stamping a
   * fixed-size flat hexagon at the tile's projected center. Neighboring
   * tiles share literal lattice-space corner coordinates, so their shared
   * corner always projects to the same 3D point — tiles actually share
   * edges instead of gapping or overlapping (see that script's header
   * comment for why a fixed-size-at-center approximation couldn't do this:
   * the projection's tangential distortion isn't uniform with distance from
   * the crown pole).
   *
   * Materials are OPAQUE, not transparent — using real transparency here
   * was the direct cause of "bite"-shaped rendering artifacts: Three.js
   * sorts transparent objects per-object, not per-pixel, so any residual
   * overlap between neighboring semi-transparent tiles punched holes in each
   * other depending on draw order. Opaque tiles use the depth buffer
   * correctly regardless.
   */
  _buildSockets() {
    const INNER_R = SHELL_R * 0.94; // concave scalp-facing surface, inside the shell (SHELL_R)

    SOCKETS.forEach(cfg => {
      const center = this._sph(INNER_R, cfg.phi, cfg.theta);
      const corners = cfg.corners.map(c => this._sph(INNER_R, c.phi, c.theta));

      const positions = new Float32Array(7 * 3);
      positions.set([center.x, center.y, center.z], 0);
      corners.forEach((c, i) => positions.set([c.x, c.y, c.z], 3 + i * 3));

      const indices = [];
      for (let i = 0; i < 6; i++) indices.push(0, 1 + i, 1 + ((i + 1) % 6));

      const geo = new THREE.BufferGeometry();
      geo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
      geo.setIndex(indices);
      geo.computeVertexNormals();

      const mat = new THREE.MeshStandardMaterial({
        color: 0x0a0a16, roughness: 0.55, metalness: 0.25,
        emissive: new THREE.Color(0x000000), emissiveIntensity: 0.05,
        side: THREE.DoubleSide, // visible from inside the cavity regardless of winding
      });
      const mesh = new THREE.Mesh(geo, mat);
      this.group.add(mesh);

      const loopPositions = new Float32Array(6 * 3);
      corners.forEach((c, i) => loopPositions.set([c.x, c.y, c.z], i * 3));
      const edgeGeo = new THREE.BufferGeometry();
      edgeGeo.setAttribute('position', new THREE.BufferAttribute(loopPositions, 3));
      const edge = new THREE.LineLoop(
        edgeGeo,
        new THREE.LineBasicMaterial({ color: 0x223344, transparent: true, opacity: 0.5 })
      );
      this.group.add(edge);

      this.sockets[cfg.id] = {
        mesh,
        center: new THREE.Vector3(center.x, center.y, center.z),
        lobe: cfg.lobe,
        side: cfg.side,
        zoneNames: SOCKET_ZONE_NAMES[cfg.id] ?? [],
        installed: false,
        wavelengths: [],
        frequency: 10,
      };
    });
  }

  _buildEEGPods() {
    EEG_POSITIONS.forEach(pos => {
      const r = SHELL_R * 1.01;
      const { x, y, z } = this._sph(r, pos.phi, pos.theta);

      // Pod sphere
      const geo = new THREE.SphereGeometry(0.026, 8, 8);
      const mat = new THREE.MeshStandardMaterial({
        color: 0x445566, roughness: 0.4, metalness: 0.5,
        emissive: new THREE.Color(0x00ff44), emissiveIntensity: 0,
      });
      const pod = new THREE.Mesh(geo, mat);
      pod.position.set(x, y, z);
      this.group.add(pod);

      // Spring arm (thin cylinder)
      const springLen = 0.035;
      const springG = new THREE.CylinderGeometry(0.005, 0.005, springLen, 6);
      const springM = new THREE.MeshStandardMaterial({ color: 0x667788, roughness: 0.6, metalness: 0.4 });
      const spring  = new THREE.Mesh(springG, springM);

      // Orient spring toward head center
      const dir = new THREE.Vector3(x, y, z).normalize();
      spring.position.set(
        x - dir.x * (springLen / 2),
        y - dir.y * (springLen / 2),
        z - dir.z * (springLen / 2)
      );
      spring.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), dir);
      this.group.add(spring);

      this.eeg[pos.name] = { mesh: pod, material: mat };
    });
  }

  _buildGoggles() {
    const gogGroup = new THREE.Group();
    // Position at front-upper of helmet, tilted slightly forward
    gogGroup.position.set(0, 0.05, SHELL_R * SHELL_SZ * 0.97);
    gogGroup.rotation.x = 0.12;

    const frameMat = new THREE.MeshStandardMaterial({ color: 0x1a1a30, roughness: 0.35, metalness: 0.65 });

    // Bridge
    const bridgeG = new THREE.BoxGeometry(0.12, 0.036, 0.032);
    gogGroup.add(new THREE.Mesh(bridgeG, frameMat));

    // Arm rails (connect to shell)
    [-0.23, 0.23].forEach(x => {
      const armG = new THREE.BoxGeometry(0.10, 0.016, 0.016);
      const arm  = new THREE.Mesh(armG, frameMat);
      arm.position.set(x, 0, -0.04);
      gogGroup.add(arm);
    });

    // Lenses — left and right
    [{ x: -0.22, key: 'left' }, { x: 0.22, key: 'right' }].forEach(({ x, key }) => {
      // Torus frame
      const torusG = new THREE.TorusGeometry(0.095, 0.014, 8, 40);
      const torus  = new THREE.Mesh(torusG, frameMat);
      torus.position.x = x;
      gogGroup.add(torus);

      // LED lens (108 micro-LEDs per lens — shown as emissive disc)
      const lensG = new THREE.CircleGeometry(0.082, 40);
      const lensMat = new THREE.MeshStandardMaterial({
        color: 0x001122, roughness: 0.05, metalness: 0,
        transparent: true, opacity: 0.72,
        emissive: new THREE.Color(0x000000), emissiveIntensity: 0,
      });
      const lens = new THREE.Mesh(lensG, lensMat);
      lens.position.set(x, 0, 0.014);
      gogGroup.add(lens);

      // Shade slot (bottom edge)
      const slotG = new THREE.BoxGeometry(0.20, 0.008, 0.004);
      const slotM = new THREE.MeshStandardMaterial({ color: 0x334455 });
      const slot  = new THREE.Mesh(slotG, slotM);
      slot.position.set(x, -0.11, 0);
      gogGroup.add(slot);

      this.parts[`goggle_${key}_lens`] = lensMat;
    });

    // IR proximity sensor dots (2 per lens)
    for (const x of [-0.22, 0.22]) {
      for (const ox of [-0.07, 0.07]) {
        const irG = new THREE.SphereGeometry(0.007, 6, 6);
        const irM = new THREE.MeshStandardMaterial({ color: 0x330011, emissive: 0x220000, emissiveIntensity: 0.3 });
        const ir  = new THREE.Mesh(irG, irM);
        ir.position.set(x + ox, 0.07, 0.014);
        gogGroup.add(ir);
      }
    }

    // Hall sensor pill (top center, for shade detection)
    const hallG = new THREE.BoxGeometry(0.016, 0.008, 0.006);
    const hallM = new THREE.MeshStandardMaterial({ color: 0x334455 });
    gogGroup.add(new THREE.Mesh(hallG, hallM));

    this.group.add(gogGroup);
    this.parts.goggles = gogGroup;
  }

  _buildEarCups() {
    [{ side: -1, key: 'left' }, { side: 1, key: 'right' }].forEach(({ side, key }) => {
      const cupGroup = new THREE.Group();
      cupGroup.position.set(side * SHELL_R * SHELL_SX * 0.985, 0.15, 0.06);

      // Cup outer disc
      const cupG = new THREE.CylinderGeometry(0.118, 0.115, 0.06, 40);
      const cupM = new THREE.MeshStandardMaterial({ color: 0x111126, roughness: 0.3, metalness: 0.55 });
      const cup  = new THREE.Mesh(cupG, cupM);
      cup.rotation.z = Math.PI / 2;
      cupGroup.add(cup);

      // Planar magnetic driver indicator (concentric rings)
      for (const r of [0.095, 0.07, 0.045]) {
        const grillG = new THREE.TorusGeometry(r, 0.004, 5, 32);
        const grillM = new THREE.MeshStandardMaterial({ color: 0x334455, roughness: 0.8, metalness: 0.3 });
        const grill  = new THREE.Mesh(grillG, grillM);
        grill.rotation.y = Math.PI / 2;
        grill.position.x = side * 0.028;
        cupGroup.add(grill);
      }

      // Mesh frame (user-replaceable silver-coated nylon)
      const meshG = new THREE.CircleGeometry(0.108, 40);
      const meshM = new THREE.MeshStandardMaterial({
        color: 0x667788, roughness: 0.9, metalness: 0.05,
        transparent: true, opacity: 0.55, wireframe: true,
      });
      const mesh = new THREE.Mesh(meshG, meshM);
      mesh.rotation.y = side < 0 ? Math.PI / 2 : -Math.PI / 2;
      mesh.position.x = side * 0.031;
      cupGroup.add(mesh);

      // Bone conduction piezo at mastoid
      const piezoG = new THREE.CylinderGeometry(0.018, 0.018, 0.010, 16);
      const piezoM = new THREE.MeshStandardMaterial({ color: 0x445566, roughness: 0.5, metalness: 0.6 });
      const piezo  = new THREE.Mesh(piezoG, piezoM);
      piezo.rotation.z = Math.PI / 2;
      piezo.position.set(side * 0.032, -0.09, -0.04);
      cupGroup.add(piezo);

      this.group.add(cupGroup);
      this.parts[`ear_${key}`] = cupGroup;
    });
  }

  _buildHub() {
    // Control hub sits at back-lower area of the helmet
    const hubGroup = new THREE.Group();
    hubGroup.position.set(0, -0.10, -SHELL_R * SHELL_SZ * 0.93);
    hubGroup.rotation.x = -0.18;

    // Hub body
    const bodyG = new THREE.BoxGeometry(0.24, 0.17, 0.07);
    const bodyM = new THREE.MeshStandardMaterial({
      color: 0x090916, roughness: 0.38, metalness: 0.72,
    });
    const body = new THREE.Mesh(bodyG, bodyM);
    hubGroup.add(body);

    // Logo recess
    const logoG = new THREE.BoxGeometry(0.10, 0.028, 0.002);
    const logoM = new THREE.MeshStandardMaterial({ color: 0x1a2040 });
    const logo  = new THREE.Mesh(logoG, logoM);
    logo.position.set(0, 0.02, 0.036);
    hubGroup.add(logo);

    // Power LED (green, breathes at idle — on hub in sim; spec: left temple)
    const pwrG = new THREE.SphereGeometry(0.007, 8, 8);
    const pwrM = new THREE.MeshStandardMaterial({ color: 0x00ff44, emissive: 0x00ff44, emissiveIntensity: 0.6 });
    const pwr  = new THREE.Mesh(pwrG, pwrM);
    pwr.position.set(-0.085, 0.055, 0.036);
    hubGroup.add(pwr);
    this.parts.hubLedPower = pwr;

    // Session LED (amber — on hub in sim; spec: right temple)
    const sesG = new THREE.SphereGeometry(0.007, 8, 8);
    const sesM = new THREE.MeshStandardMaterial({ color: 0xff8800, emissive: 0xff8800, emissiveIntensity: 0 });
    const ses  = new THREE.Mesh(sesG, sesM);
    ses.position.set(0.085, 0.055, 0.036);
    hubGroup.add(ses);
    this.parts.hubLedSession = ses;

    // USB-C port
    const usbG = new THREE.BoxGeometry(0.026, 0.013, 0.010);
    const usbM = new THREE.MeshStandardMaterial({ color: 0x2a3a55 });
    const usb  = new THREE.Mesh(usbG, usbM);
    usb.position.set(0, -0.055, 0.036);
    hubGroup.add(usb);

    // Accessory port (3.5 mm audio-style)
    const portG = new THREE.CylinderGeometry(0.007, 0.007, 0.015, 12);
    const portM = new THREE.MeshStandardMaterial({ color: 0x334455 });
    const port  = new THREE.Mesh(portG, portM);
    port.rotation.z = Math.PI / 2;
    port.position.set(0.09, -0.04, 0.036);
    hubGroup.add(port);

    // Air filter vent (hub)
    for (let i = -1; i <= 1; i++) {
      const ventG = new THREE.BoxGeometry(0.004, 0.05, 0.005);
      const ventM = new THREE.MeshStandardMaterial({ color: 0x1a2030 });
      const vent  = new THREE.Mesh(ventG, ventM);
      vent.position.set(i * 0.008, 0, -0.037);
      hubGroup.add(vent);
    }

    // Probe dock slot — molded recess on right face of hub for Y-probe storage
    const dockSlotG = new THREE.BoxGeometry(0.036, 0.088, 0.013);
    const dockSlotM = new THREE.MeshStandardMaterial({ color: 0x040810, roughness: 0.96, metalness: 0 });
    const dockSlot  = new THREE.Mesh(dockSlotG, dockSlotM);
    dockSlot.position.set(0.126, -0.002, 0.0);
    hubGroup.add(dockSlot);
    // Bracket clips that retain the probe in dock
    [-0.038, 0.038].forEach(dy => {
      const clipG = new THREE.BoxGeometry(0.046, 0.005, 0.018);
      const clipM = new THREE.MeshStandardMaterial({ color: 0x334a6a, roughness: 0.5, metalness: 0.65 });
      const clip  = new THREE.Mesh(clipG, clipM);
      clip.position.set(0.126, -0.002 + dy, 0.005);
      hubGroup.add(clip);
    });

    this.group.add(hubGroup);
    this.parts.hub = hubGroup;
  }

  _buildOccipitalArch() {
    // Boa-style occipital arch — curved bar from left to right at back-lower
    const curve = new THREE.QuadraticBezierCurve3(
      new THREE.Vector3(-0.64, -0.22, -0.52),
      new THREE.Vector3( 0,    -0.30, -0.80),
      new THREE.Vector3( 0.64, -0.22, -0.52)
    );
    const pts  = curve.getPoints(32);
    const path = new THREE.CatmullRomCurve3(pts);
    const geo  = new THREE.TubeGeometry(path, 40, 0.012, 6, false);
    const mat  = new THREE.MeshStandardMaterial({ color: 0x2a3a55, roughness: 0.4, metalness: 0.6 });
    const tube = new THREE.Mesh(geo, mat);
    this.group.add(tube);

    // Boa dial at center of arch
    const dialG = new THREE.CylinderGeometry(0.045, 0.040, 0.022, 24);
    const dialM = new THREE.MeshStandardMaterial({ color: 0x3a5070, roughness: 0.3, metalness: 0.7 });
    const dial  = new THREE.Mesh(dialG, dialM);
    dial.rotation.x = Math.PI / 2;
    dial.position.set(0, -0.30, -0.82);
    this.group.add(dial);

    // Dial ridges
    for (let i = 0; i < 12; i++) {
      const a = (i / 12) * Math.PI * 2;
      const ridgeG = new THREE.BoxGeometry(0.004, 0.024, 0.006);
      const ridgeM = new THREE.MeshStandardMaterial({ color: 0x2a4060 });
      const ridge  = new THREE.Mesh(ridgeG, ridgeM);
      ridge.rotation.z = a;
      ridge.position.set(
        Math.cos(a) * 0.042,
        -0.30,
        -0.82 + Math.sin(a) * 0.001
      );
      // orient along arch axis
      ridge.rotation.x = Math.PI / 2;
      ridge.rotation.z = a;
      this.group.add(ridge);
    }
  }

  _buildVNSClip() {
    // Auricular VNS clip — attaches to right ear
    const clipGroup = new THREE.Group();
    clipGroup.position.set(SHELL_R * SHELL_SX + 0.05, 0.10, 0.08);
    clipGroup.visible = false; // hidden until configured

    // Clip body
    const clipG = new THREE.CapsuleGeometry(0.018, 0.06, 4, 12);
    const clipM = new THREE.MeshStandardMaterial({
      color: 0x1a2a3a, roughness: 0.5, metalness: 0.4,
      emissive: 0x44ffaa, emissiveIntensity: 0,
    });
    const clip = new THREE.Mesh(clipG, clipM);
    clipGroup.add(clip);

    // PPG LED indicators
    const ppgG = new THREE.SphereGeometry(0.007, 8, 8);
    const ppgM = new THREE.MeshStandardMaterial({ color: 0xFF7200, emissive: 0xFF7200, emissiveIntensity: 0.4 });
    const ppg  = new THREE.Mesh(ppgG, ppgM);
    ppg.position.y = 0.03;
    clipGroup.add(ppg);

    // Cable to hub
    const cablePath = new THREE.CatmullRomCurve3([
      new THREE.Vector3(0, 0, 0),
      new THREE.Vector3(-0.15, -0.05, -0.10),
      new THREE.Vector3(-0.30, -0.08, -0.20),
    ]);
    const cableG = new THREE.TubeGeometry(cablePath, 12, 0.005, 5, false);
    const cableM = new THREE.MeshStandardMaterial({ color: 0x2a3a4a });
    clipGroup.add(new THREE.Mesh(cableG, cableM));

    this.group.add(clipGroup);
    this.parts.vnsClip    = clipGroup;
    this.parts.vnsClipMat = clipM;
  }

  _buildMastoidPad() {
    // 40 Hz vibrotactile mastoid pad (provisional)
    const padGroup = new THREE.Group();
    padGroup.position.set(-SHELL_R * SHELL_SX * 0.92, 0.06, -0.30);

    const padG = new THREE.CylinderGeometry(0.030, 0.030, 0.010, 24);
    const padM = new THREE.MeshStandardMaterial({
      color: 0x1a2a1a, roughness: 0.7, metalness: 0.1,
      emissive: 0xFFFF44, emissiveIntensity: 0,
    });
    padGroup.add(new THREE.Mesh(padG, padM));
    padGroup.visible = false;

    this.group.add(padGroup);
    this.parts.hapticPad    = padGroup;
    this.parts.hapticPadMat = padM;
  }

  _buildTMSCoil() {
    // T2 focal figure-8 coil — positioned at left prefrontal (DLPFC_L target,
    // ~F3/FC3 in 10-20 system).  Hidden until toggled on via accessories panel.
    //
    // Anatomy: two circular windings side-by-side sharing a center point,
    // with the junction directly over the target cortex (left DLPFC).
    // A straight handle extends posteriorly at ~45° for the clinician's grip.
    // Non-conductive CFRP window is represented by a faint cutout ring in the
    // shell at the coil site — no actual shell geometry cut needed in the sim.

    const coilGroup = new THREE.Group();

    // Position over left prefrontal cortex (phi ≈ 0.38π, theta ≈ 0.25π → F3/FC3)
    const { x, y, z } = this._sph(SHELL_R * 1.014, 0.38 * Math.PI, 0.25 * Math.PI);
    coilGroup.position.set(x, y, z);
    // Orient the group: tilt outward from sphere surface, then rotate so the
    // handle runs from the coil toward the back of the head.
    coilGroup.lookAt(0, 0, 0);
    coilGroup.rotateY(Math.PI);        // flip to face outward
    coilGroup.rotateZ(-0.30);          // cant the handle rearward
    coilGroup.visible = false;

    // ── CFRP coil housing (shared flat disc between the two windings) ─────
    const housingG = new THREE.CylinderGeometry(0.095, 0.095, 0.018, 40);
    const housingM = new THREE.MeshStandardMaterial({
      color: 0x0e1218, roughness: 0.28, metalness: 0.55,
    });
    const housing = new THREE.Mesh(housingG, housingM);
    housing.rotation.x = Math.PI / 2;
    coilGroup.add(housing);

    // ── Figure-8 windings: two tori offset left and right from center ─────
    const windingMat = new THREE.MeshStandardMaterial({
      color: 0x2a3f5f, roughness: 0.35, metalness: 0.75,
      emissive: new THREE.Color(0x0033aa), emissiveIntensity: 0,
    });

    const WINDING_R   = 0.048;  // winding ring major radius
    const WINDING_T   = 0.012;  // tube radius
    const WINDING_OFF = 0.046;  // left/right offset from center

    [-1, 1].forEach(side => {
      const windG = new THREE.TorusGeometry(WINDING_R, WINDING_T, 10, 40);
      const wind  = new THREE.Mesh(windG, windingMat.clone());
      wind.position.set(side * WINDING_OFF, 0, 0);
      wind.rotation.x = Math.PI / 2;
      coilGroup.add(wind);

      // Store references so animation can drive emissive intensity
      if (!this._tmsWindings) this._tmsWindings = [];
      this._tmsWindings.push(wind.material);
    });

    // ── center junction block (where the two windings meet) ───────────────
    const jctG = new THREE.BoxGeometry(0.022, 0.022, 0.022);
    const jctM = new THREE.MeshStandardMaterial({ color: 0x1a2a40, roughness: 0.4, metalness: 0.7 });
    coilGroup.add(new THREE.Mesh(jctG, jctM));

    // ── Handle — runs rearward from center ────────────────────────────────
    //   Built from a tapered cylinder (wider at coil, narrower at grip end)
    const handleG = new THREE.CylinderGeometry(0.016, 0.012, 0.22, 12);
    const handleM = new THREE.MeshStandardMaterial({ color: 0x111922, roughness: 0.5, metalness: 0.35 });
    const handle  = new THREE.Mesh(handleG, handleM);
    handle.rotation.x = Math.PI / 2;
    handle.position.z = -0.13;   // extends away from head in local -Z space
    coilGroup.add(handle);

    // ── Handle grip ridges (3 rings for tactile grip) ─────────────────────
    for (let i = 0; i < 3; i++) {
      const ridgeG = new THREE.TorusGeometry(0.016, 0.003, 5, 16);
      const ridgeM = new THREE.MeshStandardMaterial({ color: 0x1e2d42, roughness: 0.6, metalness: 0.4 });
      const ridge  = new THREE.Mesh(ridgeG, ridgeM);
      ridge.rotation.x = Math.PI / 2;
      ridge.position.z = -0.08 - i * 0.038;
      coilGroup.add(ridge);
    }

    // ── Cable — runs from handle end toward hub ───────────────────────────
    // Points in local coil space; starts at handle tip, curves rearward and down
    const cablePts = [
      new THREE.Vector3(0,  0, -0.24),
      new THREE.Vector3(0.06, -0.08, -0.35),
      new THREE.Vector3(0.08, -0.18, -0.45),
    ];
    const cableG = new THREE.TubeGeometry(new THREE.CatmullRomCurve3(cablePts), 16, 0.006, 6, false);
    const cableM = new THREE.MeshStandardMaterial({ color: 0x1a2535, roughness: 0.8 });
    coilGroup.add(new THREE.Mesh(cableG, cableM));

    // ── CFRP non-conductive window indicator at coil site on shell ────────
    // A faint translucent ring flush with the shell marks the window cutout.
    const windowG = new THREE.TorusGeometry(0.094, 0.006, 6, 40);
    const windowM = new THREE.MeshStandardMaterial({
      color: 0x334455, roughness: 0.9, metalness: 0,
      transparent: true, opacity: 0.35, depthWrite: false,
    });
    const windowRing = new THREE.Mesh(windowG, windowM);
    windowRing.rotation.x = Math.PI / 2;
    windowRing.position.z = 0.010;   // slightly proud of coil face toward head
    coilGroup.add(windowRing);

    // ── Pulse-glow point light (hidden at rest, fires on each TMS pulse) ──
    const pulseLight = new THREE.PointLight(0x4488ff, 0, 0.35);
    pulseLight.position.set(0, 0, 0.02);
    coilGroup.add(pulseLight);

    this.group.add(coilGroup);
    this.parts.tmsCoil       = coilGroup;
    this.parts.tmsPulseLight = pulseLight;
    this._tmsWindings        = this._tmsWindings ?? [];
    this._tmsPulseT          = 0;   // tracks time since last simulated pulse
  }

  _updateTMSCoil(wallTimeSec, snap) {
    const coil = this.parts.tmsCoil;
    if (!coil) return;

    const tmsActive = snap.tms?.active ?? false;
    coil.visible = tmsActive;
    if (!tmsActive) return;

    const freq = snap.tms?.frequency ?? 10;    // Hz (rTMS rep rate)
    const t    = wallTimeSec;

    // Simulate discrete TMS pulses at the protocol frequency.
    // Each pulse: sharp rise over ~4 ms then exponential decay over ~50 ms.
    // We use a sawtooth modulo the pulse period and a short exponential window.
    const period    = freq > 0 ? 1 / freq : 1;
    const phase     = (t % period) / period;   // 0–1 within each inter-pulse interval
    // Brief rectangular trigger window (first 5% of period → ≤5 ms at 10 Hz)
    const PULSE_W   = 0.05;
    const pulseOn   = phase < PULSE_W;
    const decay     = pulseOn ? 1 : Math.max(0, 1 - (phase - PULSE_W) / 0.12);
    const intensity = decay;

    // Drive winding emissive — blue-white flash
    if (this._tmsWindings) {
      this._tmsWindings.forEach(mat => {
        mat.emissive.setHex(intensity > 0.02 ? 0x2255ff : 0x001133);
        mat.emissiveIntensity = 0.05 + intensity * 1.8;
      });
    }

    // Point light flash at pulse peak
    if (this.parts.tmsPulseLight) {
      this.parts.tmsPulseLight.intensity = intensity * 2.5;
    }
  }

  _buildIntranasal() {
    const probeGroup = new THREE.Group();

    // Animation state — probe starts docked at hub right-face slot
    const dockedEuler   = new THREE.Euler(Math.PI + 0.18, 0.10, 0.18);
    const insertedEuler = new THREE.Euler(0.44, 0, 0);

    this._probeAnim = {
      mode:         'docked',   // 'docked' | 'inserting' | 'inserted' | 'removing'
      progress:     1,
      dockedPos:    new THREE.Vector3(0.14, -0.14, -0.84),
      dockedQuat:   new THREE.Quaternion().setFromEuler(dockedEuler),
      // Mid-point of Bézier arc — probe swings out to the right then forward
      midPos:       new THREE.Vector3(0.40, 0.04, -0.08),
      insertedPos:  new THREE.Vector3(0, -0.32, 0.68),
      insertedQuat: new THREE.Quaternion().setFromEuler(insertedEuler),
    };

    // Apply initial docked transform
    probeGroup.position.copy(this._probeAnim.dockedPos);
    probeGroup.quaternion.copy(this._probeAnim.dockedQuat);

    // ── Y-junction silicone over-mold ──────────────────────────────────────
    const overmG = new THREE.SphereGeometry(0.022, 10, 8);
    const overmM = new THREE.MeshStandardMaterial({
      color: 0x2b3f58, roughness: 0.78, metalness: 0.04,
    });
    probeGroup.add(new THREE.Mesh(overmG, overmM));

    // Pogo-pin connector ring at base (resistive sleeve authentication)
    const pogoG = new THREE.TorusGeometry(0.012, 0.003, 6, 18);
    const pogoM = new THREE.MeshStandardMaterial({ color: 0x667788, roughness: 0.3, metalness: 0.75 });
    const pogo  = new THREE.Mesh(pogoG, pogoM);
    pogo.rotation.x = Math.PI / 2;
    pogo.position.y = -0.016;
    probeGroup.add(pogo);

    // Reference LED at probe base — optical code indicator, always-on orange
    const refG = new THREE.SphereGeometry(0.0042, 7, 5);
    const refM = new THREE.MeshStandardMaterial({
      color: 0xFF7000, emissive: 0xFF7000, emissiveIntensity: 0.5,
    });
    probeGroup.add(new THREE.Mesh(refG, refM));
    this.parts.intranasalRefLed = refM;

    // ── Connection cable (to hub dock pogo) ─────────────────────────────────
    const cablePts = [
      new THREE.Vector3(0, -0.022, 0),
      new THREE.Vector3(0.008, -0.050, -0.008),
      new THREE.Vector3(0.018, -0.085, -0.018),
    ];
    probeGroup.add(new THREE.Mesh(
      new THREE.TubeGeometry(new THREE.CatmullRomCurve3(cablePts), 10, 0.0042, 5, false),
      new THREE.MeshStandardMaterial({ color: 0x1a2535, roughness: 0.8 })
    ));

    // ── Bilateral probe arms ─────────────────────────────────────────────────
    const armLedMats = [];

    [[-1, 'left'], [1, 'right']].forEach(([sign]) => {
      // Arm curve — spreads upward and slightly outward from junction
      const pts = [
        new THREE.Vector3(sign * 0.006, 0.012, 0),
        new THREE.Vector3(sign * 0.015, 0.034, 0.003),
        new THREE.Vector3(sign * 0.021, 0.062, 0.003),
        new THREE.Vector3(sign * 0.022, 0.094, 0.001),
      ];
      const curve = new THREE.CatmullRomCurve3(pts);

      // Silicone probe tube
      probeGroup.add(new THREE.Mesh(
        new THREE.TubeGeometry(curve, 20, 0.0058, 7, false),
        new THREE.MeshStandardMaterial({
          color: 0x5588aa, roughness: 0.55, metalness: 0.06,
          transparent: true, opacity: 0.92,
        })
      ));

      // Depth-stop rings: 15 / 20 / 25 mm markers (3 per arm)
      // center ring colored blue as the clinical target depth (20 mm)
      [[0.33, 0x88aacc], [0.55, 0x44aaee], [0.75, 0x88aacc]].forEach(([tRing, col]) => {
        const rPos = curve.getPoint(tRing);
        const tan  = curve.getTangent(tRing);
        const ring = new THREE.Mesh(
          new THREE.TorusGeometry(0.0078, 0.0016, 5, 14),
          new THREE.MeshStandardMaterial({ color: col, roughness: 0.4 })
        );
        ring.position.copy(rPos);
        ring.quaternion.setFromUnitVectors(new THREE.Vector3(0, 0, 1), tan);
        probeGroup.add(ring);
      });

      // Hygiene sleeve — consumable translucent tip covering the distal 26%
      const t0  = curve.getPoint(0.74);
      const t1  = curve.getPoint(1.00);
      const dir = t1.clone().sub(t0);
      const len = dir.length();
      const mid = t0.clone().add(t1).multiplyScalar(0.5);
      const slv = new THREE.Mesh(
        new THREE.CylinderGeometry(0.0070, 0.0065, len, 8),
        new THREE.MeshStandardMaterial({
          color: 0xc4ddf0, roughness: 0.88, metalness: 0,
          transparent: true, opacity: 0.78,
        })
      );
      slv.position.copy(mid);
      slv.quaternion.setFromUnitVectors(new THREE.Vector3(0, 1, 0), dir.normalize());
      probeGroup.add(slv);

      // LED tip — 660 nm primary (shown as red dot, glows when inserted + PBM active)
      const tipPos = curve.getPoint(1.0);
      const ledM = new THREE.MeshStandardMaterial({
        color: 0xFF2200, emissive: 0xFF2200, emissiveIntensity: 0, roughness: 0.12,
      });
      const ledMesh = new THREE.Mesh(new THREE.SphereGeometry(0.0052, 8, 6), ledM);
      ledMesh.position.copy(tipPos).addScaledVector(curve.getTangent(1.0), 0.005);
      probeGroup.add(ledMesh);
      armLedMats.push(ledM);
    });

    this.group.add(probeGroup);
    this.parts.intranasal     = probeGroup;
    this.parts.intranasalLeds = armLedMats;
  }

  // ─── probe animation ─────────────────────────────────────────────────────

  _updateProbeAnimation(dt, snap) {
    if (!this._probeAnim || !this.parts.intranasal) return;
    const anim  = this._probeAnim;
    const probe = this.parts.intranasal;
    const SPEED = 1.0; // full dock-to-face travel in ~1 s

    // Advance progress
    if (anim.mode === 'inserting' || anim.mode === 'removing') {
      anim.progress = Math.min(1, anim.progress + dt * SPEED);
      if (anim.progress >= 1) {
        anim.mode = anim.mode === 'inserting' ? 'inserted' : 'docked';
      }
    }

    // Scalar lerp factor: 0 = docked, 1 = inserted
    const rawT = anim.mode === 'docked'    ? 0
               : anim.mode === 'inserted'  ? 1
               : anim.mode === 'inserting' ? anim.progress
               :                            1 - anim.progress; // removing

    // Cubic ease-in-out
    const eased = rawT < 0.5
      ? 4 * rawT * rawT * rawT
      : 1 - Math.pow(-2 * rawT + 2, 3) / 2;

    // Quadratic Bézier arc (p0 = docked, p1 = mid swing-out, p2 = inserted)
    // The arc curves the probe around the right side of the head rather than
    // passing straight through the shell.
    const { dockedPos: p0, midPos: p1, insertedPos: p2 } = anim;
    const u = 1 - eased;
    probe.position.set(
      u*u*p0.x + 2*u*eased*p1.x + eased*eased*p2.x,
      u*u*p0.y + 2*u*eased*p1.y + eased*eased*p2.y,
      u*u*p0.z + 2*u*eased*p1.z + eased*eased*p2.z,
    );

    // Quaternion slerp — avoids gimbal lock / long-way-round euler interpolation
    probe.quaternion.slerpQuaternions(anim.dockedQuat, anim.insertedQuat, eased);

    // Reference LED (always on when probe is not fully docked)
    if (this.parts.intranasalRefLed) {
      this.parts.intranasalRefLed.emissiveIntensity = eased > 0.1
        ? 0.5
        : 0.5 * (eased / 0.1);
    }

    // Arm LED tips: ramp up in the final quarter of insertion; brightness
    // doubles when a PBM session is actively running.
    const pbmOn = snap?.pbm?.active ?? false;
    const glow  = eased > 0.75
      ? ((eased - 0.75) / 0.25) * (pbmOn ? 1.0 : 0.30)
      : 0;
    if (this.parts.intranasalLeds) {
      this.parts.intranasalLeds.forEach(m => { m.emissiveIntensity = glow; });
    }
  }

  // ─── geometry utility ─────────────────────────────────────────────────────

  /**
   * Convert spherical (r, phi, theta) → Cartesian (x, y, z) accounting for
   * the asymmetric helmet shell scale.
   * phi   = azimuth from +Z (0 = front)
   * theta = polar angle from +Y (0 = crown)
   */
  _sph(r, phi, theta) {
    const sinT = Math.sin(theta);
    const cosT = Math.cos(theta);
    const sinP = Math.sin(phi);
    const cosP = Math.cos(phi);
    return {
      x: r * sinT * sinP * SHELL_SX,
      y: r * cosT          * SHELL_SY,
      z: r * sinT * cosP * SHELL_SZ,
    };
  }
}
