//! Compile-time constants for the core: `common/npps/constants.json` and the helmet's socket map.
//!
//! The core has no copy of a constant to go stale. A figure the other runtimes also need is written once, in
//! `common/npps/constants.json` (and `hardware/np_socket_map.json` for the socket numbering), and this turns it into
//! Rust constants with the same UPPER_SNAKE_CASE names every runtime uses (`scripts/sync-constants.ts` writes the others).
//! A typo in a constant name is a compile error here, where a runtime lookup by string would have been a panic.

use serde_json::Value;
use std::{env, fs, path::PathBuf};

fn read(path: &PathBuf) -> Value {
    println!("cargo:rerun-if-changed={}", path.display());
    serde_json::from_str(&fs::read_to_string(path).unwrap_or_else(|e| panic!("{}: {e}", path.display())))
        .unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let root = manifest.join("../..");
    let mut out = String::from("// Generated by build.rs from common/npps/constants.json and hardware/np_socket_map.json.\n\n");

    let constants = read(&root.join("common/npps/constants.json"));
    for group in constants["groups"].as_array().expect("constants.json has groups") {
        if !group["targets"].as_array().map_or(false, |t| t.iter().any(|x| x == "rust")) {
            continue;
        }
        let module = group["rust"].as_str().expect("a rust group names its module");
        out.push_str(&format!("pub mod {module} {{\n"));
        for c in group["constants"].as_array().unwrap() {
            let name = c["name"].as_str().unwrap();
            if let Some(note) = c["note"].as_str() {
                out.push_str(&format!("    /// {note}\n"));
            }
            let int_type = group["intTypes"]["rust"].as_str().unwrap_or("i64");
            if c["int"] == true && int_type != "f64" {
                out.push_str(&format!("    pub const {name}: {int_type} = {};\n", c["value"].as_i64().unwrap()));
            } else {
                // `{:?}` keeps the decimal point, so `1` is written `1.0` and stays an f64 literal.
                out.push_str(&format!("    pub const {name}: f64 = {:?};\n", c["value"].as_f64().unwrap()));
            }
        }
        out.push_str("}\n\n");
    }

    // The helmet's socket numbering: `scripts/sync-socket-map.ts` writes it, and the parser's "is this a socket" check reads it.
    let map = read(&root.join("hardware/np_socket_map.json"));
    out.push_str("/// The helmet's socket ids, from hardware/np_socket_map.json.\npub mod socket_lattice {\n");
    for (name, key) in [("SOCKET_NUMBERING_BASE", "numberingBase"), ("SOCKET_ID_MIN", "socketIdMin"), ("SOCKET_ID_MAX", "socketIdMax")] {
        out.push_str(&format!("    pub const {name}: i64 = {};\n", map[key].as_i64().unwrap_or_else(|| panic!("np_socket_map.json has no {key}"))));
    }
    out.push_str("}\n");

    fs::write(PathBuf::from(env::var("OUT_DIR").unwrap()).join("constants.rs"), out).unwrap();
}
