// GENERATED by scripts/sync-constants.ts from common/npps/constants.json. DO NOT EDIT: change the JSON and re-run it.

// Every hardware ceiling and fixed device figure the apps and the shared validator use. The firmware enforces them
// independently; no dosage limit or clinician override can exceed them.
export const NPHardwareLimits = {
  // PBM Transcranial / Intranasal (shared firmware limit)
  PBM_DUTY_CYCLE_MAX_PERCENT: 25,
  // pending RISK-03 regulatory opinion
  PBM_PULSED_PEAK_MW_CM2: 400.0,
  PBM_CW_MAX_MW_CM2: 200.0,
  // Deep 1170 nm PBM ceiling (CLAUDE.md §3: ≤1,000 mW/cm², TEC-stabilised).
  PBM_DEEP_MAX_MW_CM2: 1000.0,
  // Aggregate PBM irradiance ceiling (OI-PBM-05, three-channel combined). Pending RISK-03 regulatory opinion scope
  // expansion (Q4–Q6).
  PBM_AGGREGATE_MAX_MW_CM2: 600.0,
  // BES / tACS (consumer: Brainwave Entrainment Stimulation)
  BES_TACS_MAX_MILLIAMPS: 1.0,
  BES_TACS_MIN_HZ: 0.5,
  BES_TACS_MAX_HZ: 40.0,
  // tDCS (consumer: Cortical Priming Stimulation)
  TDCS_MIN_MILLIAMPS: 0.1,
  TDCS_MAX_MILLIAMPS: 2.0,
  // OI-CHARGE-04 (closed 2026-09-09): this IS checked here now. There is no web electrode-area constant to add,
  // because there is no longer a global electrode area on any client — the area is authored per protocol
  // (TDCSParams.electrodeAreaCm2), travels in the signed session descriptor, and the safety MCU derives its charge
  // limit from that same declared number. What used to be a 35-vs-25 disagreement between the app's assumption and
  // the enforcer's is now one transmitted value. OI-CHARGE-05 (a)(d) 2026-09-15: RENAMED AND RE-SOURCED. This used
  // to be `tdcsMaxChargeDensityUCcm2: 40.0`, a misnomer that concealed a 1000× divergence — `I(mA) × t(s) /
  // A(cm²)` is mC/cm², so the clients enforced 40 mC/cm² while the safety MCU enforced 40 µC/cm². The name now
  // states the unit AND the period, because both were ambiguous and each hid a different defect: the unit hid the
  // 1000×, and the missing period hid that a per-phase pulsed figure was being applied to a DC session dose. 150
  // mC/cm² per session per electrode, derived rather than asserted (the old 40 had no source anywhere in the tree
  // — the citation chain was circular). Bounds the conventional large-pad human tDCS envelope: the most-exposed
  // large RCT protocol in docs/tdcs_database_full.csv is Brunoni ELECT-TDCS 2013/2017 at 2 mA × 30 min on 25 cm² =
  // 144 mC/cm². Margin check: 35× below Liebetanz 2009's measured rat epicranial DC lesion threshold of 5,240
  // mC/cm². Full derivation: NP-DT-001 DI-SAFE-01.
  TDCS_MAX_SESSION_CHARGE_DENSITY_MC_CM2: 150.0,
  // Per-PHASE ceiling for the charge-balanced biphasic modalities — BES/tACS, VNS, cervical VNS, clinical tACS
  // (OI-CHARGE-05 (b)). 40 µC/cm² is a real and correct figure in this form (Shannon 1992 / McCreery 1990 pulsed
  // charge-injection limits); it is the number the tree has always carried, now applied to the waveform class it
  // is actually about. Net charge on these modalities is ~zero by construction, so a session-cumulative dose is
  // not a physical quantity for them and is not checked.
  PULSED_MAX_PHASE_CHARGE_DENSITY_UC_CM2: 40.0,
  // Electrode areas for the modalities whose electrodes are FIXED PARTS OF THE PRODUCT rather than a user-chosen
  // consumable. The tDCS pad is authored per protocol precisely because the user picks it (OI-CHARGE-04); the BES
  // pads, auricular clip and cervical collar are not swappable, so their area is a device property both the app
  // and firmware may hold. ⚠ PROVISIONAL — NOT MEASURED (OI-CHARGE-07). Mirrors
  // firmware/hub_control/include/np_hub_config.h. A SMALLER area is a SMALLER charge budget, so these may be
  // revised down freely and may only be revised up against a measurement.
  BES_ELECTRODE_AREA_CM2: 25.0,
  VNS_ELECTRODE_AREA_CM2: 0.5,
  CERVICAL_VNS_ELECTRODE_AREA_CM2: 2.0,
  // Pulse width (seconds) the firmware substitutes when a descriptor declares none: np_mod_cvns.c and
  // np_session_runner.c both default to 250 µs. The pre-flight must use the same number or it validates a
  // different waveform than the one that runs.
  VNS_DEFAULT_PULSE_WIDTH_SECONDS: 0.00025,
  // Largest declarable per-electrode area: the wire field (np_mod_tdcs_params_t.electrode_area_mcm2) is a uint16
  // of milli-cm², so 65535 mcm². Not a clinical limit — an encoding ceiling, well above any real pad (a large
  // sponge is 35 cm²).
  TDCS_MAX_ELECTRODE_AREA_CM2: 65.535,
  // What a NEW tDCS block is seeded with in an editor (a large sponge pad). It is not a limit: the area is
  // authored per protocol, travels in the signed descriptor, and the safety MCU derives its charge limit from that
  // declared number (OI-CHARGE-04).
  TDCS_DEFAULT_ELECTRODE_AREA_CM2: 35.0,
  // hardware-enforced minimum ramp
  TDCS_RAMP_SECONDS: 30,
  TDCS_MAX_ELECTRODE_PAIRS: 3,
  // VNS (auricular)
  VNS_MAX_MILLIAMPS: 2.0,
  VNS_MIN_HZ: 1.0,
  VNS_MAX_HZ: 25.0,
  // Authored auricular VNS pulse width, µs. ASSUMED (UC-071): the range the published taVNS studies span (Matsuoka
  // 2025 Table 3b, 50–500 µs), not a derived or standard limit. The charge ceiling (40 µC/cm² per phase) is what
  // bounds the dose; this bounds the encoding to what has been studied. 0 on the wire still means the firmware
  // default, 250 µs.
  VNS_MIN_PULSE_WIDTH_US: 50.0,
  VNS_MAX_PULSE_WIDTH_US: 500.0,
  // Visual stimulation
  VISUAL_MAX_HZ: 100.0,
  // photoparoxysmal risk zone — clinician unlock required
  VISUAL_HIGH_RISK_MIN_HZ: 3.0,
  // firmware halts goggles, <200ms, if EEG shows photoparoxysmal response
  VISUAL_HIGH_RISK_MAX_HZ: 30.0,
  // Clinical tACS (T2 only)
  CLINICAL_TACS_MAX_MILLIAMPS: 4.0,
  // One driver channel per T2 cap electrode (NP-FW-HD-001 §6.4, NP_HD_DRIVER_CHANNELS). OI-TACS-01: the hub wire
  // mask carried only 16 bits until 2026-09-07, so every encoder clamped here; np_mod_clin_tacs_params_t now has a
  // third mask byte and 21 is deliverable, not just authorable.
  CLINICAL_TACS_MAX_CHANNELS: 21,
  // HD-tDCS (T2 only, sLORETA-guided 4×1 ring montage)
  HD_TDCS_MAX_MILLIAMPS_PER_ELECTRODE: 2.0,
  // Bikson lab 3.5mm electrode safety limit
  HD_TDCS_MAX_CURRENT_DENSITY_A_M2: 6.0,
  // Per-phase ceiling on the HD electrode (µC/cm²); Class B np_hd_stim.c aborts at 95% of it. Same quantity as
  // pulsedMaxPhaseChargeDensityUCcm2, kept separate because the T2 software abort is a distinct control from the
  // Class C interlock.
  HD_TDCS_MAX_CHARGE_DENSITY_UC_CM2: 40.0,
  // HD-tDCS 3.5mm Ag/AgCl sintered electrode: π × (0.175 cm)². Mirrors NP_HD_ELECTRODE_AREA_CM2. Measured
  // geometry, unlike the three above.
  HD_TDCS_ELECTRODE_AREA_CM2: 0.0962,
  // Cervical VNS (T2 accessory, cardiac interlock always active)
  CERVICAL_VNS_MAX_MILLIAMPS: 2.0,
  // 40Hz Vibrotactile (provisional accessory)
  VIBROTACTILE_FREQUENCY_HZ: 40.0,
  VIBROTACTILE_FREQ_TOLERANCE_HZ: 0.5,
  VIBROTACTILE_MAX_G: 1.2,
  VIBROTACTILE_MIN_G: 0.6,
} as const;

// Return codes of the shared core's C ABI (common/npps-ffi/include/neurone_npps.h). A refusal (1) and an internal error
// (2) carry a UTF-8 message in the output buffer; a bad argument (3) carries none.
export const NppsStatus = {
  // Success: the output buffer holds the result.
  OK: 0,
  // The core refused the input; the buffer holds the refusal message.
  REFUSED: 1,
  // The core panicked; the buffer holds a message.
  INTERNAL_ERROR: 2,
  // A null pointer or non-UTF-8 input; no buffer.
  BAD_ARGUMENT: 3,
} as const;

// The 16-bit id of each characteristic (every name ends in _ID, so SESSION_STATE_ID is never mistaken for the session
// state itself) of the NeurOne BLE service. The 128-bit UUID is the base with its second group replaced by the id
// (4E455550-XXXX-1000-8000-00805F9B34FB), so the base is written once, here, and every runtime builds its UUIDs from it.
// `hub: true` marks a characteristic the hub firmware publishes; only those reach the firmware header, because a
// firmware reference is what the consumable-trigger gate reads as 'the hub produces it'. `required: true` marks the
// characteristics an app must find before it treats a hub as fully resolved; the others are optional, or T2 only, or not
// yet published (OI-WA-03).
export const GattIds = {
  // The NeurOne custom service.
  SERVICE_ID: 0x0001,
  // NOTIFY 4 B.
  SESSION_STATE_ID: 0x0002,
  // NOTIFY 4 B.
  SESSION_STATUS_ID: 0x0003,
  // NOTIFY 4 B.
  HRV_COHERENCE_ID: 0x0004,
  // NOTIFY 4 B.
  PACER_PHASE_ID: 0x0005,
  // NOTIFY 4 B.
  IMPEDANCE_RESULT_ID: 0x0006,
  // READ/NOTIFY 8 B, WRITE 1 B (OI-ACC-08).
  CONSUMABLE_STATUS_ID: 0x0007,
  // WRITE, signed protocol blob.
  PROTOCOL_UPLOAD_ID: 0x0008,
  // WRITE, triggers an EDF+ download.
  EDF_REQUEST_ID: 0x0009,
  // WRITE/NOTIFY.
  OTA_COMMAND_ID: 0x000A,
  // NOTIFY.
  OTA_STATUS_ID: 0x000B,
  // WRITE.
  CALIBRATION_CMD_ID: 0x000C,
  // READ/NOTIFY, variable length socket-keyed module-status frames.
  ZONE_MODULE_STATUS_ID: 0x000D,
  // NOTIFY.
  SHDR_UPLOAD_STATUS_ID: 0x000E,
  // WRITE 1 B (0x01 = stop). Placeholder pending hub BLE firmware (OI-WA-03).
  SESSION_STOP_ID: 0x000F,
  // READ 32 B, hub-provisioned TRNG warranty token (OI-WA-03).
  WARRANTY_TOKEN_ID: 0x0010,
  // READ/NOTIFY 4 B little-endian uint32: bits 23:16 major, 15:8 minor, 7:0 patch.
  FIRMWARE_VERSION_ID: 0x0011,
  // READ/NOTIFY, variable length, read once at link.
  SOCKET_MAP_ID: 0x0012,
  // NOTIFY 4 B, cervical VNS gel pad contact result, T2 only (OI-ACC-07). Not published by the hub yet.
  CVNS_PAD_STATUS_ID: 0x0013,
  // READ/NOTIFY 4+8n B, cervical VNS offline-fault summary and re-enable state (NP-SW-FAULTMSG-001).
  CVNS_FAULT_STATUS_ID: 0x0014,
  // WRITE 1 B 0x01, the wearer's re-enable confirmation after a cardiac cutoff.
  CVNS_REENABLE_CONFIRM_ID: 0x0015,
  // WRITE 4 B, little-endian opaque tag of the person using the device.
  ACTIVE_USER_ID: 0x0016,
  // READ 32 B, encrypted link only (NP-FW-HUB-001 §4.2, OI-AND-WIRE-02).
  DEVICE_SERIAL_ID: 0x0017,
} as const;

// The 128-bit UUID of each id above: 4E455550-0000-1000-8000-00805F9B34FB with its second group replaced.
export const GattUuidStrings = {
  // The NeurOne custom service.
  SERVICE_ID: "4e455550-0001-1000-8000-00805f9b34fb",
  // NOTIFY 4 B.
  SESSION_STATE_ID: "4e455550-0002-1000-8000-00805f9b34fb",
  // NOTIFY 4 B.
  SESSION_STATUS_ID: "4e455550-0003-1000-8000-00805f9b34fb",
  // NOTIFY 4 B.
  HRV_COHERENCE_ID: "4e455550-0004-1000-8000-00805f9b34fb",
  // NOTIFY 4 B.
  PACER_PHASE_ID: "4e455550-0005-1000-8000-00805f9b34fb",
  // NOTIFY 4 B.
  IMPEDANCE_RESULT_ID: "4e455550-0006-1000-8000-00805f9b34fb",
  // READ/NOTIFY 8 B, WRITE 1 B (OI-ACC-08).
  CONSUMABLE_STATUS_ID: "4e455550-0007-1000-8000-00805f9b34fb",
  // WRITE, signed protocol blob.
  PROTOCOL_UPLOAD_ID: "4e455550-0008-1000-8000-00805f9b34fb",
  // WRITE, triggers an EDF+ download.
  EDF_REQUEST_ID: "4e455550-0009-1000-8000-00805f9b34fb",
  // WRITE/NOTIFY.
  OTA_COMMAND_ID: "4e455550-000a-1000-8000-00805f9b34fb",
  // NOTIFY.
  OTA_STATUS_ID: "4e455550-000b-1000-8000-00805f9b34fb",
  // WRITE.
  CALIBRATION_CMD_ID: "4e455550-000c-1000-8000-00805f9b34fb",
  // READ/NOTIFY, variable length socket-keyed module-status frames.
  ZONE_MODULE_STATUS_ID: "4e455550-000d-1000-8000-00805f9b34fb",
  // NOTIFY.
  SHDR_UPLOAD_STATUS_ID: "4e455550-000e-1000-8000-00805f9b34fb",
  // WRITE 1 B (0x01 = stop). Placeholder pending hub BLE firmware (OI-WA-03).
  SESSION_STOP_ID: "4e455550-000f-1000-8000-00805f9b34fb",
  // READ 32 B, hub-provisioned TRNG warranty token (OI-WA-03).
  WARRANTY_TOKEN_ID: "4e455550-0010-1000-8000-00805f9b34fb",
  // READ/NOTIFY 4 B little-endian uint32: bits 23:16 major, 15:8 minor, 7:0 patch.
  FIRMWARE_VERSION_ID: "4e455550-0011-1000-8000-00805f9b34fb",
  // READ/NOTIFY, variable length, read once at link.
  SOCKET_MAP_ID: "4e455550-0012-1000-8000-00805f9b34fb",
  // NOTIFY 4 B, cervical VNS gel pad contact result, T2 only (OI-ACC-07). Not published by the hub yet.
  CVNS_PAD_STATUS_ID: "4e455550-0013-1000-8000-00805f9b34fb",
  // READ/NOTIFY 4+8n B, cervical VNS offline-fault summary and re-enable state (NP-SW-FAULTMSG-001).
  CVNS_FAULT_STATUS_ID: "4e455550-0014-1000-8000-00805f9b34fb",
  // WRITE 1 B 0x01, the wearer's re-enable confirmation after a cardiac cutoff.
  CVNS_REENABLE_CONFIRM_ID: "4e455550-0015-1000-8000-00805f9b34fb",
  // WRITE 4 B, little-endian opaque tag of the person using the device.
  ACTIVE_USER_ID: "4e455550-0016-1000-8000-00805f9b34fb",
  // READ 32 B, encrypted link only (NP-FW-HUB-001 §4.2, OI-AND-WIRE-02).
  DEVICE_SERIAL_ID: "4e455550-0017-1000-8000-00805f9b34fb",
} as const;

// Fixed value lengths of the NeurOne BLE service, in bytes.
export const GattSizes = {
  // The hub's replay-guard serial (DEVICE_SERIAL characteristic, NP-FW-HUB-001 §4.2): exactly this many bytes,
  // never padded or truncated.
  DEVICE_SERIAL_LEN: 32,
} as const;
