package life.neurone.core.models

// GENERATED by scripts/sync-clinician-tiers.ts from app/NeurOneShared/Resources/clinician-tiers.json.
// DO NOT EDIT: change the JSON and re-run it.

/**
 * Clinician use-case tiers (CLAUDE.md §6.1). The same table, from the same source, is iOS's `ClinicianUseCaseTier`.
 * [displayName] is iOS's persisted raw value.
 */
enum class ClinicianUseCaseTier(val displayName: String, val monthlyPrice: String) {
    MONITOR("Monitor", "$49/month/patient"),
    ASSESS("Assess", "$149/month/patient"),
    FULL_CLINICAL("Full Clinical", "$299/month/patient"),
    RESEARCH("Research", "$599/month/study");

    /**
     * Ordering for "does this tier reach that one". Not [ordinal], which silently re-ranks if a
     * case is reordered or inserted, and not `uhdrElements.size`, which puts [RESEARCH] — empty
     * by design — below [MONITOR].
     */
    val rank: Int
        get() = when (this) {
            MONITOR -> 0
            ASSESS -> 1
            FULL_CLINICAL -> 2
            RESEARCH -> 3
        }

    /** Minimum necessary UHDR elements for this tier. Derived from [UHDRElement.minimumTier]; [RESEARCH] is IRB-defined. */
    val uhdrElements: Set<UHDRElement>
        get() = when (this) {
            MONITOR -> setOf(
                UHDRElement.SESSION_TIMESTAMPS, UHDRElement.SESSION_DURATION,
                UHDRElement.PROTOCOL_PARAMETERS,
            )
            ASSESS -> setOf(
                UHDRElement.EEG_WAVEFORMS, UHDRElement.NEUROFEEDBACK_SCORES,
                UHDRElement.SESSION_TIMESTAMPS, UHDRElement.SESSION_DURATION,
                UHDRElement.PROTOCOL_PARAMETERS, UHDRElement.PBM_DOSE_LOGS,
            )
            FULL_CLINICAL -> setOf(
                UHDRElement.EEG_WAVEFORMS, UHDRElement.HRV_TIME_SERIES,
                UHDRElement.PPG_OPTICAL_SIGNAL, UHDRElement.NEUROFEEDBACK_SCORES,
                UHDRElement.SESSION_TIMESTAMPS, UHDRElement.SESSION_DURATION,
                UHDRElement.PROTOCOL_PARAMETERS, UHDRElement.CLOSED_LOOP_EVENTS,
                UHDRElement.PBM_DOSE_LOGS, UHDRElement.OUTCOME_LOGS,
            )
            RESEARCH -> emptySet()
        }
}
