/* GENERATED by scripts/sync-constants.ts from common/npps/constants.json. DO NOT EDIT: change the JSON and re-run it. */
#ifndef NP_APP_WIRE_CONSTANTS_H
#define NP_APP_WIRE_CONSTANTS_H

/*
 * 4E455550-0000-1000-8000-00805F9B34FB, least-significant byte first. The id of a characteristic
 * replaces the two bytes at NP_GATT_UUID_ID_OFFSET.
 */
#define NP_GATT_UUID_BASE_INIT { 0xFBu, 0x34u, 0x9Bu, 0x5Fu, 0x80u, 0x00u, 0x00u, 0x80u, 0x00u, 0x10u, 0x00u, 0x00u, 0x50u, 0x55u, 0x45u, 0x4Eu }
#define NP_GATT_UUID_ID_OFFSET 10

/*
 * The NeurOne custom service.
 */
#define NP_GATT_SERVICE_ID 0x0001u
/*
 * READ/NOTIFY 8 B, WRITE 1 B (OI-ACC-08).
 */
#define NP_GATT_CONSUMABLE_STATUS_ID 0x0007u
/*
 * READ 32 B, hub-provisioned TRNG warranty token (OI-WA-03).
 */
#define NP_GATT_WARRANTY_TOKEN_ID 0x0010u
/*
 * READ/NOTIFY 4+8n B, cervical VNS offline-fault summary and re-enable state (NP-SW-FAULTMSG-001).
 */
#define NP_GATT_CVNS_FAULT_STATUS_ID 0x0014u
/*
 * WRITE 1 B 0x01, the wearer's re-enable confirmation after a cardiac cutoff.
 */
#define NP_GATT_CVNS_REENABLE_CONFIRM_ID 0x0015u
/*
 * WRITE 4 B, little-endian opaque tag of the person using the device.
 */
#define NP_GATT_ACTIVE_USER_ID 0x0016u
/*
 * READ 32 B, encrypted link only (NP-FW-HUB-001 §4.2, OI-AND-WIRE-02).
 */
#define NP_GATT_DEVICE_SERIAL_ID 0x0017u

/*
 * The hub's replay-guard serial (DEVICE_SERIAL characteristic, NP-FW-HUB-001 §4.2): exactly this many
 * bytes, never padded or truncated.
 */
#define NP_GATT_DEVICE_SERIAL_LEN 32U
/*
 * Byte 0 of the frame.
 */
#define NP_CVFS_WIRE_VERSION 1U
/*
 * Header bytes before the first record.
 */
#define NP_CVFS_HEADER_LEN 4U
/*
 * Bytes in one fault record.
 */
#define NP_CVFS_RECORD_LEN 8U
/*
 * Most records one frame carries.
 */
#define NP_CVFS_MAX_WIRE_RECORDS 4U

#endif /* NP_APP_WIRE_CONSTANTS_H */
