package life.neurone.core.consent

import life.neurone.core.models.ClinicianUseCaseTier
import life.neurone.core.models.UHDRElement

// GENERATED by scripts/sync-use-cases.ts from app/NeurOneShared/Resources/clinician-use-cases.json.
// DO NOT EDIT: change the JSON and re-run it.

/**
 * All available clinical use cases (CLAUDE.md §6.1). The same table, from the same source, is iOS's `USE_CASE_LIBRARY`: a
 * grant records the IDs it was made from and the platforms read each other's grants.
 */
val USE_CASE_LIBRARY: List<ClinicalUseCase> = listOf(
    ClinicalUseCase(
        id = "adherence_monitoring",
        titleKey = "CLINICIAN_USECASE_ADHERENCE_MONITORING_NAME",
        descriptionKey = "CLINICIAN_USECASE_ADHERENCE_MONITORING_DESC",
        requiredElements = setOf(
            UHDRElement.SESSION_TIMESTAMPS, UHDRElement.SESSION_DURATION,
            UHDRElement.PROTOCOL_PARAMETERS,
        ),
        tier = ClinicianUseCaseTier.MONITOR,
    ),
    ClinicalUseCase(
        id = "eeg_review",
        titleKey = "CLINICIAN_USECASE_EEG_REVIEW_NAME",
        descriptionKey = "CLINICIAN_USECASE_EEG_REVIEW_DESC",
        requiredElements = setOf(
            UHDRElement.EEG_WAVEFORMS, UHDRElement.NEUROFEEDBACK_SCORES, UHDRElement.PBM_DOSE_LOGS,
            UHDRElement.SESSION_TIMESTAMPS, UHDRElement.SESSION_DURATION,
            UHDRElement.PROTOCOL_PARAMETERS,
        ),
        tier = ClinicianUseCaseTier.ASSESS,
    ),
    ClinicalUseCase(
        id = "hrv_outcomes",
        titleKey = "CLINICIAN_USECASE_HRV_OUTCOMES_NAME",
        descriptionKey = "CLINICIAN_USECASE_HRV_OUTCOMES_DESC",
        requiredElements = setOf(
            UHDRElement.EEG_WAVEFORMS, UHDRElement.NEUROFEEDBACK_SCORES, UHDRElement.PBM_DOSE_LOGS,
            UHDRElement.HRV_TIME_SERIES, UHDRElement.PPG_OPTICAL_SIGNAL,
            UHDRElement.CLOSED_LOOP_EVENTS, UHDRElement.OUTCOME_LOGS,
            UHDRElement.SESSION_TIMESTAMPS, UHDRElement.SESSION_DURATION,
            UHDRElement.PROTOCOL_PARAMETERS,
        ),
        tier = ClinicianUseCaseTier.FULL_CLINICAL,
    ),
)
