"""
Mark NP-DRV-SHELL-001 (docs/superseded/np_drv_shell_001.docx) as
SUPERSEDED and update its docs/status/document-register.md entry to match.

This document (Rev A generated by editscripts/generate_fpc_routing_review.py,
later extended to Rev 2 by editscripts/patch_risk17.py's §2.3 addition) is
entirely built on the retired position-unique 5-zone-slot FPC routing
architecture: fixed slot-to-zone assignments, per-zone measured arc lengths,
and a 5-tail adjacent-crosstalk analysis. None of that describes the current
hex-tile/socket architecture (NP-HEX-ZM-001), and the replacement per-socket
interconnect design for ~80 sockets has not been done yet (see
MECH-1/MECH-2/SMART-1 in docs/np_hex_zm_001.md §7 — flagged as real,
unscoped EE work, not something to invent here).

Unlike the FPC spec (which the document register already flagged superseded),
this document's document-register.md entry was NOT updated in PR #223 — it
still reads as a current, valid document. This script closes that gap:
1. Inserts an in-document SUPERSEDED banner (same convention as the spec doc
   and the markdown siblings from commit b96f2d4).
2. Updates the document-register.md row to carry the same supersession tag.

The generic bend-radius engineering (IPC-2223D basis, dynamic/static radius
values, channel-geometry principles in §3-4) is preserved as likely-reusable
methodology — not deleted — same as the spec doc treatment.
"""

import re

from docx import Document
from docx.shared import Pt, RGBColor
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

SHELL_PATH = "docs/superseded/np_drv_shell_001.docx"
REGISTER_PATH = "docs/status/document-register.md"

BANNER_MARKER = "SUPERSEDED (2026-07-28)"


def set_cell_bg(cell, hex_color):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def already_patched(doc):
    return any(BANNER_MARKER in p.text for p in doc.paragraphs)


def patch_docx():
    doc = Document(SHELL_PATH)
    if already_patched(doc):
        print(f"  Already patched — skipping: {SHELL_PATH}")
        return

    anchor = None
    for p in doc.paragraphs:
        if p.text.strip() == "1.  PURPOSE AND SCOPE":
            anchor = p
            break
    if anchor is None:
        raise RuntimeError("Could not find '1.  PURPOSE AND SCOPE' anchor paragraph")

    t = doc.add_table(rows=1, cols=1)
    t.style = "Table Grid"
    cell = t.rows[0].cells[0]
    set_cell_bg(cell, "FCE4D6")
    para = cell.paragraphs[0]

    def run(text, bold=False, size=10, color=(0xC0, 0x00, 0x00)):
        r = para.add_run(text)
        r.bold = bold
        r.font.size = Pt(size)
        r.font.color.rgb = RGBColor(*color)
        return r

    run("⚠ SUPERSEDED (2026-07-28) — retired 5-zone-slot routing architecture, do not use for new tooling work.  ", bold=True)
    para.add_run().add_break()
    run(
        "This document (§2.1) assigns FPC routing paths to 5 fixed, position-unique zone-module "
        "slots (Zone 1 frontal-left .. Zone 5 parietal) with measured-arc-length targets per zone. "
        "NP-HEX-ZM-001 (2026-07-15) replaced that architecture with a universal 40mm hex-tile SKU "
        "tiling ~80 sockets — there are no fixed \"Zone 1..5\" slots left to route to. See "
        "docs/np_hex_zm_001.md §3-4.",
        color=(0x40, 0x40, 0x40),
    )
    para.add_run().add_break()
    run(
        "Retired outright: §2.1's 5-slot table, §5's per-zone DRC checklist (DRC-01..06, 08, 10-11), "
        "§6's per-zone FPC length/arc table, §7's per-zone open items, and §2.3's 5-tail adjacent-FPC "
        "crosstalk analysis (added by the RISK-17 patch) — all sized for 5 large discrete FPC tails, "
        "not ~80 small ones.",
        color=(0x40, 0x40, 0x40),
    )
    para.add_run().add_break()
    run(
        "Likely still-reusable methodology, not yet re-applied to the hex-tile lattice: the generic "
        "bend-radius physics (§3 — IPC-2223D basis, ≥25mm dynamic / ≥12.5mm static, no-bend-near-"
        "connector rule) and the channel-geometry principles (§4 — radiused corners, enforcer "
        "bosses, alignment tolerance) are architecture-independent and should inform whatever "
        "per-socket interconnect design replaces this document.",
        color=(0x40, 0x40, 0x40),
    )
    para.add_run().add_break()
    run(
        "Open gap this note does not fill: no document yet specifies FPC/cable routing, bend radius, "
        "or channel geometry for the ~80-socket hex-tile lattice — see MECH-1/MECH-2/SMART-1 "
        "residuals in docs/np_hex_zm_001.md §7 (\"Hub PCB I2C fan-out architecture for ~30-80 "
        "sockets not yet designed... flagged for EE Lead scoping, not sized here\").",
        color=(0x40, 0x40, 0x40),
    )

    anchor._p.addprevious(t._tbl)
    spacer = OxmlElement("w:p")
    anchor._p.addprevious(spacer)

    doc.save(SHELL_PATH)
    print(f"  Supersession banner inserted: {SHELL_PATH}")


def patch_register():
    with open(REGISTER_PATH, "r") as f:
        content = f.read()

    OLD_MARKER = "| Shell FPC Routing Review | `docs/superseded/np_drv_shell_001.docx` |"
    if OLD_MARKER not in content:
        print(f"  WARNING: shell routing review row not found in {REGISTER_PATH}")
        return
    if "⚠ SUPERSEDED" in content.split(OLD_MARKER, 1)[1].split("\n", 1)[0]:
        print(f"  Already patched — skipping: {REGISTER_PATH}")
        return

    pattern = re.compile(
        r"(\| Shell FPC Routing Review \| `docs/neurone_shell_fpc_routing_review\.docx` \| "
        r"NP-DRV-SHELL-001 Rev 2 \(2026-05-10\) — bend radius, multi-FPC bundle mgmt \(§2\.3\), "
        r"EEG cable routing \(§2\.4\), 23-item DRC checklist; §2\.4\.5 locked routing path "
        r"\(OI-09 CLOSED, DRC-22 CLOSED, DRC-23 CLOSED\))( \|)"
    )
    new_content, n = pattern.subn(
        r"\1 **⚠ SUPERSEDED 2026-07-28 — retired 5-zone-slot FPC routing architecture; "
        r"replacement per-socket interconnect for the ~80-socket hex-tile lattice not yet "
        r"designed, see `docs/np_hex_zm_001.md` §7 MECH-1/MECH-2/SMART-1.**\2",
        content,
    )
    if n == 0:
        print(f"  WARNING: register row text did not match expected pattern exactly — no changes made")
        return

    with open(REGISTER_PATH, "w") as f:
        f.write(new_content)
    print(f"  document-register.md row updated")


if __name__ == "__main__":
    patch_docx()
    patch_register()
