package life.neurone.core.protocol

// GENERATED by scripts/sync-constants.ts from common/npps/constants.json. DO NOT EDIT: change the JSON and re-run it.

// Every hardware ceiling and fixed device figure the apps and the shared validator use. The firmware enforces them
// independently; no dosage limit or clinician override can exceed them.
object NPHardwareLimits {
    // PBM Transcranial / Intranasal (shared firmware limit)
    const val PBM_DUTY_CYCLE_MAX_PERCENT: Int = 25
    // pending RISK-03 regulatory opinion
    const val PBM_PULSED_PEAK_MW_CM2: Double = 400.0
    const val PBM_CW_MAX_MW_CM2: Double = 200.0
    // Deep 1170 nm PBM ceiling (CLAUDE.md §3: ≤1,000 mW/cm², TEC-stabilised).
    const val PBM_DEEP_MAX_MW_CM2: Double = 1000.0
    // Aggregate PBM irradiance ceiling (OI-PBM-05, three-channel combined). Pending RISK-03 regulatory
    // opinion scope expansion (Q4–Q6).
    const val PBM_AGGREGATE_MAX_MW_CM2: Double = 600.0
    // BES / tACS (consumer: Brainwave Entrainment Stimulation)
    const val BES_TACS_MAX_MILLIAMPS: Double = 1.0
    const val BES_TACS_MIN_HZ: Double = 0.5
    const val BES_TACS_MAX_HZ: Double = 40.0
    // tDCS (consumer: Cortical Priming Stimulation)
    const val TDCS_MIN_MILLIAMPS: Double = 0.1
    const val TDCS_MAX_MILLIAMPS: Double = 2.0
    // OI-CHARGE-04 (closed 2026-09-09): this IS checked here now. There is no web electrode-area constant
    // to add, because there is no longer a global electrode area on any client — the area is authored per
    // protocol (TDCSParams.electrodeAreaCm2), travels in the signed session descriptor, and the safety MCU
    // derives its charge limit from that same declared number. What used to be a 35-vs-25 disagreement
    // between the app's assumption and the enforcer's is now one transmitted value. OI-CHARGE-05 (a)(d)
    // 2026-09-15: RENAMED AND RE-SOURCED. This used to be `tdcsMaxChargeDensityUCcm2: 40.0`, a misnomer
    // that concealed a 1000× divergence — `I(mA) × t(s) / A(cm²)` is mC/cm², so the clients enforced 40
    // mC/cm² while the safety MCU enforced 40 µC/cm². The name now states the unit AND the period, because
    // both were ambiguous and each hid a different defect: the unit hid the 1000×, and the missing period
    // hid that a per-phase pulsed figure was being applied to a DC session dose. 150 mC/cm² per session
    // per electrode, derived rather than asserted (the old 40 had no source anywhere in the tree — the
    // citation chain was circular). Bounds the conventional large-pad human tDCS envelope: the
    // most-exposed large RCT protocol in docs/tdcs_database_full.csv is Brunoni ELECT-TDCS 2013/2017 at 2
    // mA × 30 min on 25 cm² = 144 mC/cm². Margin check: 35× below Liebetanz 2009's measured rat epicranial
    // DC lesion threshold of 5,240 mC/cm². Full derivation: NP-DT-001 DI-SAFE-01.
    const val TDCS_MAX_SESSION_CHARGE_DENSITY_MC_CM2: Double = 150.0
    // Per-PHASE ceiling for the charge-balanced biphasic modalities — BES/tACS, VNS, cervical VNS,
    // clinical tACS (OI-CHARGE-05 (b)). 40 µC/cm² is a real and correct figure in this form (Shannon 1992
    // / McCreery 1990 pulsed charge-injection limits); it is the number the tree has always carried, now
    // applied to the waveform class it is actually about. Net charge on these modalities is ~zero by
    // construction, so a session-cumulative dose is not a physical quantity for them and is not checked.
    const val PULSED_MAX_PHASE_CHARGE_DENSITY_UC_CM2: Double = 40.0
    // Electrode areas for the modalities whose electrodes are FIXED PARTS OF THE PRODUCT rather than a
    // user-chosen consumable. The tDCS pad is authored per protocol precisely because the user picks it
    // (OI-CHARGE-04); the BES pads, auricular clip and cervical collar are not swappable, so their area is
    // a device property both the app and firmware may hold. ⚠ PROVISIONAL — NOT MEASURED (OI-CHARGE-07).
    // Mirrors firmware/hub_control/include/np_hub_config.h. A SMALLER area is a SMALLER charge budget, so
    // these may be revised down freely and may only be revised up against a measurement.
    const val BES_ELECTRODE_AREA_CM2: Double = 25.0
    const val VNS_ELECTRODE_AREA_CM2: Double = 0.5
    const val CERVICAL_VNS_ELECTRODE_AREA_CM2: Double = 2.0
    // Pulse width (seconds) the firmware substitutes when a descriptor declares none: np_mod_cvns.c and
    // np_session_runner.c both default to 250 µs. The pre-flight must use the same number or it validates
    // a different waveform than the one that runs.
    const val VNS_DEFAULT_PULSE_WIDTH_SECONDS: Double = 0.00025
    // Largest declarable per-electrode area: the wire field (np_mod_tdcs_params_t.electrode_area_mcm2) is
    // a uint16 of milli-cm², so 65535 mcm². Not a clinical limit — an encoding ceiling, well above any
    // real pad (a large sponge is 35 cm²).
    const val TDCS_MAX_ELECTRODE_AREA_CM2: Double = 65.535
    // What a NEW tDCS block is seeded with in an editor (a large sponge pad). It is not a limit: the area
    // is authored per protocol, travels in the signed descriptor, and the safety MCU derives its charge
    // limit from that declared number (OI-CHARGE-04).
    const val TDCS_DEFAULT_ELECTRODE_AREA_CM2: Double = 35.0
    // hardware-enforced minimum ramp
    const val TDCS_RAMP_SECONDS: Int = 30
    const val TDCS_MAX_ELECTRODE_PAIRS: Int = 3
    // VNS (auricular)
    const val VNS_MAX_MILLIAMPS: Double = 2.0
    const val VNS_MIN_HZ: Double = 1.0
    const val VNS_MAX_HZ: Double = 25.0
    // Visual stimulation
    const val VISUAL_MAX_HZ: Double = 100.0
    // photoparoxysmal risk zone — clinician unlock required
    const val VISUAL_HIGH_RISK_MIN_HZ: Double = 3.0
    // firmware halts goggles, <200ms, if EEG shows photoparoxysmal response
    const val VISUAL_HIGH_RISK_MAX_HZ: Double = 30.0
    // Clinical tACS (T2 only)
    const val CLINICAL_TACS_MAX_MILLIAMPS: Double = 4.0
    // One driver channel per T2 cap electrode (NP-FW-HD-001 §6.4, NP_HD_DRIVER_CHANNELS). OI-TACS-01: the
    // hub wire mask carried only 16 bits until 2026-09-07, so every encoder clamped here;
    // np_mod_clin_tacs_params_t now has a third mask byte and 21 is deliverable, not just authorable.
    const val CLINICAL_TACS_MAX_CHANNELS: Int = 21
    // HD-tDCS (T2 only, sLORETA-guided 4×1 ring montage)
    const val HD_TDCS_MAX_MILLIAMPS_PER_ELECTRODE: Double = 2.0
    // Bikson lab 3.5mm electrode safety limit
    const val HD_TDCS_MAX_CURRENT_DENSITY_A_M2: Double = 6.0
    // Per-phase ceiling on the HD electrode (µC/cm²); Class B np_hd_stim.c aborts at 95% of it. Same
    // quantity as pulsedMaxPhaseChargeDensityUCcm2, kept separate because the T2 software abort is a
    // distinct control from the Class C interlock.
    const val HD_TDCS_MAX_CHARGE_DENSITY_UC_CM2: Double = 40.0
    // HD-tDCS 3.5mm Ag/AgCl sintered electrode: π × (0.175 cm)². Mirrors NP_HD_ELECTRODE_AREA_CM2.
    // Measured geometry, unlike the three above.
    const val HD_TDCS_ELECTRODE_AREA_CM2: Double = 0.0962
    // Cervical VNS (T2 accessory, cardiac interlock always active)
    const val CERVICAL_VNS_MAX_MILLIAMPS: Double = 2.0
    // 40Hz Vibrotactile (provisional accessory)
    const val VIBROTACTILE_FREQUENCY_HZ: Double = 40.0
    const val VIBROTACTILE_FREQ_TOLERANCE_HZ: Double = 0.5
    const val VIBROTACTILE_MAX_G: Double = 1.2
    const val VIBROTACTILE_MIN_G: Double = 0.6
}

// The 16-bit id of each characteristic of the NeurOne BLE service. The 128-bit UUID is the base with its second group
// replaced by the id (4E455550-XXXX-1000-8000-00805F9B34FB), so the base is written once, here, and every runtime builds
// its UUIDs from it. `hub: true` marks a characteristic the hub firmware publishes; only those reach the firmware
// header, because a firmware reference is what the consumable-trigger gate reads as 'the hub produces it'.
object GattIds {
    // The NeurOne custom service.
    const val SERVICE: Int = 0x0001
    // NOTIFY 4 B.
    const val SESSION_STATE: Int = 0x0002
    // NOTIFY 4 B.
    const val SESSION_STATUS: Int = 0x0003
    // NOTIFY 4 B.
    const val HRV_COHERENCE: Int = 0x0004
    // NOTIFY 4 B.
    const val PACER_PHASE: Int = 0x0005
    // NOTIFY 4 B.
    const val IMPEDANCE_RESULT: Int = 0x0006
    // READ/NOTIFY 8 B, WRITE 1 B (OI-ACC-08).
    const val CONSUMABLE_STATUS: Int = 0x0007
    // WRITE, signed protocol blob.
    const val PROTOCOL_UPLOAD: Int = 0x0008
    // WRITE, triggers an EDF+ download.
    const val EDF_REQUEST: Int = 0x0009
    // WRITE/NOTIFY.
    const val OTA_COMMAND: Int = 0x000A
    // NOTIFY.
    const val OTA_STATUS: Int = 0x000B
    // WRITE.
    const val CALIBRATION_CMD: Int = 0x000C
    // READ/NOTIFY, variable length socket-keyed module-status frames.
    const val ZONE_MODULE_STATUS: Int = 0x000D
    // NOTIFY.
    const val SHDR_UPLOAD_STATUS: Int = 0x000E
    // WRITE 1 B (0x01 = stop). Placeholder pending hub BLE firmware (OI-WA-03).
    const val SESSION_STOP: Int = 0x000F
    // READ 32 B, hub-provisioned TRNG warranty token (OI-WA-03).
    const val WARRANTY_TOKEN: Int = 0x0010
    // READ/NOTIFY 4 B little-endian uint32: bits 23:16 major, 15:8 minor, 7:0 patch.
    const val FIRMWARE_VERSION: Int = 0x0011
    // READ/NOTIFY, variable length, read once at link.
    const val SOCKET_MAP: Int = 0x0012
    // NOTIFY 4 B, cervical VNS gel pad contact result, T2 only (OI-ACC-07). Not published by the hub yet.
    const val CVNS_PAD_STATUS: Int = 0x0013
    // READ/NOTIFY 4+8n B, cervical VNS offline-fault summary and re-enable state (NP-SW-FAULTMSG-001).
    const val CVNS_FAULT_STATUS: Int = 0x0014
    // WRITE 1 B 0x01, the wearer's re-enable confirmation after a cardiac cutoff.
    const val CVNS_REENABLE_CONFIRM: Int = 0x0015
    // WRITE 4 B, little-endian opaque tag of the person using the device.
    const val ACTIVE_USER: Int = 0x0016
    // READ 32 B, encrypted link only (NP-FW-HUB-001 §4.2, OI-AND-WIRE-02).
    const val DEVICE_SERIAL: Int = 0x0017
}

// The 128-bit UUID of each id above: 4E455550-0000-1000-8000-00805F9B34FB with its second group replaced.
object GattUuidStrings {
    // The NeurOne custom service.
    const val SERVICE: String = "4E455550-0001-1000-8000-00805F9B34FB"
    // NOTIFY 4 B.
    const val SESSION_STATE: String = "4E455550-0002-1000-8000-00805F9B34FB"
    // NOTIFY 4 B.
    const val SESSION_STATUS: String = "4E455550-0003-1000-8000-00805F9B34FB"
    // NOTIFY 4 B.
    const val HRV_COHERENCE: String = "4E455550-0004-1000-8000-00805F9B34FB"
    // NOTIFY 4 B.
    const val PACER_PHASE: String = "4E455550-0005-1000-8000-00805F9B34FB"
    // NOTIFY 4 B.
    const val IMPEDANCE_RESULT: String = "4E455550-0006-1000-8000-00805F9B34FB"
    // READ/NOTIFY 8 B, WRITE 1 B (OI-ACC-08).
    const val CONSUMABLE_STATUS: String = "4E455550-0007-1000-8000-00805F9B34FB"
    // WRITE, signed protocol blob.
    const val PROTOCOL_UPLOAD: String = "4E455550-0008-1000-8000-00805F9B34FB"
    // WRITE, triggers an EDF+ download.
    const val EDF_REQUEST: String = "4E455550-0009-1000-8000-00805F9B34FB"
    // WRITE/NOTIFY.
    const val OTA_COMMAND: String = "4E455550-000A-1000-8000-00805F9B34FB"
    // NOTIFY.
    const val OTA_STATUS: String = "4E455550-000B-1000-8000-00805F9B34FB"
    // WRITE.
    const val CALIBRATION_CMD: String = "4E455550-000C-1000-8000-00805F9B34FB"
    // READ/NOTIFY, variable length socket-keyed module-status frames.
    const val ZONE_MODULE_STATUS: String = "4E455550-000D-1000-8000-00805F9B34FB"
    // NOTIFY.
    const val SHDR_UPLOAD_STATUS: String = "4E455550-000E-1000-8000-00805F9B34FB"
    // WRITE 1 B (0x01 = stop). Placeholder pending hub BLE firmware (OI-WA-03).
    const val SESSION_STOP: String = "4E455550-000F-1000-8000-00805F9B34FB"
    // READ 32 B, hub-provisioned TRNG warranty token (OI-WA-03).
    const val WARRANTY_TOKEN: String = "4E455550-0010-1000-8000-00805F9B34FB"
    // READ/NOTIFY 4 B little-endian uint32: bits 23:16 major, 15:8 minor, 7:0 patch.
    const val FIRMWARE_VERSION: String = "4E455550-0011-1000-8000-00805F9B34FB"
    // READ/NOTIFY, variable length, read once at link.
    const val SOCKET_MAP: String = "4E455550-0012-1000-8000-00805F9B34FB"
    // NOTIFY 4 B, cervical VNS gel pad contact result, T2 only (OI-ACC-07). Not published by the hub yet.
    const val CVNS_PAD_STATUS: String = "4E455550-0013-1000-8000-00805F9B34FB"
    // READ/NOTIFY 4+8n B, cervical VNS offline-fault summary and re-enable state (NP-SW-FAULTMSG-001).
    const val CVNS_FAULT_STATUS: String = "4E455550-0014-1000-8000-00805F9B34FB"
    // WRITE 1 B 0x01, the wearer's re-enable confirmation after a cardiac cutoff.
    const val CVNS_REENABLE_CONFIRM: String = "4E455550-0015-1000-8000-00805F9B34FB"
    // WRITE 4 B, little-endian opaque tag of the person using the device.
    const val ACTIVE_USER: String = "4E455550-0016-1000-8000-00805F9B34FB"
    // READ 32 B, encrypted link only (NP-FW-HUB-001 §4.2, OI-AND-WIRE-02).
    const val DEVICE_SERIAL: String = "4E455550-0017-1000-8000-00805F9B34FB"
}

// Fixed value lengths of the NeurOne BLE service, in bytes.
object GattSizes {
    // The hub's replay-guard serial (DEVICE_SERIAL characteristic, NP-FW-HUB-001 §4.2): exactly this many
    // bytes, never padded or truncated.
    const val DEVICE_SERIAL_LEN: Int = 32
}

// The anonymisation floors a study descriptor must meet before a user may be asked to consent to it (CLAUDE.md §5.3,
// §6.3). Locked; the device is the only place they can be enforced, because the anonymisation happens on the device.
object ConsentLimits {
    // A descriptor's k must be at least this.
    const val MINIMUM_K_ANONYMITY: Int = 10
    // A descriptor's date rounding must be at least this many days (one week).
    const val MINIMUM_DATE_ROUNDING_DAYS: Int = 7
}

// The CVNS_FAULT_STATUS frame (NP-SW-FAULTMSG-001): a 4-byte header then up to MAX_WIRE_RECORDS records of RECORD_LEN
// bytes. The hub writes it and the apps parse it.
object CvfsWire {
    // Byte 0 of the frame.
    const val WIRE_VERSION: Int = 1
    // Header bytes before the first record.
    const val HEADER_LEN: Int = 4
    // Bytes in one fault record.
    const val RECORD_LEN: Int = 8
    // Most records one frame carries.
    const val MAX_WIRE_RECORDS: Int = 4
}
