// Generated by scripts/sync-socket-map.ts — DO NOT EDIT BY HAND.
// Regenerate with: bun scripts/sync-socket-map.ts
// Geometry is validated on every run against protocols/predefined/00-zones.npps.
// Scan-grounded v1 lattice (NP-HEX-ZM-001 §3.4) — PROVISIONAL pending REG-1 / ACT-1.
// x/y are PROVISIONAL unit-hex lattice coordinates for layout only, not mm.

import Foundation

/// The socket lattice: a hardware fact, changing only on an inner-bowl re-tool.
///
/// Not a zone table. Which sockets a zone contains is authored in a `.npps`
/// file and answered by `NPZoneRegistry` — a zone is defined by a `zone` block
/// and nowhere else (NP-NPPS-REF-001 §8).
enum SocketLattice {

    /// Number of sockets on this lattice.
    static let NP_SOCKET_COUNT = 80

    /// Socket ids are 1-based — the numbering base every consumer honours.
    static let NP_SOCKET_NUMBERING_BASE = 1

    /// Inclusive lowest valid socket id.
    static let NP_SOCKET_ID_MIN = 1

    /// Inclusive highest valid socket id.
    static let NP_SOCKET_ID_MAX = 80

    /// Inclusive id range, for error messages and UI hints.
    static var rangeLabel: String { "\(NP_SOCKET_ID_MIN)\u{2013}\(NP_SOCKET_ID_MAX)" }

    static func isValid(_ socketID: Int) -> Bool {
        socketID >= NP_SOCKET_ID_MIN && socketID <= NP_SOCKET_ID_MAX
    }
}
