// Generated by scripts/sync-socket-map.ts — DO NOT EDIT BY HAND.
// Regenerate with: bun scripts/sync-socket-map.ts
// Geometry is validated on every run against protocols/predefined/00-zones.npps.
// Scan-grounded v1 lattice (NP-HEX-ZM-001 §3.4) — PROVISIONAL pending REG-1 / ACT-1.
// x/y are PROVISIONAL unit-hex lattice coordinates for layout only, not mm.

import Foundation

/// Which zones a socket belongs to, authored in protocols/predefined/00-zones.npps.
///
/// Zones replaced lobe and side: neither is a property of the hardware, and
/// nothing in the system derives one. A socket's anatomical meaning is the set of
/// zones a human put it in.
struct SocketZoneEntry {
    /// Smallest zone containing this socket — the most specific description
    /// available, and what the app speaks. nil if no zone lists it.
    let primary: String?
    /// Every zone containing it, smallest first. Sockets belong to several:
    /// a midline socket is in both the left and right zone of its region.
    let all: [String]
}

enum SocketZones {

    /// 1-based socket id -> zone membership.
    static let bySocket: [UInt8: SocketZoneEntry] = [
    1: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    2: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    3: SocketZoneEntry(
        primary: "Frontal Right (excl. midline)",
        all: [
            "Frontal Right (excl. midline)", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    4: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    5: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    6: SocketZoneEntry(
        primary: "Frontal Right (excl. midline)",
        all: [
            "Frontal Right (excl. midline)", "Frontal Left", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    7: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    8: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    9: SocketZoneEntry(
        primary: "Frontal Right (excl. midline)",
        all: [
            "Frontal Right (excl. midline)", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    10: SocketZoneEntry(
        primary: "Frontal Right (excl. midline)",
        all: [
            "Frontal Right (excl. midline)", "Frontal Left", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    11: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    12: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    13: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    14: SocketZoneEntry(
        primary: "Frontal Right (excl. midline)",
        all: [
            "Frontal Right (excl. midline)", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    15: SocketZoneEntry(
        primary: "Frontal Right (excl. midline)",
        all: [
            "Frontal Right (excl. midline)", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    16: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    17: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    18: SocketZoneEntry(
        primary: "Frontal Right (excl. midline)",
        all: [
            "Frontal Right (excl. midline)", "Frontal Left", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    19: SocketZoneEntry(
        primary: "Frontal Right (excl. midline)",
        all: [
            "Frontal Right (excl. midline)", "Frontal Left", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    20: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    21: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    22: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    23: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    24: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    25: SocketZoneEntry(primary: "Temporal Left", all: ["Temporal Left", "Vault (excl. Occipital)", "All"]),
    26: SocketZoneEntry(primary: "Motor / SMA", all: ["Motor / SMA", "Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    27: SocketZoneEntry(primary: "Motor / SMA", all: ["Motor / SMA", "Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    28: SocketZoneEntry(primary: "Motor / SMA", all: ["Motor / SMA", "Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    29: SocketZoneEntry(
        primary: "Motor / SMA",
        all: [
            "Motor / SMA", "Frontal Left", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All",
        ]),
    30: SocketZoneEntry(primary: "Motor / SMA", all: ["Motor / SMA", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    31: SocketZoneEntry(primary: "Motor / SMA", all: ["Motor / SMA", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    32: SocketZoneEntry(primary: "Motor / SMA", all: ["Motor / SMA", "Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    33: SocketZoneEntry(primary: "Temporal Right", all: ["Temporal Right", "Vault (excl. Occipital)", "All"]),
    34: SocketZoneEntry(primary: "Temporal Left", all: ["Temporal Left", "Vault (excl. Occipital)", "All"]),
    35: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    36: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    37: SocketZoneEntry(primary: "Frontal Left", all: ["Frontal Left", "Frontal", "Vault (excl. Occipital)", "All"]),
    38: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    39: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    40: SocketZoneEntry(primary: "Frontal Right", all: ["Frontal Right", "Frontal", "Vault (excl. Occipital)", "All"]),
    41: SocketZoneEntry(primary: "Temporal Right", all: ["Temporal Right", "Vault (excl. Occipital)", "All"]),
    42: SocketZoneEntry(primary: "Temporal Left", all: ["Temporal Left", "Vault (excl. Occipital)", "All"]),
    43: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    44: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    45: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    46: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    47: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    48: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    49: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    50: SocketZoneEntry(primary: "Temporal Right", all: ["Temporal Right", "Vault (excl. Occipital)", "All"]),
    51: SocketZoneEntry(primary: "Temporal Left", all: ["Temporal Left", "Vault (excl. Occipital)", "All"]),
    52: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    53: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    54: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    55: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    56: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    57: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    58: SocketZoneEntry(primary: "Temporal Right", all: ["Temporal Right", "Vault (excl. Occipital)", "All"]),
    59: SocketZoneEntry(primary: "Temporal Left", all: ["Temporal Left", "Vault (excl. Occipital)", "All"]),
    60: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    61: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    62: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    63: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    64: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    65: SocketZoneEntry(primary: "Temporal Right", all: ["Temporal Right", "Vault (excl. Occipital)", "All"]),
    66: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    67: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    68: SocketZoneEntry(primary: "Parietal Left", all: ["Parietal Left", "Posterior", "Vault (excl. Occipital)", "All"]),
    69: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    70: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    71: SocketZoneEntry(primary: "Parietal Right", all: ["Parietal Right", "Posterior", "Vault (excl. Occipital)", "All"]),
    72: SocketZoneEntry(primary: "Occipital Left", all: ["Occipital Left", "Posterior", "All"]),
    73: SocketZoneEntry(primary: "Occipital Left", all: ["Occipital Left", "Posterior", "All"]),
    74: SocketZoneEntry(primary: "Occipital Left", all: ["Occipital Left", "Occipital Right", "Posterior", "All"]),
    75: SocketZoneEntry(primary: "Occipital Right", all: ["Occipital Right", "Posterior", "All"]),
    76: SocketZoneEntry(primary: "Occipital Right", all: ["Occipital Right", "Posterior", "All"]),
    77: SocketZoneEntry(primary: "Occipital Left", all: ["Occipital Left", "Posterior", "All"]),
    78: SocketZoneEntry(primary: "Occipital Left", all: ["Occipital Left", "Posterior", "All"]),
    79: SocketZoneEntry(primary: "Occipital Right", all: ["Occipital Right", "Posterior", "All"]),
    80: SocketZoneEntry(primary: "Occipital Right", all: ["Occipital Right", "Posterior", "All"]),
    ]

    /// Most specific zone name for a socket, or nil when the table has no entry
    /// (a helmet reporting a socket this app build does not know about).
    static func primaryZone(for socketID: UInt8) -> String? {
        bySocket[socketID]?.primary
    }

    static func zones(for socketID: UInt8) -> [String] {
        bySocket[socketID]?.all ?? []
    }

    /// Socket ids this table covers. Not a hardware claim — the helmet's own
    /// socket map is authoritative for which sockets physically exist.
    static let socketCount = 80
}
