// GENERATED by scripts/sync-uhdr-elements.ts from app/NeurOneShared/Resources/uhdr-elements.json.
// DO NOT EDIT: change the JSON and re-run it.

// UHDR data elements (per NP-FW-EMMC-001 §12). The same table, from the same source, is Android's `UHDRElement`: the
// raw value here is its `wireName`, and a signed study descriptor names its requested elements by it.

enum UHDRElement: String, CaseIterable, Codable {
    case eegWaveforms = "EEG Waveforms"
    case hrvTimeSeries = "HRV Time Series"
    case ppgOpticalSignal = "PPG Optical Signal"
    case neurofeedbackScores = "Neurofeedback Performance Scores"
    case sessionTimestamps = "Session Timestamps"
    case sessionDuration = "Session Duration"
    case protocolParameters = "Protocol Parameters"
    case closedLoopEvents = "Closed-Loop Adaptation Events"
    case pbmDoseLogs = "PBM Dose (J/cm²) Per Zone"
    case outcomeLogs = "User-Entered Outcome Logs"
    case eyeStateLogs = "Eye Open/Closed State"

    /// Lowest clinician tier that may access this element (ISC-137).
    var minimumTier: ClinicianUseCaseTier {
        switch self {
        case .sessionTimestamps, .sessionDuration, .protocolParameters:
            return .monitor
        case .eegWaveforms, .neurofeedbackScores, .pbmDoseLogs:
            return .assess
        case .hrvTimeSeries, .ppgOpticalSignal, .closedLoopEvents, .outcomeLogs, .eyeStateLogs:
            return .fullClinical
        }
    }

    /// Display text. `rawValue` stays the persisted Codable value: it is written
    /// into stored consent records, so it cannot double as the thing on screen.
    var displayName: String {
        switch self {
        case .eegWaveforms: return String(localized: "CONSENT_ELEMENT_EEGWAVEFORMS")
        case .hrvTimeSeries: return String(localized: "CONSENT_ELEMENT_HRVTIMESERIES")
        case .ppgOpticalSignal: return String(localized: "CONSENT_ELEMENT_PPGOPTICALSIGNAL")
        case .neurofeedbackScores: return String(localized: "CONSENT_ELEMENT_NEUROFEEDBACKSCORES")
        case .sessionTimestamps: return String(localized: "CONSENT_ELEMENT_SESSIONTIMESTAMPS")
        case .sessionDuration: return String(localized: "CONSENT_ELEMENT_SESSIONDURATION")
        case .protocolParameters: return String(localized: "CONSENT_ELEMENT_PROTOCOLPARAMETERS")
        case .closedLoopEvents: return String(localized: "CONSENT_ELEMENT_CLOSEDLOOPEVENTS")
        case .pbmDoseLogs: return String(localized: "CONSENT_ELEMENT_PBMDOSELOGS")
        case .outcomeLogs: return String(localized: "CONSENT_ELEMENT_OUTCOMELOGS")
        case .eyeStateLogs: return String(localized: "CONSENT_ELEMENT_EYESTATELOGS")
        }
    }

    var plainLanguageDescription: String {
        switch self {
        case .eegWaveforms: return String(localized: "CONSENT_ELEMENT_DESC_EEGWAVEFORMS")
        case .hrvTimeSeries: return String(localized: "CONSENT_ELEMENT_DESC_HRVTIMESERIES")
        case .ppgOpticalSignal: return String(localized: "CONSENT_ELEMENT_DESC_PPGOPTICALSIGNAL")
        case .neurofeedbackScores: return String(localized: "CONSENT_ELEMENT_DESC_NEUROFEEDBACKSCORES")
        case .sessionTimestamps: return String(localized: "CONSENT_ELEMENT_DESC_SESSIONTIMESTAMPS")
        case .sessionDuration: return String(localized: "CONSENT_ELEMENT_DESC_SESSIONDURATION")
        case .protocolParameters: return String(localized: "CONSENT_ELEMENT_DESC_PROTOCOLPARAMETERS")
        case .closedLoopEvents: return String(localized: "CONSENT_ELEMENT_DESC_CLOSEDLOOPEVENTS")
        case .pbmDoseLogs: return String(localized: "CONSENT_ELEMENT_DESC_PBMDOSELOGS")
        case .outcomeLogs: return String(localized: "CONSENT_ELEMENT_DESC_OUTCOMELOGS")
        case .eyeStateLogs: return String(localized: "CONSENT_ELEMENT_DESC_EYESTATELOGS")
        }
    }
}
