package com.neurone.core.protocol

// Port of iOS NPBundledProtocols. The 19 predefined NPPS protocol templates,
// embedded verbatim from protocols/predefined/*.npps (the single source of truth).
// NPProtocolLibrary parses each string into an NPProtocolEntry at construction.
// Regenerated by hand from the .npps files; keep in sync when a template changes.
object NPBundledProtocols {

    val allContents: List<String> = listOf(
        """
protocol "Gamma Focus" {
    id: "10000001-0000-0000-0000-000000000000"
    description: "Simultaneous 40Hz entrainment across audio, visual, and PBM channels for cognitive enhancement and attention. Evidence-backed GENUS-inspired multi-sensory 40Hz protocol."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [focus, gamma, 40Hz, cognitive, multimodal]
    duration: 20m

    pbm_transcranial {
        intensity: 80%
        frequency: 40Hz
        duty_cycle: 25%
        zones: all
        wavelength: 660_808nm
    }

    audio_entrainment {
        binaural_hz: 40Hz
        noise: none
        carrier_hz: 440Hz
        volume: 70%
        eeg_adaptive: false
        bone_conduction_pacer: false
    }

    visual_stimulation {
        frequency: 40Hz
        mode: binocular
        emdr_cadence: 1Hz
        interval_on: 60s
        interval_off: 30s
        repeat: until_end
    }

    eeg_neurofeedback {
        band: gamma
        channels: all
        closed_loop: true
    }

}
""",
        """
protocol "Alpha Calm" {
    id: "10000002-0000-0000-0000-000000000000"
    description: "Promotes relaxed alertness via 10Hz alpha entrainment with PBM and HRV biofeedback. Ideal for stress reduction and pre-sleep wind-down."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [calm, alpha, relaxation, stress, hrv]
    duration: 20m

    pbm_transcranial {
        intensity: 75%
        frequency: 10Hz
        duty_cycle: 25%
        zones: all
        wavelength: 660_808nm
    }

    eeg_neurofeedback {
        band: alpha
        channels: all
        closed_loop: true
    }

    vns_hrv {
        frequency: 25Hz
        intensity: 1.5mA
        hrv_protocol: standalone
        breathing_rate: 6.0
    }

    audio_entrainment {
        binaural_hz: 10Hz
        noise: pink
        carrier_hz: 440Hz
        volume: 60%
        eeg_adaptive: true
        bone_conduction_pacer: false
    }

}
""",
        """
protocol "Deep Sleep" {
    id: "10000003-0000-0000-0000-000000000000"
    description: "Slow-wave sleep induction using 2Hz delta PBM on rear zones with brown noise and resonance breathing. Use within 30 minutes of bedtime."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [sleep, delta, recovery, relaxation]
    duration: 45m

    pbm_transcranial {
        intensity: 60%
        frequency: 2Hz
        duty_cycle: 25%
        zones: rear
        wavelength: 660_808nm
    }

    eeg_neurofeedback {
        band: delta
        channels: all
        closed_loop: true
    }

    audio_entrainment {
        noise: brown
        carrier_hz: 440Hz
        volume: 40%
        eeg_adaptive: false
        bone_conduction_pacer: false
    }

    vns_hrv {
        frequency: 6Hz
        intensity: 1.0mA
        hrv_protocol: standalone
        breathing_rate: 5.0
    }

}
""",
        """
protocol "Memory Boost" {
    id: "10000004-0000-0000-0000-000000000000"
    description: "Theta (6Hz) hippocampal entrainment for memory consolidation and learning. Combines PBM, theta-band EEG neurofeedback, binaural audio, and HRV biofeedback."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [memory, theta, learning, consolidation]
    duration: 30m

    pbm_transcranial {
        intensity: 70%
        frequency: 6Hz
        duty_cycle: 25%
        zones: all
        wavelength: 660_808nm
    }

    eeg_neurofeedback {
        band: theta
        channels: all
        closed_loop: true
    }

    audio_entrainment {
        binaural_hz: 6Hz
        noise: brown
        carrier_hz: 440Hz
        volume: 55%
        eeg_adaptive: true
        bone_conduction_pacer: false
    }

    vns_hrv {
        frequency: 25Hz
        intensity: 1.5mA
        hrv_protocol: standalone
        breathing_rate: 6.0
    }

}
""",
        """
protocol "Anxiety Relief" {
    id: "10000005-0000-0000-0000-000000000000"
    description: "Multi-modal anxiety reduction combining VNS, HRV coherence training, alpha PBM, and resonance breathing. Based on 24-RCT meta-analysis (d=0.83 anxiety reduction)."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [anxiety, stress, hrv, vns, alpha, calm]
    duration: 20m

    vns_hrv {
        frequency: 25Hz
        intensity: 0.5mA
        hrv_protocol: eeg_biofeedback
        breathing_rate: 6.0
    }

    pbm_transcranial {
        intensity: 65%
        frequency: 10Hz
        duty_cycle: 25%
        zones: front
        wavelength: 660_808nm
    }

    audio_entrainment {
        binaural_hz: 10Hz
        noise: pink
        carrier_hz: 440Hz
        volume: 60%
        eeg_adaptive: true
        bone_conduction_pacer: true
    }

    eeg_neurofeedback {
        band: alpha
        channels: all
        closed_loop: true
    }

}
""",
        """
protocol "Flow State" {
    id: "10000006-0000-0000-0000-000000000000"
    description: "Gamma-theta coupled protocol targeting the flow state signature: frontal gamma + parieto-occipital theta. Split-zone PBM with closed-loop EEG adaptation."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [flow, gamma, theta, performance, creative, multimodal]
    duration: 25m

    pbm_transcranial {
        intensity: 80%
        frequency: 40Hz
        duty_cycle: 25%
        zones: [1, 2]
        wavelength: 660_808nm
    }

    pbm_transcranial {
        intensity: 75%
        frequency: 6Hz
        duty_cycle: 25%
        zones: [3, 4, 5]
        wavelength: 660_808nm
    }

    eeg_neurofeedback {
        band: gamma_theta
        channels: all
        closed_loop: true
    }

    audio_entrainment {
        binaural_hz: 40Hz
        isochronic_hz: 6Hz
        noise: none
        carrier_hz: 440Hz
        volume: 65%
        eeg_adaptive: true
        bone_conduction_pacer: false
    }

}
""",
        """
protocol "Vascular Baseline" {
    id: "10000007-0000-0000-0000-000000000000"
    description: "Continuous-wave PBM for cerebrovascular support. Low-frequency VNS and alpha EEG. Use as a maintenance or recovery session."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [circulation, CW, baseline, maintenance, cerebrovascular]
    duration: 30m

    pbm_transcranial {
        intensity: 80%
        frequency: 0Hz  # CW
        zones: all
        wavelength: 660_808nm
    }

    vns_hrv {
        frequency: 1Hz
        intensity: 1.0mA
        hrv_protocol: standalone
        breathing_rate: 6.0
    }

    eeg_neurofeedback {
        band: alpha
        channels: all
        closed_loop: true
    }

}
""",
        """
protocol "ADHD Focus" {
    id: "10000008-0000-0000-0000-000000000000"
    description: "EEG neurofeedback theta/beta ratio training with tDCS cortical priming and 20Hz frontal PBM. Based on 21 RCTs (n=1,261) of EEG neurofeedback for ADHD."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [adhd, focus, theta, beta, neurofeedback, tdcs]
    duration: 40m

    eeg_neurofeedback {
        band: alpha_theta
        channels: front
        closed_loop: true
    }

    tdcs {
        intensity: 1.5mA
        electrode_pairs: [["F3", "Fp2"]]
        ramp: 30s  # hardware-enforced
        interval_on: 20m
        interval_off: 20m
        repeat: 1
    }

    pbm_transcranial {
        intensity: 70%
        frequency: 20Hz
        duty_cycle: 25%
        zones: front
        wavelength: 660_808nm
    }

    audio_entrainment {
        isochronic_hz: 20Hz
        noise: none
        carrier_hz: 440Hz
        volume: 55%
        eeg_adaptive: true
        bone_conduction_pacer: false
    }

}
""",
        """
protocol "Retinal Health" {
    id: "10000009-0000-0000-0000-000000000000"
    description: "Invisible 808-830nm near-infrared retinal PBM during normal-looking wear (Mode F). Supports mitochondrial function in retinal photoreceptors. 3-minute daily maintenance."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [retinal, pbm, nir, mode_f, ocular, maintenance]
    duration: 3m

    visual_stimulation {
        frequency: 0Hz  # CW
        mode: mode_f
        mode_f: true
    }

}
""",
        """
protocol "PTSD EMDR Support" {
    id: "1000000A-0000-0000-0000-000000000000"
    description: "EMDR bilateral visual stimulation with VNS vagal support and calming brown noise. Intended for use alongside therapeutic EMDR sessions. WHO-recommended protocol basis."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [ptsd, emdr, bilateral, trauma, vns, clinical]
    duration: 60m

    visual_stimulation {
        frequency: 1Hz
        mode: emdr
        emdr_cadence: 1Hz
    }

    vns_hrv {
        frequency: 25Hz
        intensity: 0.4mA
        hrv_protocol: standalone
        breathing_rate: 6.0
    }

    audio_entrainment {
        noise: brown
        carrier_hz: 440Hz
        volume: 45%
        eeg_adaptive: false
        bone_conduction_pacer: true
    }

    eeg_neurofeedback {
        band: alpha
        channels: all
        closed_loop: false
    }

}
""",
        """
protocol "HRV Coherence Training" {
    id: "1000000B-0000-0000-0000-000000000000"
    description: "Standalone HRV coherence training with resonance breathing pacer. Bone conduction delivers the breathing cue. Evidence: meta-analysis 24 RCTs (d=0.83 anxiety reduction)."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [HRV, coherence, stress, relaxation, breathing]
    duration: 20m

    vns_hrv {
        frequency: 25Hz
        intensity: 1.5mA
        hrv_protocol: standalone
        breathing_rate: 6.0
    }

    audio_entrainment {
        noise: pink
        carrier_hz: 440Hz
        volume: 40%
        eeg_adaptive: false
        bone_conduction_pacer: true
    }

}
""",
        """
protocol "HRV + taVNS Synchronised" {
    id: "1000000C-0000-0000-0000-000000000000"
    description: "Stimulation pulses timed to inspiration phase for optimised noradrenergic modulation. Alpha EEG neurofeedback adds cortical awareness layer."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [HRV, VNS, advanced, synchronised]
    duration: 20m

    vns_hrv {
        frequency: 25Hz
        intensity: 1.5mA
        hrv_protocol: tavns_sync
        breathing_rate: 6.0
    }

    eeg_neurofeedback {
        band: alpha
        channels: all
        closed_loop: true
    }

}
""",
        """
protocol "Focus Prime" {
    id: "1000000D-0000-0000-0000-000000000000"
    description: "20Hz beta/focus protocol combining PBM, closed-loop EEG, BES, binaural audio, and visual entrainment. BES runs in 30-on/30-off intervals for habituation prevention."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [focus, beta, cognitive, productivity]
    duration: 20m

    pbm_transcranial {
        intensity: 80%
        frequency: 20Hz
        duty_cycle: 25%
        zones: all
        wavelength: 660_808nm
    }

    eeg_neurofeedback {
        band: beta
        channels: all
        closed_loop: true
    }

    bes_tacs {
        frequency: 20Hz
        intensity: 0.8mA
        waveform: sinusoidal
        interval_on: 30s
        interval_off: 30s
        repeat: until_end
    }

    audio_entrainment {
        binaural_hz: 20Hz
        noise: pink
        carrier_hz: 440Hz
        volume: 60%
        eeg_adaptive: true
        bone_conduction_pacer: false
    }

    visual_stimulation {
        frequency: 20Hz
        mode: binocular
        emdr_cadence: 1Hz
        interval_on: 300s
        interval_off: 120s
        repeat: until_end
    }

}
""",
        """
protocol "Gamma + Theta Coupled" {
    id: "1000000E-0000-0000-0000-000000000000"
    description: "Simultaneous 40Hz front-zone PBM and 6Hz rear-zone PBM with gamma-theta EEG coupling, binaural + isochronic audio, 40Hz visual entrainment, and BES."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [focus, gamma, theta, coupled, advanced]
    duration: 20m

    pbm_transcranial {
        intensity: 75%
        frequency: 40Hz
        duty_cycle: 25%
        zones: front
        wavelength: 660_808nm
    }

    pbm_transcranial {
        intensity: 70%
        frequency: 6Hz
        duty_cycle: 25%
        zones: rear
        wavelength: 660_808nm
    }

    eeg_neurofeedback {
        band: gamma_theta
        channels: all
        closed_loop: true
    }

    audio_entrainment {
        binaural_hz: 40Hz
        isochronic_hz: 6Hz
        noise: pink
        carrier_hz: 440Hz
        volume: 60%
        eeg_adaptive: true
        bone_conduction_pacer: false
    }

    visual_stimulation {
        frequency: 40Hz
        mode: binocular
        emdr_cadence: 1Hz
    }

    bes_tacs {
        frequency: 40Hz
        intensity: 0.8mA
        waveform: sinusoidal
    }

}
""",
        """
protocol "Full T1 Immersive" {
    id: "1000000F-0000-0000-0000-000000000000"
    description: "All 8 T1 modalities running simultaneously with balanced settings. For experienced users. Intranasal PBM and tDCS run in time-limited intervals within the 30-minute session."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [comprehensive, all-modalities, advanced, T1]
    duration: 30m

    pbm_transcranial {
        intensity: 75%
        frequency: 40Hz
        duty_cycle: 25%
        zones: all
        wavelength: 660_808nm
    }

    pbm_intranasal {
        intensity: 60%
        frequency: 40Hz
        duty_cycle: 25%
        interval_on: 15m
        interval_off: 15m
        repeat: 1
    }

    eeg_neurofeedback {
        band: gamma
        channels: all
        closed_loop: true
    }

    bes_tacs {
        frequency: 40Hz
        intensity: 0.8mA
        waveform: sinusoidal
    }

    vns_hrv {
        frequency: 25Hz
        intensity: 1.5mA
        hrv_protocol: tavns_sync
        breathing_rate: 6.0
    }

    audio_entrainment {
        isochronic_hz: 40Hz
        noise: pink
        carrier_hz: 440Hz
        volume: 60%
        eeg_adaptive: true
        bone_conduction_pacer: true
    }

    visual_stimulation {
        frequency: 40Hz
        mode: binocular
        emdr_cadence: 1Hz
    }

    tdcs {
        intensity: 1.0mA
        electrode_pairs: [["Fp1", "P3"]]
        ramp: 30s  # hardware-enforced
        interval_on: 20m
        interval_off: 10m
        repeat: 1
    }

}
""",
        """
composite "Full Multi-Modal RCT" {
    id: "10000100-0000-0000-0000-000000000000"
    description: "Replicates the 2025 nationally-conducted RCT protocol combining PBM + qEEG neurofeedback + HRV biofeedback simultaneously. Sequence: vascular baseline → combined active phase → cool-down HRV."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [rct, multimodal, pbm, eeg, hrv, research, depression]
    conflict_resolution: merge

    layer "Vascular Baseline" {
        start: 0s
        duration: 5m
        intensity_scale: 0.5
    }

    layer "Gamma Focus" {
        start: 300s
        duration: 20m
        intensity_scale: 1.0
    }

    layer "HRV Coherence Training" {
        start: 300s
        duration: 20m
        intensity_scale: 1.0
    }

    layer "Alpha Calm" {
        start: 1500s
        duration: 10m
        intensity_scale: 0.6
    }

}
""",
        """
composite "Sleep Optimisation Stack" {
    id: "10000101-0000-0000-0000-000000000000"
    description: "Evening stack: alpha wind-down then HRV coherence then deep sleep induction. Runs for approximately 90 minutes starting 2 hours before target sleep time."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [sleep, evening, wind-down, delta, alpha, stack]
    conflict_resolution: sequential

    layer "Alpha Calm" {
        start: 0s
        duration: 20m
        intensity_scale: 0.8
    }

    layer "HRV Coherence Training" {
        start: 600s
        duration: 10m
        intensity_scale: 0.7
    }

    layer "Deep Sleep" {
        start: 1200s
        intensity_scale: 1.0
    }

}
""",
        """
composite "Calm to Focus" {
    id: "10000102-0000-0000-0000-000000000000"
    description: "Transitions from alpha calm to focused beta. Layers overlap for 2 minutes, allowing smooth frequency transition from 10Hz to 20Hz."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [transition, ramp, productivity, calm, focus]
    conflict_resolution: merge

    layer "Alpha Calm" {
        start: 0s
        duration: 10m
        intensity_scale: 1.0
    }

    layer "Focus Prime" {
        start: 480s
        duration: 20m
        intensity_scale: 1.0
    }

}
""",
        """
composite "Sleep Wind-Down" {
    id: "10000103-0000-0000-0000-000000000000"
    description: "Sequential transition from alpha calm to deep sleep preparation. No overlap — alpha calm finishes before sleep deep begins."
    author: "NeurOne"
    version: "1.0"
    readonly: true
    tags: [sleep, wind-down, transition, evening]
    conflict_resolution: sequential

    layer "Alpha Calm" {
        start: 0s
        duration: 10m
        intensity_scale: 1.0
    }

    layer "Deep Sleep" {
        start: 600s
        intensity_scale: 1.0
    }

}
""",
    )
}
