// :core — Kotlin Multiplatform module. NO Android plugin, NO android.* imports.
//
// Everything in commonMain compiles for every target: the JVM (Android and the macOS/Windows desktop
// apps), wasmJs (the web app) and iOS. The platform differences are the small expect/actual set in
// life.neurone.core.platform and the NPPS binding in life.neurone.core.npps. Privacy-critical logic
// stays verifiable in CI without an Android SDK (ISC-2, ISC-3, ISC-4 in app/android/ISA.md): the
// jvmTest task runs on a plain JVM.

import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
}

// ── Predefined protocol bundling ───────────────────────────────────────────
// The .npps library in protocols/predefined/ is the single source of truth for
// every runtime (web fetches it, iOS bundles it, this module compiles it in). It is generated into
// Kotlin at build time rather than transcribed or read from a resource path: NPBundledProtocols.kt
// used to be a hand-maintained duplicate and had drifted — 8 of its 17 protocols were missing the
// conditions/references fields added in NP-NPPS-REF-001 Rev 2 — and a JVM resource path does not
// exist on iOS or in a browser.
val predefinedProtocolsDir = layout.projectDirectory.dir("../../../protocols/predefined")
val generatedBundledDir = layout.buildDirectory.dir("generated/bundled/commonMain/kotlin")

val generateBundledProtocols by tasks.registering {
    description = "Compiles protocols/predefined into BundledProtocolFiles.kt."
    group = "build"
    inputs.dir(predefinedProtocolsDir).withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.dir(generatedBundledDir)
    doLast {
        fun literal(text: String): String {
            val sb = StringBuilder("\"")
            for (ch in text) when {
                ch == '\\' -> sb.append("\\\\")
                ch == '"' -> sb.append("\\\"")
                ch == '$' -> sb.append("\\$")
                ch == '\n' -> sb.append("\\n")
                ch == '\r' -> sb.append("\\r")
                ch == '\t' -> sb.append("\\t")
                ch.code < 0x20 || ch.code > 0x7e -> sb.append("\\u%04x".format(ch.code))
                else -> sb.append(ch)
            }
            return sb.append('"').toString()
        }
        val files = predefinedProtocolsDir.asFile.listFiles { f -> f.name.endsWith(".npps") || f.name == "manifest.json" }!!
            .sortedBy { it.name }
        val out = generatedBundledDir.get().asFile.resolve("life/neurone/core/protocol/BundledProtocolFiles.kt")
        out.parentFile.mkdirs()
        out.writeText(buildString {
            appendLine("// GENERATED by :core generateBundledProtocols from protocols/predefined — do not edit.")
            appendLine("package life.neurone.core.protocol")
            appendLine()
            appendLine("/** Every file in protocols/predefined, by file name. One JVM constant per file stays under the 64 KB limit. */")
            appendLine("internal object BundledProtocolFiles {")
            appendLine("    val files: Map<String, String> = mapOf(")
            for (f in files) appendLine("        ${literal(f.name)} to ${literal(f.readText())},")
            appendLine("    )")
            appendLine("}")
        })
    }
}

// ── Golden test data, compiled into the common tests ─────────────────────────
// The binding parity tests (NppsBackendParityTests) run on every target, and only the JVM can read a file, so the
// goldens the web parser and compiler produced (app/NeurOneShared/TestData) are generated into Kotlin. Strings
// are chunked: one JVM constant is capped at 64 KB.
val testDataDir = layout.projectDirectory.dir("../../NeurOneShared/TestData")
val generatedGoldensDir = layout.buildDirectory.dir("generated/goldens/commonTest/kotlin")
val repoFixtures: java.io.File = layout.projectDirectory.dir("../../../npps/fixtures").asFile

val generateTestGoldens by tasks.registering {
    description = "Compiles the NPPS goldens into TestGoldens.kt for commonTest."
    group = "build"
    val sources = mapOf(
        "parse" to "npps-parse-golden.json",
        "hubCases" to "hub-descriptor-cases.json",
        "hubGolden" to "hub-descriptor-golden.json",
    )
    inputs.files(sources.values.map { testDataDir.file(it) })
    inputs.dir(repoFixtures)
    outputs.dir(generatedGoldensDir)
    doLast {
        fun literal(text: String): String {
            val sb = StringBuilder("\"")
            for (ch in text) when {
                ch == '\\' -> sb.append("\\\\")
                ch == '"' -> sb.append("\\\"")
                ch == '$' -> sb.append("\\$")
                ch == '\n' -> sb.append("\\n")
                ch == '\r' -> sb.append("\\r")
                ch == '\t' -> sb.append("\\t")
                ch.code < 0x20 || ch.code > 0x7e -> sb.append("\\u%04x".format(ch.code))
                else -> sb.append(ch)
            }
            return sb.append('"').toString()
        }
        val out = generatedGoldensDir.get().asFile.resolve("life/neurone/core/npps/TestGoldens.kt")
        out.parentFile.mkdirs()
        out.writeText(buildString {
            appendLine("// GENERATED by :core generateTestGoldens from app/NeurOneShared/TestData — do not edit.")
            appendLine("package life.neurone.core.npps")
            appendLine()
            appendLine("internal object TestGoldens {")
            for ((name, file) in sources) {
                val chunks = testDataDir.file(file).asFile.readText().chunked(12_000)
                appendLine("    val $name: String = listOf(")
                for (chunk in chunks) appendLine("        ${literal(chunk)},")
                appendLine("    ).joinToString(\"\")")
            }
            // The shared fixtures the parse golden also covers, by repository-relative path.
            val fixtures = repoFixtures.listFiles { f -> f.name.endsWith(".npps") }!!.sortedBy { it.name }
            appendLine("    val fixtures: Map<String, String> = mapOf(")
            for (f in fixtures) {
                appendLine("        ${literal("npps/fixtures/" + f.name)} to listOf(")
                for (chunk in f.readText().chunked(12_000).ifEmpty { listOf("") }) appendLine("            ${literal(chunk)},")
                appendLine("        ).joinToString(\"\"),")
            }
            appendLine("    )")
            appendLine("}")
        })
    }
}

// ── The shared NPPS core on Apple targets (OI-UI-KMP-01) ──────────────────────
// Kotlin/Native calls the C ABI of common/npps-ffi through cinterop, so the static library for each Apple
// architecture must exist before cinterop runs. cargo only builds them on a macOS host; elsewhere the Apple
// targets are not compiled at all (kotlin.native.ignoreDisabledTargets), so there is nothing to build for.
val isMacHost = System.getProperty("os.name").startsWith("Mac")
val appleRustTargets = mapOf(
    "iosArm64" to "aarch64-apple-ios",
    "iosSimulatorArm64" to "aarch64-apple-ios-sim",
    "iosX64" to "x86_64-apple-ios",
)
val nppsFfiCommonDir: java.io.File = layout.projectDirectory.dir("../../../common").asFile

val buildNppsFfiTasks = appleRustTargets.mapValues { (kotlinTarget, triple) ->
    tasks.register<Exec>("buildNppsFfi${kotlinTarget.replaceFirstChar { it.uppercase() }}") {
        group = "build"
        description = "Builds libneurone_npps_ffi.a for $triple (macOS host only)."
        enabled = isMacHost
        workingDir = nppsFfiCommonDir
        environment("IPHONEOS_DEPLOYMENT_TARGET", "17.0")
        commandLine("cargo", "build", "--release", "--locked", "-p", "neurone-npps-ffi", "--target", triple)
        inputs.dir(File(nppsFfiCommonDir, "npps-core")).withPathSensitivity(PathSensitivity.RELATIVE)
        inputs.dir(File(nppsFfiCommonDir, "npps-ffi")).withPathSensitivity(PathSensitivity.RELATIVE)
        inputs.file(File(nppsFfiCommonDir, "npps/fields.json"))
        inputs.file(File(nppsFfiCommonDir, "Cargo.lock"))
        outputs.dir(File(nppsFfiCommonDir, "target/$triple/release"))
    }
}

// ── The shared NPPS core in the browser and Node (OI-UI-KMP-01) ───────────────
// neurone_npps.wasm is the C ABI built for wasm32 by scripts/build-npps-wasm.sh. The Node test run reads it
// from disk; the web app serves it (see :web).
val nppsWasm: java.io.File = nppsFfiCommonDir.resolve("generated/neurone_npps.wasm")
val buildNppsWasm by tasks.registering(Exec::class) {
    group = "build"
    description = "Builds neurone_npps.wasm with scripts/build-npps-wasm.sh."
    workingDir = nppsFfiCommonDir.parentFile
    commandLine("bash", "scripts/build-npps-wasm.sh")
    inputs.dir(File(nppsFfiCommonDir, "npps-core")).withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.dir(File(nppsFfiCommonDir, "npps-ffi")).withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(File(nppsFfiCommonDir, "npps/fields.json"))
    inputs.file(File(nppsFfiCommonDir, "Cargo.lock"))
    outputs.file(nppsWasm)
}

kotlin {
    jvm {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        // The binding parity tests run under Node: a browser run needs a browser installed.
        nodejs()
    }
    listOf(iosArm64(), iosSimulatorArm64(), iosX64()).forEach { target ->
        val triple = appleRustTargets.getValue(target.name)
        target.compilations.getByName("main").cinterops.create("nppsFfi") {
            definitionFile.set(project.file("src/nativeInterop/cinterop/nppsFfi.def"))
            includeDirs(File(nppsFfiCommonDir, "npps-ffi/include"))
            // The static library is embedded in the klib, so every framework that links :core carries the core.
            extraOpts("-libraryPath", File(nppsFfiCommonDir, "target/$triple/release").absolutePath, "-staticLibrary", "libneurone_npps_ffi.a")
            tasks.matching { it.name == interopProcessingTaskName }.configureEach {
                dependsOn(buildNppsFfiTasks.getValue(target.name))
            }
        }
    }

    sourceSets {
        commonMain {
            // Through the task, so every consumer of the sources (the metadata compilation CodeQL runs included)
            // waits for the generation.
            kotlin.srcDir(generateBundledProtocols.map { generatedBundledDir.get() })
            dependencies {
                // `api` (not `implementation`): `Json` is part of core's public API — it appears in the
                // default constructor arguments of SessionHistoryStore/ConsentStore — so consumers
                // need it on their compile classpath.
                api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
                api("org.jetbrains.kotlinx:kotlinx-datetime:0.6.1")
            }
        }
        commonTest {
            kotlin.srcDir(generateTestGoldens.map { generatedGoldensDir.get() })
            dependencies {
                implementation(kotlin("test"))
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
            }
        }
        wasmJsMain.dependencies {
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
        }
        jvmTest {
            // Test data shared by every app lives in app/NeurOneShared/TestData, not under this module
            // (hub-descriptor-golden.json is read by the Android, iOS and Windows tests).
            resources.srcDir(layout.projectDirectory.dir("../../NeurOneShared/TestData"))
            // locales/en.json: the validator returns locale keys, and the tests resolve them in English (TestLocale).
            resources.srcDir(layout.projectDirectory.dir("../../../locales"))
            dependencies {
                implementation("org.junit.jupiter:junit-jupiter:5.10.2")
                runtimeOnly("org.junit.platform:junit-platform-launcher")
            }
        }
    }
}

tasks.matching { it.name.startsWith("compileKotlin") || it.name.endsWith("SourcesJar") || it.name == "sourcesJar" }
    .configureEach { dependsOn(generateBundledProtocols) }
tasks.matching { it.name.startsWith("compileTestKotlin") }.configureEach { dependsOn(generateTestGoldens) }

// The wasm Node test reads the module from disk; the browser test is not run.
tasks.matching { it.name == "wasmJsNodeTest" }.configureEach {
    dependsOn(buildNppsWasm)
    (this as org.jetbrains.kotlin.gradle.targets.js.testing.KotlinJsTest).environment("NEURONE_NPPS_WASM", nppsWasm.absolutePath)
}

// ── The shared NPPS core (OI-NPPS-CORE-01) ───────────────────────────────────
// common/npps-jni is the JNI binding of the Rust core. The tests that call it (NppsCoreTests)
// need the host build of it, so the test task builds it first and puts it on java.library.path.
// cargo must be on PATH; a missing toolchain fails the build rather than skipping the tests,
// because a skipped test is a parity check that silently stopped checking. Packaging the
// library for a device (cargo-ndk, four ABIs, :app jniLibs) is wired in :app.
val repoCommon: java.io.File = layout.projectDirectory.dir("../../../common").asFile
val buildNppsCoreHost by tasks.registering(Exec::class) {
    group = "build"
    description = "Builds the host (JVM test) copy of the NPPS core's JNI library."
    workingDir = repoCommon
    commandLine("cargo", "build", "--release", "--locked", "-p", "neurone-npps-jni")
    inputs.dir(File(repoCommon, "npps-core")).withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.dir(File(repoCommon, "npps-jni")).withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(File(repoCommon, "npps/fields.json"))
    inputs.file(File(repoCommon, "Cargo.lock"))
    outputs.dir(File(repoCommon, "target/release"))
}

tasks.named<Test>("jvmTest") {
    useJUnitPlatform()
    dependsOn(buildNppsCoreHost)
    systemProperty("java.library.path", File(repoCommon, "target/release").absolutePath)
}
