// :core — Kotlin Multiplatform module. NO Android plugin, NO android.* imports.
//
// Everything in commonMain compiles for every target: the JVM (Android and the macOS/Windows desktop
// apps), wasmJs (the web app) and iOS. The platform differences are the small expect/actual set in
// life.neurone.core.platform and the NPPS binding in life.neurone.core.npps. Privacy-critical logic
// stays verifiable in CI without an Android SDK (ISC-2, ISC-3, ISC-4 in app/android/ISA.md): the
// jvmTest task runs on a plain JVM.

import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    kotlin("multiplatform")
    kotlin("plugin.serialization")
}

// ── Predefined protocol bundling ───────────────────────────────────────────
// The .npps library in protocols/predefined/ is the single source of truth for
// every runtime (web fetches it, iOS bundles it, this module compiles it in). It is generated into
// Kotlin at build time rather than transcribed or read from a resource path: NPBundledProtocols.kt
// used to be a hand-maintained duplicate and had drifted — 8 of its 17 protocols were missing the
// conditions/references fields added in NP-NPPS-REF-001 Rev 2 — and a JVM resource path does not
// exist on iOS or in a browser.
val predefinedProtocolsDir = layout.projectDirectory.dir("../../../protocols/predefined")
val generatedBundledDir = layout.buildDirectory.dir("generated/bundled/commonMain/kotlin")

val generateBundledProtocols by tasks.registering {
    description = "Compiles protocols/predefined into BundledProtocolFiles.kt."
    group = "build"
    inputs.dir(predefinedProtocolsDir).withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.dir(generatedBundledDir)
    doLast {
        fun literal(text: String): String {
            val sb = StringBuilder("\"")
            for (ch in text) when {
                ch == '\\' -> sb.append("\\\\")
                ch == '"' -> sb.append("\\\"")
                ch == '$' -> sb.append("\\$")
                ch == '\n' -> sb.append("\\n")
                ch == '\r' -> sb.append("\\r")
                ch == '\t' -> sb.append("\\t")
                ch.code < 0x20 || ch.code > 0x7e -> sb.append("\\u%04x".format(ch.code))
                else -> sb.append(ch)
            }
            return sb.append('"').toString()
        }
        val files = predefinedProtocolsDir.asFile.listFiles { f -> f.name.endsWith(".npps") || f.name == "manifest.json" }!!
            .sortedBy { it.name }
        val out = generatedBundledDir.get().asFile.resolve("life/neurone/core/protocol/BundledProtocolFiles.kt")
        out.parentFile.mkdirs()
        out.writeText(buildString {
            appendLine("// GENERATED by :core generateBundledProtocols from protocols/predefined — do not edit.")
            appendLine("package life.neurone.core.protocol")
            appendLine()
            appendLine("/** Every file in protocols/predefined, by file name. One JVM constant per file stays under the 64 KB limit. */")
            appendLine("internal object BundledProtocolFiles {")
            appendLine("    val files: Map<String, String> = mapOf(")
            for (f in files) appendLine("        ${literal(f.name)} to ${literal(f.readText())},")
            appendLine("    )")
            appendLine("}")
        })
    }
}

kotlin {
    jvm {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs { browser() }
    iosArm64()
    iosSimulatorArm64()
    iosX64()

    sourceSets {
        commonMain {
            kotlin.srcDir(generatedBundledDir)
            dependencies {
                // `api` (not `implementation`): `Json` is part of core's public API — it appears in the
                // default constructor arguments of SessionHistoryStore/ConsentStore — so consumers
                // need it on their compile classpath.
                api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
                api("org.jetbrains.kotlinx:kotlinx-datetime:0.6.1")
            }
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
        }
        jvmTest {
            // Test data shared by every app lives in app/NeurOneShared/TestData, not under this module
            // (hub-descriptor-golden.json is read by the Android, iOS and Windows tests).
            resources.srcDir(layout.projectDirectory.dir("../../NeurOneShared/TestData"))
            // locales/en.json: the validator returns locale keys, and the tests resolve them in English (TestLocale).
            resources.srcDir(layout.projectDirectory.dir("../../../locales"))
            dependencies {
                implementation("org.junit.jupiter:junit-jupiter:5.10.2")
                runtimeOnly("org.junit.platform:junit-platform-launcher")
            }
        }
    }
}

tasks.matching { it.name.startsWith("compileKotlin") || it.name.endsWith("SourcesJar") || it.name == "sourcesJar" }
    .configureEach { dependsOn(generateBundledProtocols) }

// ── The shared NPPS core (OI-NPPS-CORE-01) ───────────────────────────────────
// common/npps-jni is the JNI binding of the Rust core. The tests that call it (NppsCoreTests)
// need the host build of it, so the test task builds it first and puts it on java.library.path.
// cargo must be on PATH; a missing toolchain fails the build rather than skipping the tests,
// because a skipped test is a parity check that silently stopped checking. Packaging the
// library for a device (cargo-ndk, four ABIs, :app jniLibs) is wired in :app.
val repoCommon: java.io.File = layout.projectDirectory.dir("../../../common").asFile
val buildNppsCoreHost by tasks.registering(Exec::class) {
    group = "build"
    description = "Builds the host (JVM test) copy of the NPPS core's JNI library."
    workingDir = repoCommon
    commandLine("cargo", "build", "--release", "--locked", "-p", "neurone-npps-jni")
    inputs.dir(File(repoCommon, "npps-core")).withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.dir(File(repoCommon, "npps-jni")).withPathSensitivity(PathSensitivity.RELATIVE)
    inputs.file(File(repoCommon, "npps/fields.json"))
    inputs.file(File(repoCommon, "Cargo.lock"))
    outputs.dir(File(repoCommon, "target/release"))
}

tasks.named<Test>("jvmTest") {
    useJUnitPlatform()
    dependsOn(buildNppsCoreHost)
    systemProperty("java.library.path", File(repoCommon, "target/release").absolutePath)
}
