// Generated by scripts/sync-socket-map.ts — DO NOT EDIT BY HAND.
// Regenerate with: bun scripts/sync-socket-map.ts
// Geometry is validated on every run against protocols/predefined/00-zones.npps.
// Scan-grounded v1 lattice (NP-HEX-ZM-001 §3.4) — PROVISIONAL pending REG-1 / ACT-1.
// x/y are PROVISIONAL unit-hex lattice coordinates for layout only, not mm.

export interface NPSocketGeometry {
  /** 1-based socket id, matching the `sockets:` lists in .npps zone files. */
  id: number;
  row: number;
  col: number;
  /** Provisional unit-hex lattice coordinates — layout only, not millimetres. */
  x: number;
  y: number;
  /**
   * Position in 3-space, MILLIMETRES, aircraft body axes, origin at the centre
   * of the ellipsoid the helmet is a partial shell of:
   *   +x forward (toward the face), +y right, +z down.
   * The vault has negative z; the crown sits at z = -157.
   *
   * There is deliberately no lobe and no side here. A socket's anatomical
   * meaning is its ZONE MEMBERSHIP, authored in
   * protocols/predefined/00-zones.npps — not a property of the hardware.
   */
  xMm: number;
  yMm: number;
  zMm: number;
}

/** Semi-axes of the modelled ellipsoid, mm (fore/aft, lateral, vertical). */
export const NP_ELLIPSOID_SEMI_AXES_MM = {
  foreAft: 133.5,
  lateral: 114.5,
  vertical: 157,
} as const;

/** Every socket in the helmet, ordered by id. */
export const NP_SOCKETS: readonly NPSocketGeometry[] = [
  { id: 1, row: 0, col: 0, x: -1, y: 0, xMm: 126.32, yMm: -25.66, zMm: -11.47 },
  { id: 2, row: 0, col: 1, x: 0, y: 0, xMm: 118.85, yMm: 0, zMm: -34.82 },
  { id: 3, row: 0, col: 2, x: 1, y: 0, xMm: 123.33, yMm: 25.06, zMm: -11.2 },
  { id: 4, row: 1, col: 0, x: -2.5, y: 0.866, xMm: 120.85, yMm: -52.45, zMm: 0 },
  { id: 5, row: 1, col: 1, x: -1.5, y: 0.866, xMm: 111.99, yMm: -41.19, zMm: -35.39 },
  { id: 6, row: 1, col: 2, x: -0.5, y: 0.866, xMm: 96.22, yMm: -15.01, zMm: -53.43 },
  { id: 7, row: 1, col: 3, x: 0.5, y: 0.866, xMm: 101.34, yMm: 15.81, zMm: -56.28 },
  { id: 8, row: 1, col: 4, x: 1.5, y: 0.866, xMm: 113.46, yMm: 41.73, zMm: -35.85 },
  { id: 9, row: 1, col: 5, x: 2.5, y: 0.866, xMm: 118.3, yMm: 51.35, zMm: 0 },
  { id: 10, row: 2, col: 0, x: -3, y: 1.7321, xMm: 104.85, yMm: -74.36, zMm: -18.43 },
  { id: 11, row: 2, col: 1, x: -2, y: 1.7321, xMm: 85.78, yMm: -51.38, zMm: -47.14 },
  { id: 12, row: 2, col: 2, x: -1, y: 1.7321, xMm: 82.52, yMm: -29.74, zMm: -70.61 },
  { id: 13, row: 2, col: 3, x: 0, y: 1.7321, xMm: 90.38, yMm: 0, zMm: -89.31 },
  { id: 14, row: 2, col: 4, x: 1, y: 1.7321, xMm: 89.68, yMm: 32.32, zMm: -76.74 },
  { id: 15, row: 2, col: 5, x: 2, y: 1.7321, xMm: 87.15, yMm: 52.2, zMm: -47.9 },
  { id: 16, row: 2, col: 6, x: 3, y: 1.7321, xMm: 102.71, yMm: 72.84, zMm: -18.06 },
  { id: 17, row: 3, col: 0, x: -3.5, y: 2.5981, xMm: 79.68, yMm: -89.92, zMm: -33.02 },
  { id: 18, row: 3, col: 1, x: -2.5, y: 2.5981, xMm: 79.48, yMm: -77.06, zMm: -71.03 },
  { id: 19, row: 3, col: 2, x: -1.5, y: 2.5981, xMm: 72.16, yMm: -48.93, zMm: -94.14 },
  { id: 20, row: 3, col: 3, x: -0.5, y: 2.5981, xMm: 71.72, yMm: -17.9, zMm: -112.24 },
  { id: 21, row: 3, col: 4, x: 0.5, y: 2.5981, xMm: 70.61, yMm: 17.62, zMm: -110.49 },
  { id: 22, row: 3, col: 5, x: 1.5, y: 2.5981, xMm: 71.95, yMm: 48.78, zMm: -93.86 },
  { id: 23, row: 3, col: 6, x: 2.5, y: 2.5981, xMm: 72.49, yMm: 70.28, zMm: -64.78 },
  { id: 24, row: 3, col: 7, x: 3.5, y: 2.5981, xMm: 78.86, yMm: 88.99, zMm: -32.68 },
  { id: 25, row: 4, col: 0, x: -4, y: 3.4641, xMm: 52.08, yMm: -106.22, zMm: -40.04 },
  { id: 26, row: 4, col: 1, x: -3, y: 3.4641, xMm: 46.23, yMm: -83.13, zMm: -70.59 },
  { id: 27, row: 4, col: 2, x: -2, y: 3.4641, xMm: 45.4, yMm: -62.52, zMm: -99.92 },
  { id: 28, row: 4, col: 3, x: -1, y: 3.4641, xMm: 45.51, yMm: -34.8, zMm: -123.06 },
  { id: 29, row: 4, col: 4, x: 0, y: 3.4641, xMm: 45.48, yMm: 0, zMm: -131.89 },
  { id: 30, row: 4, col: 5, x: 1, y: 3.4641, xMm: 46.16, yMm: 35.29, zMm: -124.81 },
  { id: 31, row: 4, col: 6, x: 2, y: 3.4641, xMm: 45.13, yMm: 62.15, zMm: -99.34 },
  { id: 32, row: 4, col: 7, x: 3, y: 3.4641, xMm: 45.63, yMm: 82.05, zMm: -69.68 },
  { id: 33, row: 4, col: 8, x: 4, y: 3.4641, xMm: 46.64, yMm: 95.12, zMm: -35.86 },
  { id: 34, row: 5, col: 0, x: -3.5, y: 4.3301, xMm: 16.16, yMm: -94.64, zMm: -66.8 },
  { id: 35, row: 5, col: 1, x: -2.5, y: 4.3301, xMm: 16.19, yMm: -77.64, zMm: -100.24 },
  { id: 36, row: 5, col: 2, x: -1.5, y: 4.3301, xMm: 16.18, yMm: -52.08, zMm: -127.52 },
  { id: 37, row: 5, col: 3, x: -0.5, y: 4.3301, xMm: 16.15, yMm: -18.56, zMm: -143.64 },
  { id: 38, row: 5, col: 4, x: 0.5, y: 4.3301, xMm: 15.77, yMm: 18.13, zMm: -140.29 },
  { id: 39, row: 5, col: 5, x: 1.5, y: 4.3301, xMm: 16.06, yMm: 51.69, zMm: -126.57 },
  { id: 40, row: 5, col: 6, x: 2.5, y: 4.3301, xMm: 16.16, yMm: 77.51, zMm: -100.07 },
  { id: 41, row: 5, col: 7, x: 3.5, y: 4.3301, xMm: 15.78, yMm: 92.41, zMm: -65.23 },
  { id: 42, row: 6, col: 0, x: -4, y: 5.1962, xMm: -18.12, yMm: -112.45, zMm: -54.87 },
  { id: 43, row: 6, col: 1, x: -3, y: 5.1962, xMm: -15.77, yMm: -85, zMm: -81.95 },
  { id: 44, row: 6, col: 2, x: -2, y: 5.1962, xMm: -15.79, yMm: -64.34, zMm: -112.11 },
  { id: 45, row: 6, col: 3, x: -1, y: 5.1962, xMm: -15.81, yMm: -35.36, zMm: -134.32 },
  { id: 46, row: 6, col: 4, x: 0, y: 5.1962, xMm: -15.99, yMm: 0, zMm: -144.49 },
  { id: 47, row: 6, col: 5, x: 1, y: 5.1962, xMm: -16.11, yMm: 36.03, zMm: -136.87 },
  { id: 48, row: 6, col: 6, x: 2, y: 5.1962, xMm: -15.95, yMm: 65, zMm: -113.27 },
  { id: 49, row: 6, col: 7, x: 3, y: 5.1962, xMm: -15.6, yMm: 84.06, zMm: -81.04 },
  { id: 50, row: 6, col: 8, x: 4, y: 5.1962, xMm: -15.69, yMm: 97.41, zMm: -47.53 },
  { id: 51, row: 7, col: 0, x: -3.5, y: 6.0622, xMm: -45.53, yMm: -88.33, zMm: -52.57 },
  { id: 52, row: 7, col: 1, x: -2.5, y: 6.0622, xMm: -47.48, yMm: -76.51, zMm: -89.21 },
  { id: 53, row: 7, col: 2, x: -1.5, y: 6.0622, xMm: -46.87, yMm: -51.31, zMm: -116.32 },
  { id: 54, row: 7, col: 3, x: -0.5, y: 6.0622, xMm: -47.53, yMm: -18.74, zMm: -135.44 },
  { id: 55, row: 7, col: 4, x: 0.5, y: 6.0622, xMm: -47.17, yMm: 18.6, zMm: -134.39 },
  { id: 56, row: 7, col: 5, x: 1.5, y: 6.0622, xMm: -47.42, yMm: 51.9, zMm: -117.67 },
  { id: 57, row: 7, col: 6, x: 2.5, y: 6.0622, xMm: -46.98, yMm: 75.69, zMm: -88.26 },
  { id: 58, row: 7, col: 7, x: 3.5, y: 6.0622, xMm: -45.67, yMm: 88.6, zMm: -52.73 },
  { id: 59, row: 8, col: 0, x: -3, y: 6.9282, xMm: -72.63, yMm: -77.34, zMm: -47.88 },
  { id: 60, row: 8, col: 1, x: -2, y: 6.9282, xMm: -72.17, yMm: -60.71, zMm: -80.22 },
  { id: 61, row: 8, col: 2, x: -1, y: 6.9282, xMm: -76.13, yMm: -36.5, zMm: -111.22 },
  { id: 62, row: 8, col: 3, x: 0, y: 6.9282, xMm: -74.93, yMm: 0, zMm: -120.03 },
  { id: 63, row: 8, col: 4, x: 1, y: 6.9282, xMm: -75.64, yMm: 36.27, zMm: -110.5 },
  { id: 64, row: 8, col: 5, x: 2, y: 6.9282, xMm: -73.08, yMm: 61.48, zMm: -81.23 },
  { id: 65, row: 8, col: 6, x: 3, y: 6.9282, xMm: -71.6, yMm: 76.24, zMm: -47.21 },
  { id: 66, row: 9, col: 0, x: -2.5, y: 7.7942, xMm: -94.7, yMm: -63.36, zMm: -34.77 },
  { id: 67, row: 9, col: 1, x: -1.5, y: 7.7942, xMm: -96.89, yMm: -48.12, zMm: -69.37 },
  { id: 68, row: 9, col: 2, x: -0.5, y: 7.7942, xMm: -99.91, yMm: -19.12, zMm: -95.19 },
  { id: 69, row: 9, col: 3, x: 0.5, y: 7.7942, xMm: -99.31, yMm: 19, zMm: -94.62 },
  { id: 70, row: 9, col: 4, x: 1.5, y: 7.7942, xMm: -96.57, yMm: 47.97, zMm: -69.15 },
  { id: 71, row: 9, col: 5, x: 2.5, y: 7.7942, xMm: -93.54, yMm: 62.59, zMm: -34.34 },
  { id: 72, row: 10, col: 0, x: -2, y: 8.6603, xMm: -116.85, yMm: -49.27, zMm: -16.47 },
  { id: 73, row: 10, col: 1, x: -1, y: 8.6603, xMm: -113.2, yMm: -32.61, zMm: -50.38 },
  { id: 74, row: 10, col: 2, x: 0, y: 8.6603, xMm: -115.2, yMm: 0, zMm: -68.56 },
  { id: 75, row: 10, col: 3, x: 1, y: 8.6603, xMm: -112.56, yMm: 32.43, zMm: -50.1 },
  { id: 76, row: 10, col: 4, x: 2, y: 8.6603, xMm: -116.19, yMm: 48.99, zMm: -16.37 },
  { id: 77, row: 11, col: 0, x: -1.5, y: 9.5263, xMm: -123.2, yMm: -26.33, zMm: 0 },
  { id: 78, row: 11, col: 1, x: -0.5, y: 9.5263, xMm: -126.15, yMm: -15.15, zMm: -30.58 },
  { id: 79, row: 11, col: 2, x: 0.5, y: 9.5263, xMm: -125.72, yMm: 15.1, zMm: -30.47 },
  { id: 80, row: 11, col: 3, x: 1.5, y: 9.5263, xMm: -121.82, yMm: 26.03, zMm: 0 },
];

export const NP_SOCKET_COUNT = 80;

/**
 * Socket ids are 1-based. This is the numbering base every consumer must honour
 * — .npps `sockets:` lists, the firmware major address, and the UI picker.
 */
export const NP_SOCKET_NUMBERING_BASE = 1;

/** Inclusive lowest valid socket id. */
export const NP_SOCKET_ID_MIN = 1;

/** Inclusive highest valid socket id. */
export const NP_SOCKET_ID_MAX = 80;

/**
 * SCAN-MEASURED geometry the lattice sits on (NP-HEX-ZM-001 §3.4). Two Scaniverse
 * LiDAR scans of the reference helmet interior replaced the earlier
 * ellipsoid-from-envelope idealization: the arcs, rim height and vault area are
 * measured off the real interior surface, and the row widths are counted whole
 * tiles on it. PROVISIONAL — pending REG-1 (10-20 registration vs shell CAD) and
 * ACT-1 (active-surface boundary). Rows sit at rowPitchMm along sagittalArcMm;
 * widths must alternate parity or the tiles overlap.
 */
export const NP_TILE_GEOMETRY = {
  moduleWidthMm: 40,
  /** Nasion->inion over-vertex arc, mm — scan-measured. */
  sagittalArcMm: 465,
  /** Ear-to-ear over-vertex arc at the widest station, mm — scan-measured. */
  coronalArcMm: 419,
  /** Rim->crown height, mm — scan-measured. */
  rimToCrownMm: 157,
  /** Front-to-back row spacing, mm — offset-hex pitch, = the measured 34.6 mm. */
  rowPitchMm: 34.64,
  hexAreaCm2: 13.8564,
  tiledAreaCm2: 1108.5,
  /** Full-mesh interior vault area, cm² — scan-measured containment bound. */
  vaultSurfaceCm2: 1370,
  /** Clearance between the helmet interior and the largest skull, mm (provisional floor). */
  standoffMm: 23,
  /** Largest head circumference the single adult SKU covers, mm. */
  headCircumferenceMm: 620,
  interiorLengthMm: 267,
  interiorBreadthMm: 229,
} as const;

/** Row widths front to back; used by the picker to lay out hex rows. */
export const NP_ROW_WIDTHS: readonly number[] = [3, 6, 7, 8, 9, 8, 9, 8, 7, 6, 5, 4];

const BY_ID = new Map<number, NPSocketGeometry>(NP_SOCKETS.map(s => [s.id, s]));

export function socketById(id: number): NPSocketGeometry | undefined {
  return BY_ID.get(id);
}

/** True when `id` names a real socket on this helmet. */
export function isValidSocketId(id: number): boolean {
  return BY_ID.has(id);
}
