// Generated by scripts/sync-socket-map.ts — DO NOT EDIT BY HAND.
// Regenerate with: bun scripts/sync-socket-map.ts
// Geometry is validated on every run against protocols/predefined/00-zones.npps.
// Scan-grounded v1 lattice (NP-HEX-ZM-001 §3.4) — PROVISIONAL pending REG-1 / ACT-1.
// x/y are PROVISIONAL unit-hex lattice coordinates for layout only, not mm.

export interface NPSocketGeometry {
  /** 1-based socket id, matching the `sockets:` lists in .npps zone files. */
  id: number;
  row: number;
  col: number;
  /** Provisional unit-hex lattice coordinates — layout only, not millimetres. */
  x: number;
  y: number;
  /**
   * Position in 3-space, MILLIMETRES, aircraft body axes, origin at the centre
   * of the ellipsoid the helmet is a partial shell of:
   *   +x forward (toward the face), +y right, +z down.
   * The vault has negative z; the crown sits at z = -157.
   *
   * There is deliberately no lobe and no side here. A socket's anatomical
   * meaning is its ZONE MEMBERSHIP, authored in
   * protocols/predefined/00-zones.npps — not a property of the hardware.
   */
  xMm: number;
  yMm: number;
  zMm: number;
}

/** Semi-axes of the modelled ellipsoid, mm (fore/aft, lateral, vertical). */
export const NP_ELLIPSOID_SEMI_AXES_MM = {
  foreAft: 133.5,
  lateral: 114.5,
  vertical: 157,
} as const;

/** Every socket in the helmet, ordered by id. */
export const NP_SOCKETS: readonly NPSocketGeometry[] = [
  { id: 1, row: 0, col: 0, x: -1, y: 0, xMm: 129.54, yMm: -26.32, zMm: -11.76 },
  { id: 2, row: 0, col: 1, x: 0, y: 0, xMm: 129.54, yMm: 0, zMm: -37.96 },
  { id: 3, row: 0, col: 2, x: 1, y: 0, xMm: 129.54, yMm: 26.32, zMm: -11.76 },
  { id: 4, row: 1, col: 0, x: -2.5, y: 0.866, xMm: 119.12, yMm: -51.7, zMm: 0 },
  { id: 5, row: 1, col: 1, x: -1.5, y: 0.866, xMm: 119.12, yMm: -43.81, zMm: -37.64 },
  { id: 6, row: 1, col: 2, x: -0.5, y: 0.866, xMm: 119.12, yMm: -18.59, zMm: -66.15 },
  { id: 7, row: 1, col: 3, x: 0.5, y: 0.866, xMm: 119.12, yMm: 18.59, zMm: -66.15 },
  { id: 8, row: 1, col: 4, x: 1.5, y: 0.866, xMm: 119.12, yMm: 43.81, zMm: -37.64 },
  { id: 9, row: 1, col: 5, x: 2.5, y: 0.866, xMm: 119.12, yMm: 51.7, zMm: 0 },
  { id: 10, row: 2, col: 0, x: -3, y: 1.7321, xMm: 102.21, yMm: -72.48, zMm: -17.97 },
  { id: 11, row: 2, col: 1, x: -2, y: 1.7321, xMm: 102.21, yMm: -61.22, zMm: -56.17 },
  { id: 12, row: 2, col: 2, x: -1, y: 1.7321, xMm: 102.21, yMm: -36.84, zMm: -87.46 },
  { id: 13, row: 2, col: 3, x: 0, y: 1.7321, xMm: 102.21, yMm: 0, zMm: -101 },
  { id: 14, row: 2, col: 4, x: 1, y: 1.7321, xMm: 102.21, yMm: 36.84, zMm: -87.46 },
  { id: 15, row: 2, col: 5, x: 2, y: 1.7321, xMm: 102.21, yMm: 61.22, zMm: -56.17 },
  { id: 16, row: 2, col: 6, x: 3, y: 1.7321, xMm: 102.21, yMm: 72.48, zMm: -17.97 },
  { id: 17, row: 3, col: 0, x: -3.5, y: 2.5981, xMm: 79, yMm: -89.16, zMm: -32.74 },
  { id: 18, row: 3, col: 1, x: -2.5, y: 2.5981, xMm: 79, yMm: -76.6, zMm: -70.6 },
  { id: 19, row: 3, col: 2, x: -1.5, y: 2.5981, xMm: 79, yMm: -53.56, zMm: -103.06 },
  { id: 20, row: 3, col: 3, x: -0.5, y: 2.5981, xMm: 79, yMm: -19.71, zMm: -123.64 },
  { id: 21, row: 3, col: 4, x: 0.5, y: 2.5981, xMm: 79, yMm: 19.71, zMm: -123.64 },
  { id: 22, row: 3, col: 5, x: 1.5, y: 2.5981, xMm: 79, yMm: 53.56, zMm: -103.06 },
  { id: 23, row: 3, col: 6, x: 2.5, y: 2.5981, xMm: 79, yMm: 76.6, zMm: -70.6 },
  { id: 24, row: 3, col: 7, x: 3.5, y: 2.5981, xMm: 79, yMm: 89.16, zMm: -32.74 },
  { id: 25, row: 4, col: 0, x: -4, y: 3.4641, xMm: 50.17, yMm: -102.31, zMm: -38.57 },
  { id: 26, row: 4, col: 1, x: -3, y: 3.4641, xMm: 50.17, yMm: -90.21, zMm: -76.61 },
  { id: 27, row: 4, col: 2, x: -2, y: 3.4641, xMm: 50.17, yMm: -69.09, zMm: -110.42 },
  { id: 28, row: 4, col: 3, x: -1, y: 3.4641, xMm: 50.17, yMm: -38.36, zMm: -135.65 },
  { id: 29, row: 4, col: 4, x: 0, y: 3.4641, xMm: 50.17, yMm: 0, zMm: -145.49 },
  { id: 30, row: 4, col: 5, x: 1, y: 3.4641, xMm: 50.17, yMm: 38.36, zMm: -135.65 },
  { id: 31, row: 4, col: 6, x: 2, y: 3.4641, xMm: 50.17, yMm: 69.09, zMm: -110.42 },
  { id: 32, row: 4, col: 7, x: 3, y: 3.4641, xMm: 50.17, yMm: 90.21, zMm: -76.61 },
  { id: 33, row: 4, col: 8, x: 4, y: 3.4641, xMm: 50.17, yMm: 102.31, zMm: -38.57 },
  { id: 34, row: 5, col: 0, x: -3.5, y: 4.3301, xMm: 17.23, yMm: -100.95, zMm: -71.26 },
  { id: 35, row: 5, col: 1, x: -2.5, y: 4.3301, xMm: 17.23, yMm: -82.67, zMm: -106.73 },
  { id: 36, row: 5, col: 2, x: -1.5, y: 4.3301, xMm: 17.23, yMm: -55.48, zMm: -135.84 },
  { id: 37, row: 5, col: 3, x: -0.5, y: 4.3301, xMm: 17.23, yMm: -19.81, zMm: -153.3 },
  { id: 38, row: 5, col: 4, x: 0.5, y: 4.3301, xMm: 17.23, yMm: 19.81, zMm: -153.3 },
  { id: 39, row: 5, col: 5, x: 1.5, y: 4.3301, xMm: 17.23, yMm: 55.48, zMm: -135.84 },
  { id: 40, row: 5, col: 6, x: 2.5, y: 4.3301, xMm: 17.23, yMm: 82.67, zMm: -106.73 },
  { id: 41, row: 5, col: 7, x: 3.5, y: 4.3301, xMm: 17.23, yMm: 100.95, zMm: -71.26 },
  { id: 42, row: 6, col: 0, x: -4, y: 5.1962, xMm: -17.23, yMm: -106.97, zMm: -52.2 },
  { id: 43, row: 6, col: 1, x: -3, y: 5.1962, xMm: -17.23, yMm: -92.88, zMm: -89.55 },
  { id: 44, row: 6, col: 2, x: -2, y: 5.1962, xMm: -17.23, yMm: -70.21, zMm: -122.35 },
  { id: 45, row: 6, col: 3, x: -1, y: 5.1962, xMm: -17.23, yMm: -38.55, zMm: -146.44 },
  { id: 46, row: 6, col: 4, x: 0, y: 5.1962, xMm: -17.23, yMm: 0, zMm: -155.69 },
  { id: 47, row: 6, col: 5, x: 1, y: 5.1962, xMm: -17.23, yMm: 38.55, zMm: -146.44 },
  { id: 48, row: 6, col: 6, x: 2, y: 5.1962, xMm: -17.23, yMm: 70.21, zMm: -122.35 },
  { id: 49, row: 6, col: 7, x: 3, y: 5.1962, xMm: -17.23, yMm: 92.88, zMm: -89.55 },
  { id: 50, row: 6, col: 8, x: 4, y: 5.1962, xMm: -17.23, yMm: 106.97, zMm: -52.2 },
  { id: 51, row: 7, col: 0, x: -3.5, y: 6.0622, xMm: -50.17, yMm: -97.33, zMm: -57.93 },
  { id: 52, row: 7, col: 1, x: -2.5, y: 6.0622, xMm: -50.17, yMm: -80.83, zMm: -94.25 },
  { id: 53, row: 7, col: 2, x: -1.5, y: 6.0622, xMm: -50.17, yMm: -54.91, zMm: -124.49 },
  { id: 54, row: 7, col: 3, x: -0.5, y: 6.0622, xMm: -50.17, yMm: -19.78, zMm: -142.94 },
  { id: 55, row: 7, col: 4, x: 0.5, y: 6.0622, xMm: -50.17, yMm: 19.78, zMm: -142.94 },
  { id: 56, row: 7, col: 5, x: 1.5, y: 6.0622, xMm: -50.17, yMm: 54.91, zMm: -124.49 },
  { id: 57, row: 7, col: 6, x: 2.5, y: 6.0622, xMm: -50.17, yMm: 80.83, zMm: -94.25 },
  { id: 58, row: 7, col: 7, x: 3.5, y: 6.0622, xMm: -50.17, yMm: 97.33, zMm: -57.93 },
  { id: 59, row: 8, col: 0, x: -3, y: 6.9282, xMm: -79, yMm: -84.12, zMm: -52.08 },
  { id: 60, row: 8, col: 1, x: -2, y: 6.9282, xMm: -79, yMm: -66.46, zMm: -87.82 },
  { id: 61, row: 8, col: 2, x: -1, y: 6.9282, xMm: -79, yMm: -37.88, zMm: -115.41 },
  { id: 62, row: 8, col: 3, x: 0, y: 6.9282, xMm: -79, yMm: 0, zMm: -126.56 },
  { id: 63, row: 8, col: 4, x: 1, y: 6.9282, xMm: -79, yMm: 37.88, zMm: -115.41 },
  { id: 64, row: 8, col: 5, x: 2, y: 6.9282, xMm: -79, yMm: 66.46, zMm: -87.82 },
  { id: 65, row: 8, col: 6, x: 3, y: 6.9282, xMm: -79, yMm: 84.12, zMm: -52.08 },
  { id: 66, row: 9, col: 0, x: -2.5, y: 7.7942, xMm: -102.21, yMm: -68.39, zMm: -37.52 },
  { id: 67, row: 9, col: 1, x: -1.5, y: 7.7942, xMm: -102.21, yMm: -50.77, zMm: -73.18 },
  { id: 68, row: 9, col: 2, x: -0.5, y: 7.7942, xMm: -102.21, yMm: -19.56, zMm: -97.38 },
  { id: 69, row: 9, col: 3, x: 0.5, y: 7.7942, xMm: -102.21, yMm: 19.56, zMm: -97.38 },
  { id: 70, row: 9, col: 4, x: 1.5, y: 7.7942, xMm: -102.21, yMm: 50.77, zMm: -73.18 },
  { id: 71, row: 9, col: 5, x: 2.5, y: 7.7942, xMm: -102.21, yMm: 68.39, zMm: -37.52 },
  { id: 72, row: 10, col: 0, x: -2, y: 8.6603, xMm: -119.12, yMm: -50.23, zMm: -16.79 },
  { id: 73, row: 10, col: 1, x: -1, y: 8.6603, xMm: -119.12, yMm: -34.32, zMm: -53.02 },
  { id: 74, row: 10, col: 2, x: 0, y: 8.6603, xMm: -119.12, yMm: 0, zMm: -70.89 },
  { id: 75, row: 10, col: 3, x: 1, y: 8.6603, xMm: -119.12, yMm: 34.32, zMm: -53.02 },
  { id: 76, row: 10, col: 4, x: 2, y: 8.6603, xMm: -119.12, yMm: 50.23, zMm: -16.79 },
  { id: 77, row: 11, col: 0, x: -1.5, y: 9.5263, xMm: -129.54, yMm: -27.68, zMm: 0 },
  { id: 78, row: 11, col: 1, x: -0.5, y: 9.5263, xMm: -129.54, yMm: -15.55, zMm: -31.4 },
  { id: 79, row: 11, col: 2, x: 0.5, y: 9.5263, xMm: -129.54, yMm: 15.55, zMm: -31.4 },
  { id: 80, row: 11, col: 3, x: 1.5, y: 9.5263, xMm: -129.54, yMm: 27.68, zMm: 0 },
];

export const NP_SOCKET_COUNT = 80;

/**
 * Socket ids are 1-based. This is the numbering base every consumer must honour
 * — .npps `sockets:` lists, the firmware major address, and the UI picker.
 */
export const NP_SOCKET_NUMBERING_BASE = 1;

/** Inclusive lowest valid socket id. */
export const NP_SOCKET_ID_MIN = 1;

/** Inclusive highest valid socket id. */
export const NP_SOCKET_ID_MAX = 80;

/**
 * SCAN-MEASURED geometry the lattice sits on (NP-HEX-ZM-001 §3.4). Two Scaniverse
 * LiDAR scans of the reference helmet interior replaced the earlier
 * ellipsoid-from-envelope idealization: the arcs, rim height and vault area are
 * measured off the real interior surface, and the row widths are counted whole
 * tiles on it. PROVISIONAL — pending REG-1 (10-20 registration vs shell CAD) and
 * ACT-1 (active-surface boundary). Rows sit at rowPitchMm along sagittalArcMm;
 * widths must alternate parity or the tiles overlap.
 */
export const NP_TILE_GEOMETRY = {
  moduleWidthMm: 40,
  /** Nasion->inion over-vertex arc, mm — scan-measured. */
  sagittalArcMm: 465,
  /** Ear-to-ear over-vertex arc at the widest station, mm — scan-measured. */
  coronalArcMm: 419,
  /** Rim->crown height, mm — scan-measured. */
  rimToCrownMm: 157,
  /** Front-to-back row spacing, mm — offset-hex pitch, = the measured 34.6 mm. */
  rowPitchMm: 34.64,
  hexAreaCm2: 13.8564,
  tiledAreaCm2: 1108.5,
  /** Full-mesh interior vault area, cm² — scan-measured containment bound. */
  vaultSurfaceCm2: 1370,
  /** Clearance between the helmet interior and the largest skull, mm (provisional floor). */
  standoffMm: 23,
  /** Largest head circumference the single adult SKU covers, mm. */
  headCircumferenceMm: 620,
  interiorLengthMm: 267,
  interiorBreadthMm: 229,
} as const;

/** Row widths front to back; used by the picker to lay out hex rows. */
export const NP_ROW_WIDTHS: readonly number[] = [3, 6, 7, 8, 9, 8, 9, 8, 7, 6, 5, 4];

const BY_ID = new Map<number, NPSocketGeometry>(NP_SOCKETS.map(s => [s.id, s]));

export function socketById(id: number): NPSocketGeometry | undefined {
  return BY_ID.get(id);
}

/** True when `id` names a real socket on this helmet. */
export function isValidSocketId(id: number): boolean {
  return BY_ID.has(id);
}
