// Generated by scripts/sync-socket-map.ts — DO NOT EDIT BY HAND.
// Regenerate with: bun scripts/sync-socket-map.ts
// Geometry is validated on every run against protocols/predefined/00-zones.npps.
// Scan-grounded v1 lattice (NP-HEX-ZM-001 §3.4) — PROVISIONAL pending REG-1 / ACT-1.
// x/y are PROVISIONAL unit-hex lattice coordinates for layout only, not mm.

export type NPLobe = 'frontal' | 'temporal' | 'parietal' | 'occipital';
export type NPSide = 'left' | 'right' | 'midline';

export interface NPSocketGeometry {
  /** 1-based socket id, matching the `sockets:` lists in .npps zone files. */
  id: number;
  lobe: NPLobe;
  /** `midline` sockets belong to BOTH hemisphere zones of their lobe. */
  side: NPSide;
  row: number;
  col: number;
  /** Provisional unit-hex lattice coordinates — layout only, not millimetres. */
  x: number;
  y: number;
}

/** Every socket in the helmet, ordered by id. */
export const NP_SOCKETS: readonly NPSocketGeometry[] = [
  { id: 1, lobe: 'frontal', side: 'left', row: 0, col: 0, x: -1, y: 0 },
  { id: 2, lobe: 'frontal', side: 'midline', row: 0, col: 1, x: 0, y: 0 },
  { id: 3, lobe: 'frontal', side: 'right', row: 0, col: 2, x: 1, y: 0 },
  { id: 4, lobe: 'frontal', side: 'left', row: 1, col: 0, x: -2.5, y: 0.866 },
  { id: 5, lobe: 'frontal', side: 'left', row: 1, col: 1, x: -1.5, y: 0.866 },
  { id: 6, lobe: 'frontal', side: 'left', row: 1, col: 2, x: -0.5, y: 0.866 },
  { id: 7, lobe: 'frontal', side: 'right', row: 1, col: 3, x: 0.5, y: 0.866 },
  { id: 8, lobe: 'frontal', side: 'right', row: 1, col: 4, x: 1.5, y: 0.866 },
  { id: 9, lobe: 'frontal', side: 'right', row: 1, col: 5, x: 2.5, y: 0.866 },
  { id: 10, lobe: 'frontal', side: 'left', row: 2, col: 0, x: -3, y: 1.7321 },
  { id: 11, lobe: 'frontal', side: 'left', row: 2, col: 1, x: -2, y: 1.7321 },
  { id: 12, lobe: 'frontal', side: 'left', row: 2, col: 2, x: -1, y: 1.7321 },
  { id: 13, lobe: 'frontal', side: 'midline', row: 2, col: 3, x: 0, y: 1.7321 },
  { id: 14, lobe: 'frontal', side: 'right', row: 2, col: 4, x: 1, y: 1.7321 },
  { id: 15, lobe: 'frontal', side: 'right', row: 2, col: 5, x: 2, y: 1.7321 },
  { id: 16, lobe: 'frontal', side: 'right', row: 2, col: 6, x: 3, y: 1.7321 },
  { id: 17, lobe: 'frontal', side: 'left', row: 3, col: 0, x: -3.5, y: 2.5981 },
  { id: 18, lobe: 'frontal', side: 'left', row: 3, col: 1, x: -2.5, y: 2.5981 },
  { id: 19, lobe: 'frontal', side: 'left', row: 3, col: 2, x: -1.5, y: 2.5981 },
  { id: 20, lobe: 'frontal', side: 'left', row: 3, col: 3, x: -0.5, y: 2.5981 },
  { id: 21, lobe: 'frontal', side: 'right', row: 3, col: 4, x: 0.5, y: 2.5981 },
  { id: 22, lobe: 'frontal', side: 'right', row: 3, col: 5, x: 1.5, y: 2.5981 },
  { id: 23, lobe: 'frontal', side: 'right', row: 3, col: 6, x: 2.5, y: 2.5981 },
  { id: 24, lobe: 'frontal', side: 'right', row: 3, col: 7, x: 3.5, y: 2.5981 },
  { id: 25, lobe: 'temporal', side: 'left', row: 4, col: 0, x: -4, y: 3.4641 },
  { id: 26, lobe: 'frontal', side: 'left', row: 4, col: 1, x: -3, y: 3.4641 },
  { id: 27, lobe: 'frontal', side: 'left', row: 4, col: 2, x: -2, y: 3.4641 },
  { id: 28, lobe: 'frontal', side: 'left', row: 4, col: 3, x: -1, y: 3.4641 },
  { id: 29, lobe: 'frontal', side: 'midline', row: 4, col: 4, x: 0, y: 3.4641 },
  { id: 30, lobe: 'frontal', side: 'right', row: 4, col: 5, x: 1, y: 3.4641 },
  { id: 31, lobe: 'frontal', side: 'right', row: 4, col: 6, x: 2, y: 3.4641 },
  { id: 32, lobe: 'frontal', side: 'right', row: 4, col: 7, x: 3, y: 3.4641 },
  { id: 33, lobe: 'temporal', side: 'right', row: 4, col: 8, x: 4, y: 3.4641 },
  { id: 34, lobe: 'temporal', side: 'left', row: 5, col: 0, x: -3.5, y: 4.3301 },
  { id: 35, lobe: 'frontal', side: 'left', row: 5, col: 1, x: -2.5, y: 4.3301 },
  { id: 36, lobe: 'frontal', side: 'left', row: 5, col: 2, x: -1.5, y: 4.3301 },
  { id: 37, lobe: 'frontal', side: 'left', row: 5, col: 3, x: -0.5, y: 4.3301 },
  { id: 38, lobe: 'frontal', side: 'right', row: 5, col: 4, x: 0.5, y: 4.3301 },
  { id: 39, lobe: 'frontal', side: 'right', row: 5, col: 5, x: 1.5, y: 4.3301 },
  { id: 40, lobe: 'frontal', side: 'right', row: 5, col: 6, x: 2.5, y: 4.3301 },
  { id: 41, lobe: 'temporal', side: 'right', row: 5, col: 7, x: 3.5, y: 4.3301 },
  { id: 42, lobe: 'temporal', side: 'left', row: 6, col: 0, x: -4, y: 5.1962 },
  { id: 43, lobe: 'parietal', side: 'left', row: 6, col: 1, x: -3, y: 5.1962 },
  { id: 44, lobe: 'parietal', side: 'left', row: 6, col: 2, x: -2, y: 5.1962 },
  { id: 45, lobe: 'parietal', side: 'left', row: 6, col: 3, x: -1, y: 5.1962 },
  { id: 46, lobe: 'parietal', side: 'midline', row: 6, col: 4, x: 0, y: 5.1962 },
  { id: 47, lobe: 'parietal', side: 'right', row: 6, col: 5, x: 1, y: 5.1962 },
  { id: 48, lobe: 'parietal', side: 'right', row: 6, col: 6, x: 2, y: 5.1962 },
  { id: 49, lobe: 'parietal', side: 'right', row: 6, col: 7, x: 3, y: 5.1962 },
  { id: 50, lobe: 'temporal', side: 'right', row: 6, col: 8, x: 4, y: 5.1962 },
  { id: 51, lobe: 'temporal', side: 'left', row: 7, col: 0, x: -3.5, y: 6.0622 },
  { id: 52, lobe: 'parietal', side: 'left', row: 7, col: 1, x: -2.5, y: 6.0622 },
  { id: 53, lobe: 'parietal', side: 'left', row: 7, col: 2, x: -1.5, y: 6.0622 },
  { id: 54, lobe: 'parietal', side: 'left', row: 7, col: 3, x: -0.5, y: 6.0622 },
  { id: 55, lobe: 'parietal', side: 'right', row: 7, col: 4, x: 0.5, y: 6.0622 },
  { id: 56, lobe: 'parietal', side: 'right', row: 7, col: 5, x: 1.5, y: 6.0622 },
  { id: 57, lobe: 'parietal', side: 'right', row: 7, col: 6, x: 2.5, y: 6.0622 },
  { id: 58, lobe: 'temporal', side: 'right', row: 7, col: 7, x: 3.5, y: 6.0622 },
  { id: 59, lobe: 'temporal', side: 'left', row: 8, col: 0, x: -3, y: 6.9282 },
  { id: 60, lobe: 'parietal', side: 'left', row: 8, col: 1, x: -2, y: 6.9282 },
  { id: 61, lobe: 'parietal', side: 'left', row: 8, col: 2, x: -1, y: 6.9282 },
  { id: 62, lobe: 'parietal', side: 'midline', row: 8, col: 3, x: 0, y: 6.9282 },
  { id: 63, lobe: 'parietal', side: 'right', row: 8, col: 4, x: 1, y: 6.9282 },
  { id: 64, lobe: 'parietal', side: 'right', row: 8, col: 5, x: 2, y: 6.9282 },
  { id: 65, lobe: 'temporal', side: 'right', row: 8, col: 6, x: 3, y: 6.9282 },
  { id: 66, lobe: 'parietal', side: 'left', row: 9, col: 0, x: -2.5, y: 7.7942 },
  { id: 67, lobe: 'parietal', side: 'left', row: 9, col: 1, x: -1.5, y: 7.7942 },
  { id: 68, lobe: 'parietal', side: 'left', row: 9, col: 2, x: -0.5, y: 7.7942 },
  { id: 69, lobe: 'parietal', side: 'right', row: 9, col: 3, x: 0.5, y: 7.7942 },
  { id: 70, lobe: 'parietal', side: 'right', row: 9, col: 4, x: 1.5, y: 7.7942 },
  { id: 71, lobe: 'parietal', side: 'right', row: 9, col: 5, x: 2.5, y: 7.7942 },
  { id: 72, lobe: 'occipital', side: 'left', row: 10, col: 0, x: -2, y: 8.6603 },
  { id: 73, lobe: 'occipital', side: 'left', row: 10, col: 1, x: -1, y: 8.6603 },
  { id: 74, lobe: 'occipital', side: 'midline', row: 10, col: 2, x: 0, y: 8.6603 },
  { id: 75, lobe: 'occipital', side: 'right', row: 10, col: 3, x: 1, y: 8.6603 },
  { id: 76, lobe: 'occipital', side: 'right', row: 10, col: 4, x: 2, y: 8.6603 },
  { id: 77, lobe: 'occipital', side: 'left', row: 11, col: 0, x: -1.5, y: 9.5263 },
  { id: 78, lobe: 'occipital', side: 'left', row: 11, col: 1, x: -0.5, y: 9.5263 },
  { id: 79, lobe: 'occipital', side: 'right', row: 11, col: 2, x: 0.5, y: 9.5263 },
  { id: 80, lobe: 'occipital', side: 'right', row: 11, col: 3, x: 1.5, y: 9.5263 },
];

export const NP_SOCKET_COUNT = 80;

/**
 * Socket ids are 1-based. This is the numbering base every consumer must honour
 * — .npps `sockets:` lists, the firmware major address, and the UI picker.
 */
export const NP_SOCKET_NUMBERING_BASE = 1;

/** Inclusive lowest valid socket id. */
export const NP_SOCKET_ID_MIN = 1;

/** Inclusive highest valid socket id. */
export const NP_SOCKET_ID_MAX = 80;

/**
 * SCAN-MEASURED geometry the lattice sits on (NP-HEX-ZM-001 §3.4). Two Scaniverse
 * LiDAR scans of the reference helmet interior replaced the earlier
 * ellipsoid-from-envelope idealization: the arcs, rim height and vault area are
 * measured off the real interior surface, and the row widths are counted whole
 * tiles on it. PROVISIONAL — pending REG-1 (10-20 registration vs shell CAD) and
 * ACT-1 (active-surface boundary). Rows sit at rowPitchMm along sagittalArcMm;
 * widths must alternate parity or the tiles overlap.
 */
export const NP_TILE_GEOMETRY = {
  moduleWidthMm: 40,
  /** Nasion->inion over-vertex arc, mm — scan-measured. */
  sagittalArcMm: 465,
  /** Ear-to-ear over-vertex arc at the widest station, mm — scan-measured. */
  coronalArcMm: 419,
  /** Rim->crown height, mm — scan-measured. */
  rimToCrownMm: 157,
  /** Front-to-back row spacing, mm — offset-hex pitch, = the measured 34.6 mm. */
  rowPitchMm: 34.64,
  hexAreaCm2: 13.8564,
  tiledAreaCm2: 1108.5,
  /** Full-mesh interior vault area, cm² — scan-measured containment bound. */
  vaultSurfaceCm2: 1370,
  /** Clearance between the helmet interior and the largest skull, mm (provisional floor). */
  standoffMm: 23,
  /** Largest head circumference the single adult SKU covers, mm. */
  headCircumferenceMm: 620,
  interiorLengthMm: 267,
  interiorBreadthMm: 229,
} as const;

/** Row widths front to back; used by the picker to lay out hex rows. */
export const NP_ROW_WIDTHS: readonly number[] = [3, 6, 7, 8, 9, 8, 9, 8, 7, 6, 5, 4];

const BY_ID = new Map<number, NPSocketGeometry>(NP_SOCKETS.map(s => [s.id, s]));

export function socketById(id: number): NPSocketGeometry | undefined {
  return BY_ID.get(id);
}

/** True when `id` names a real socket on this helmet. */
export function isValidSocketId(id: number): boolean {
  return BY_ID.has(id);
}
