#!/usr/bin/env bun
/**
 * build-simulator-runtime.ts — bundle the simulator's NPPS runtime to plain JS.
 *
 * The simulator is plain ES modules and cannot import TypeScript, so the real
 * parser (app/web/src/lib/nppsParser.ts) plus simulator/src/npps-runtime.ts are
 * bundled into simulator/js/vendor/npps-runtime.js.
 *
 * **What this bundles is CODE. It bundles no protocol content whatsoever.**
 * That distinction is the whole point: NP-NPPS-REF-001 §1.6 (*No build-time
 * cache of protocol content*) prohibits shipping a parsed copy of the .npps
 * library, because a .npps file can change after the build and the cache would
 * then be read in place of the edit — silently, leaving an author with no way to
 * tell why their change is not showing up anywhere. A parser is not a cache: it
 * has no opinion about what the files say, and it reads them when the simulator
 * runs.
 *
 * Run after changing simulator/src/ or the web parser:
 *   bun scripts/build-simulator-runtime.ts
 * Pass --check to fail without writing when the bundle is stale (CI).
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';

const ROOT = join(import.meta.dir, '..');
const ENTRY = join(ROOT, 'simulator', 'src', 'npps-runtime.ts');
const OUT = join(ROOT, 'simulator', 'js', 'vendor', 'npps-runtime.js');

const BANNER = `// GENERATED by scripts/build-simulator-runtime.ts — DO NOT EDIT BY HAND.
// A bundle of simulator/src/npps-runtime.ts + app/web/src/lib/nppsParser.ts.
//
// This file contains CODE ONLY. It holds no zones, no conditions and no
// protocols: those are fetched from protocols/predefined/ when the simulator
// loads, per NP-NPPS-REF-001 §1.6 (No build-time cache of protocol content).
// Regenerate with: bun scripts/build-simulator-runtime.ts
`;

const check = process.argv.includes('--check');

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: 'browser',
  format: 'esm',
  minify: false,
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error('simulator runtime bundle failed');
}

const built = BANNER + (await result.outputs[0]!.text());

// A parsed .npps definition must never end up inside the bundle. The canaries
// are the stable UUIDs the shipped library declares — read from the files
// themselves, so the check maintains itself as the library grows.
//
// Deliberately NOT zone NAMES: the parser quotes several in its own error
// messages ('e.g. zones: ["Frontal Left", ...]'), which is code doing its job.
// An `id:` UUID appears only in the data, so finding one here means the build
// started baking content in — §1.6 violated by the build rather than the source.
const ID_PATTERN = /\bid\s*:\s*"([0-9a-fA-F-]{36})"/g;
const canaries = new Set<string>();
for (const file of ['00-zones.npps', '00-conditions.npps']) {
  const source = readFileSync(join(ROOT, 'protocols', 'predefined', file), 'utf8');
  for (const m of source.matchAll(ID_PATTERN)) canaries.add(m[1]!);
}
if (canaries.size === 0) {
  throw new Error('no canary ids found in the shipped library — the content check would be vacuous');
}
for (const canary of canaries) {
  if (built.includes(canary)) {
    throw new Error(
      `bundle contains protocol content (definition id ${canary}) — it must contain ` +
      'code only. See NP-NPPS-REF-001 §1.6.'
    );
  }
}

if (check) {
  const existing = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (existing !== built) {
    console.error(`STALE: ${OUT} does not match a fresh build.`);
    console.error('Run: bun scripts/build-simulator-runtime.ts');
    process.exit(1);
  }
  console.log('simulator runtime bundle is up to date.');
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, built);
  console.log(`Wrote ${OUT} (${(built.length / 1024).toFixed(1)} kB, code only)`);
}
