#!/usr/bin/env bun
/**
 * build-simulator-runtime.ts — bundle the simulator's NPPS runtime to plain JS.
 *
 * The simulator is plain ES modules and cannot import TypeScript, so the real
 * parser (app/web/src/lib/nppsParser.ts) plus simulator/src/npps-runtime.ts are
 * bundled into simulator/js/vendor/npps-runtime.js.
 *
 * **What this bundles is CODE. It bundles no protocol content whatsoever.**
 * That distinction is the whole point: NP-NPPS-REF-001 §1.6 (*No build-time
 * cache of protocol content*) prohibits shipping a parsed copy of the .npps
 * library, because a .npps file can change after the build and the cache would
 * then be read in place of the edit — silently, leaving an author with no way to
 * tell why their change is not showing up anywhere. A parser is not a cache: it
 * has no opinion about what the files say, and it reads them when the simulator
 * runs.
 *
 * Run after changing simulator/src/ or the web parser:
 *   bun scripts/build-simulator-runtime.ts
 * Pass --check to fail without writing when the bundle is stale (CI).
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'fs';
import { createHash } from 'crypto';
import { dirname, join, resolve } from 'path';

const ROOT = join(import.meta.dir, '..');
const ENTRY = join(ROOT, 'simulator', 'src', 'npps-runtime.ts');
const OUT = join(ROOT, 'simulator', 'js', 'vendor', 'npps-runtime.js');

const FINGERPRINT_TAG = '// sources-sha256: ';

function banner(fingerprint: string): string {
  return `// GENERATED by scripts/build-simulator-runtime.ts — DO NOT EDIT BY HAND.
// A bundle of simulator/src/npps-runtime.ts + app/web/src/lib/nppsParser.ts.
//
// This file contains CODE ONLY. It holds no zones, no conditions and no
// protocols: those are fetched from protocols/predefined/ when the simulator
// loads, per NP-NPPS-REF-001 §1.6 (No build-time cache of protocol content).
// Regenerate with: bun scripts/build-simulator-runtime.ts
${FINGERPRINT_TAG}${fingerprint}
`;
}

/**
 * Every TypeScript source that goes into the bundle, found by walking relative
 * imports from the entry. The graph is entirely relative — no npm dependency
 * reaches this bundle — so a resolver this small is complete rather than
 * approximate. It throws on an unresolvable relative import rather than
 * silently dropping a file, because a dropped file would weaken the
 * fingerprint below without anything failing.
 */
function sourceGraph(entry: string): string[] {
  const seen = new Set<string>();
  const queue = [entry];
  const importRe = /(?:^|\n)\s*(?:import|export)[\s\S]*?from\s+['"](\.[^'"]+)['"]/g;

  while (queue.length > 0) {
    const file = queue.pop()!;
    if (seen.has(file)) continue;
    seen.add(file);

    const text = readFileSync(file, 'utf8');
    for (const m of text.matchAll(importRe)) {
      const spec = m[1]!;
      const base = resolve(dirname(file), spec);
      const candidates = [base, `${base}.ts`, `${base}.tsx`, join(base, 'index.ts')];
      const resolved = candidates.find(c => existsSync(c) && !c.endsWith('/'));
      if (!resolved) {
        throw new Error(`cannot resolve '${spec}' from ${file} — the fingerprint would be incomplete`);
      }
      if (!seen.has(resolved)) queue.push(resolved);
    }
  }
  return [...seen].sort();
}

/** SHA-256 over every source path and its contents. */
function fingerprintSources(files: string[]): string {
  const hash = createHash('sha256');
  for (const file of files) {
    hash.update(file.slice(ROOT.length));
    hash.update('\0');
    hash.update(readFileSync(file));
    hash.update('\0');
  }
  return hash.digest('hex');
}

/**
 * A parsed .npps definition must never end up inside the bundle. The canaries
 * are the stable UUIDs the shipped library declares — read from the files
 * themselves, so the check maintains itself as the library grows.
 *
 * Deliberately NOT zone NAMES: the parser quotes several in its own error
 * messages ('e.g. zones: ["Frontal Left", ...]'), which is code doing its job.
 * An `id:` UUID appears only in the data, so finding one here means the build
 * started baking content in — §1.6 violated by the build rather than the source.
 */
function assertNoProtocolContent(bundle: string): void {
  const ID_PATTERN = /\bid\s*:\s*"([0-9a-fA-F-]{36})"/g;
  const canaries = new Set<string>();
  for (const file of ['00-zones.npps', '00-conditions.npps']) {
    const source = readFileSync(join(ROOT, 'protocols', 'predefined', file), 'utf8');
    for (const m of source.matchAll(ID_PATTERN)) canaries.add(m[1]!);
  }
  if (canaries.size === 0) {
    throw new Error('no canary ids found in the shipped library — the content check would be vacuous');
  }
  for (const canary of canaries) {
    if (bundle.includes(canary)) {
      throw new Error(
        `bundle contains protocol content (definition id ${canary}) — it must contain ` +
        'code only. See NP-NPPS-REF-001 §1.6.'
      );
    }
  }
}

const check = process.argv.includes('--check');
const fingerprint = fingerprintSources(sourceGraph(ENTRY));

// ── Check mode ────────────────────────────────────────────────────────────────
//
// Deliberately does NOT rebuild and diff. Bundler output is not byte-stable
// across Bun versions — CI resolves `bun-version: latest` while a contributor
// has whatever they installed — so a byte comparison fails on a version bump
// with a message blaming the committed file, which is not the thing that
// changed. What this check actually needs to catch is "someone edited the
// parser or the runtime and forgot to rebuild", and the source fingerprint
// answers exactly that, at any bundler version.
if (check) {
  if (!existsSync(OUT)) {
    console.error(`MISSING: ${OUT}\nRun: bun scripts/build-simulator-runtime.ts`);
    process.exit(1);
  }
  const committed = readFileSync(OUT, 'utf8');

  // The committed artefact is the one that ships, so it is the one worth
  // checking for baked-in protocol content.
  assertNoProtocolContent(committed);

  const line = committed.split('\n').find(l => l.startsWith(FINGERPRINT_TAG));
  const recorded = line?.slice(FINGERPRINT_TAG.length).trim();
  if (!recorded) {
    console.error(`${OUT} carries no source fingerprint.\nRun: bun scripts/build-simulator-runtime.ts`);
    process.exit(1);
  }
  if (recorded !== fingerprint) {
    console.error(
      `STALE: ${OUT} was built from different sources.\n` +
      `  recorded: ${recorded}\n  current:  ${fingerprint}\n` +
      'Run: bun scripts/build-simulator-runtime.ts'
    );
    process.exit(1);
  }
  console.log(`simulator runtime bundle is up to date (sources ${fingerprint.slice(0, 12)}…).`);
  process.exit(0);
}

// ── Build ─────────────────────────────────────────────────────────────────────

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: 'browser',
  format: 'esm',
  minify: false,
});

if (!result.success) {
  for (const log of result.logs) console.error(log);
  throw new Error('simulator runtime bundle failed');
}

const built = banner(fingerprint) + (await result.outputs[0]!.text());
assertNoProtocolContent(built);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, built);
console.log(`Wrote ${OUT} (${(built.length / 1024).toFixed(1)} kB, code only)`);
console.log(`  sources ${fingerprint.slice(0, 12)}…`);
