#!/usr/bin/env bun
/**
 * generate-simulator-data.ts — the simulator's socket LATTICE.
 *
 * Emits simulator/js/sockets.generated.js: the 80 hex-tile positions projected
 * onto the dome for 3D placement.
 *
 * **This script emits no protocol content.** It used to also bake the parsed
 * .npps library into simulator/js/protocols.generated.js and a ZONES export
 * here. NP-NPPS-REF-001 §1.6 (*No build-time cache of protocol content*)
 * prohibits that, and the simulator had already shown why: its committed output
 * still carried the `side` field ZONE-1 removed a month earlier, so the
 * simulator quietly showed a lattice the repository had stopped describing, and
 * anyone editing a .npps file had no way to tell why their change was not
 * showing up anywhere. Zones, conditions and protocols are now fetched and
 * parsed when the simulator loads, by simulator/src/npps-runtime.ts.
 *
 * The lattice stays generated because it is not protocol content: it is
 * hardware, derived from hardware/np_socket_map.json (generated by
 * scripts/sync-socket-map.ts from the scan-grounded lattice, NP-HEX-ZM-001
 * §3.4 — PROVISIONAL pending REG-1/ACT-1), and it changes only on an
 * inner-bowl re-tool, which is a rebuild in any case. This script does not
 * re-derive socket geometry; it only projects the documented row/col lattice
 * coordinates onto the dome (see toSpherical() below).
 *
 * Regenerate with: bun scripts/generate-simulator-data.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SOCKET_MAP_PATH = join(ROOT, 'hardware/np_socket_map.json');
const OUT_SOCKETS = join(ROOT, 'simulator/js/sockets.generated.js');

// direction — a standard azimuthal-equidistant projection from the crown point.

function toSpherical(x: number, y: number, yCrown: number, angularScale: number) {
  const lateralUnits = -x;              // sign-flipped: anatomical LEFT -> +X (mirrored clinical view, matches EEG_POSITIONS convention in helmet.js)
  const forwardUnits = yCrown - y;      // +front (toward Fp/row0) .. -back (toward O/row11)

  const rho = Math.sqrt(lateralUnits * lateralUnits + forwardUnits * forwardUnits); // real lattice units (1 unit = 40mm)
  const theta = rho * angularScale;
  const phi = Math.atan2(lateralUnits, forwardUnits);

  return { phi, theta, rho };
}

// A fixed-size hexagon stamped at each tile's projected CENTER can't tile
// correctly: this projection's tangential distortion (theta/sin(theta), the
// standard azimuthal-equidistant distortion factor) grows with distance from
// the crown pole, so no single hex size is simultaneously correct for tiles
// near the crown and tiles out at the temporal/occipital rim — the result was
// visibly overlapping tiles with z-fighting "bites" out of them.
//
// The actual fix: hexagon CORNERS in the real 2D lattice are shared between
// neighboring tiles by construction (it's a proper hex tiling — verified
// nearest-neighbor spacing is exactly 1.0 unit everywhere, see toSpherical's
// header comment). So instead of projecting each tile's CENTER and stamping a
// locally-flat hexagon there, project each tile's 6 CORNER points individually
// through the same toSpherical(). Two adjacent tiles' shared lattice corner is
// then the exact same (x,y) input, so it projects to the exact same (phi,
// theta) output — the tiles share that vertex exactly, no matter how much the
// projection distorts elsewhere. This is what makes it a true tiling instead
// of an approximation.
//
// Standard "pointy-top" hex geometry (points up/down, flat vertical edges
// left/right — confirmed against the data: same-row neighbor spacing (pure
// horizontal) equals the nearest-neighbor distance, 1.0 unit; row-to-row
// spacing of 0.8660254 = 1.5 * circumradius confirms it). Circumradius in
// lattice units for flat-to-flat width 1.0: R = 1/sqrt(3).
const HEX_CIRCUMRADIUS_UNITS = 1 / Math.sqrt(3);

function hexCornerOffsets(): Array<[number, number]> {
  const offsets: Array<[number, number]> = [];
  for (let i = 0; i < 6; i++) {
    const a = (Math.PI / 3) * i + Math.PI / 6; // 30°, 90°, 150°, ... — pointy-top
    offsets.push([HEX_CIRCUMRADIUS_UNITS * Math.cos(a), HEX_CIRCUMRADIUS_UNITS * Math.sin(a)]);
  }
  return offsets;
}

function generateSockets() {
  const socketMap = JSON.parse(readFileSync(SOCKET_MAP_PATH, 'utf8'));
  const rows: number[] = socketMap.rowWidths;
  const rowCount = rows.length;
  const THETA_MAX = 0.58 * Math.PI; // stays within the shell's 0.62π dome coverage (helmet.js SHELL)

  // Row-to-row y advances by sqrt(3)/2 per row (standard offset-hex packing,
  // confirmed against the actual data: row1.y/row0.y step = 0.8660254). The
  // crown sits at the mid-row (~50% central-sulcus landmark), not a real row.
  const HEX_ROW_Y_STEP = Math.sqrt(3) / 2;
  const CROWN_ROW = (rowCount - 1) / 2; // 5.5 for 12 rows
  const yCrown = CROWN_ROW * HEX_ROW_Y_STEP;

  // Single global angular scale (radians per lattice unit), calibrated so the
  // single farthest-from-crown socket CENTER lands exactly at THETA_MAX.
  // (Corners of that outermost tile land slightly beyond THETA_MAX — harmless,
  // the shell dome's own polar cutoff has margin above THETA_MAX for this.)
  const rhosRaw = socketMap.sockets.map((s: any) => Math.hypot(-s.x, yCrown - s.y));
  const rhoMax = Math.max(...rhosRaw);
  const angularScale = THETA_MAX / rhoMax;

  const cornerOffsets = hexCornerOffsets();

  let thetaMax = 0;
  const sockets = socketMap.sockets.map((s: any) => {
    const { phi, theta } = toSpherical(s.x, s.y, yCrown, angularScale);
    thetaMax = Math.max(thetaMax, theta);
    const corners = cornerOffsets.map(([dx, dy]) => {
      const c = toSpherical(s.x + dx, s.y + dy, yCrown, angularScale);
      return { phi: c.phi, theta: c.theta };
    });
    return { id: s.id, side: s.side, row: s.row, phi, theta, corners };
  });
  console.log(`  Sockets: ${sockets.length}, max theta = ${(thetaMax / Math.PI).toFixed(3)}π`);
  return { sockets };
}

// ── Emit ──────────────────────────────────────────────────────────────────────

function emitSocketsModule(sockets: any[]) {
  const banner = `// GENERATED by scripts/generate-simulator-data.ts — DO NOT EDIT BY HAND.
// Source of truth: hardware/np_socket_map.json (socket geometry).
// Regenerate with: bun scripts/generate-simulator-data.ts
// Socket lattice is PROVISIONAL v1 (NP-HEX-ZM-001 §3.4) pending gates REG-1/ACT-1.
//
// The LATTICE ONLY — no zones, no protocols. Those are fetched and parsed from
// protocols/predefined/ when the simulator loads (simulator/src/npps-runtime.ts),
// per NP-NPPS-REF-001 §1.6 (No build-time cache of protocol content).
`;
  const body = `${banner}
/**
 * All 80 hex-tile sockets, with 3D dome position (phi, theta — see
 * helmet.js _sph()) plus each tile's 6 hex corners, individually projected
 * through the same function as the center. Neighboring tiles share literal
 * lattice corner coordinates (it's a proper hex tiling — see toSpherical()'s
 * header comment in scripts/generate-simulator-data.ts), so their shared
 * corner always projects to the identical (phi, theta) — that's what makes
 * helmet.js's rendered tiles actually share edges instead of a fixed-size
 * hexagon approximating each tile's projected center.
 */
export const SOCKETS = ${JSON.stringify(sockets, null, 2)};
`;
  writeFileSync(OUT_SOCKETS, body);
  console.log(`  Wrote ${OUT_SOCKETS}`);
}

// ── Main ──────────────────────────────────────────────────────────────────────

console.log('Generating simulator lattice...');
const { sockets } = generateSockets();
emitSocketsModule(sockets);
console.log('Done.');
