#!/usr/bin/env bun
/**
 * generate-simulator-data.ts — real hex-socket zones + real protocols → simulator data.
 *
 * The browser simulator (simulator/js/*.js) is plain ES modules with no build step
 * (see simulator/HOWTO.md §2 — "no npm packages, no build step"), so it cannot import
 * app/web's TypeScript directly or fetch() local files reliably from a file:// origin.
 * This script runs the REAL parser (app/web/src/lib/nppsParser.ts) against the REAL
 * source files (protocols/predefined/*.npps) and bakes the result into static generated
 * JS modules the simulator loads like any other local script — no fetch, no CORS issue,
 * still zero install for a user who just opens simulator/index.html.
 *
 * This replaces a hand-authored simulator/js/protocols.js that hardcoded 5 fictional
 * zone-module IDs (ZM-01..05) and 9 fictional protocols disconnected from the real
 * protocol files — exactly the kind of drift this generator exists to prevent, since
 * re-running it after any protocols/predefined/*.npps change regenerates the simulator
 * data from the same source of truth used everywhere else in the repo.
 *
 * Geometry source: hardware/np_socket_map.json (generated by scripts/sync-socket-map.ts
 * from the scan-grounded lattice, NP-HEX-ZM-001 §3.4 — PROVISIONAL pending REG-1/ACT-1).
 * This script does not re-derive socket geometry; it only projects the documented
 * row/col lattice coordinates onto the dome for 3D placement (see toSpherical() below).
 *
 * Outputs:
 *   simulator/js/sockets.generated.js   — SOCKETS (80 hex-tile positions) + ZONES (named
 *                                          socket sets, from 00-zones.npps)
 *   simulator/js/protocols.generated.js — PROTOCOLS keyed by slug (derived from filename)
 *
 * Regenerate with: bun scripts/generate-simulator-data.ts
 */

import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { parseNPPSFile, buildNamespace } from '../app/web/src/lib/nppsParser';
import type {
  NPProtocolDefinition,
  NPZoneDefinition,
  NPModalityParams,
} from '../app/web/src/types/protocol';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const PROTOCOLS_DIR = join(ROOT, 'protocols/predefined');
const SOCKET_MAP_PATH = join(ROOT, 'hardware/np_socket_map.json');
const OUT_SOCKETS = join(ROOT, 'simulator/js/sockets.generated.js');
const OUT_PROTOCOLS = join(ROOT, 'simulator/js/protocols.generated.js');

// T2-only modality types (CLAUDE.md §3 "T2 additions") — used to derive a display tier
// for protocols, since .npps files don't carry an explicit tier field.
const T2_ONLY_MODALITY_TYPES = new Set([
  'qeeg_21ch', 'tms', 'pbm_deep_1170nm', 'clinical_tacs', 'hd_tdcs', 'cervical_vns',
]);

// Peak/limit constants from CLAUDE.md §3 modality 1 (PBM Transcranial), used only to
// derive a plausible simulated dose display — real .npps files carry intensity/duty/
// duration, not a precomputed J/cm² target.
const PBM_PEAK_MW_CM2 = 400;

function slugFromFilename(filename: string): string {
  return filename.replace(/\.npps$/, '');
}

function splitWavelength(wl: string): string[] {
  // '660_808nm' -> ['660nm','808nm']; '1064nm' -> ['1064nm']; '660_808_1064nm' -> all three
  if (wl === '1064nm' || wl === '1170nm') return [wl];
  return wl.replace(/nm$/, '').split('_').map(n => `${n}nm`);
}

function findParam<T extends NPModalityParams['type']>(
  modalities: NPProtocolDefinition['modalities'],
  type: T
): Extract<NPModalityParams, { type: T }>['params'] | undefined {
  const m = modalities.find(m => m.modalityParams.type === type);
  return m ? (m.modalityParams.params as any) : undefined;
}

function deriveTier(def: NPProtocolDefinition): 'T1' | 'T2' {
  return def.modalities.some(m => T2_ONLY_MODALITY_TYPES.has(m.modalityParams.type))
    ? 'T2' : 'T1';
}

function derivePhases(durationSeconds: number) {
  if (durationSeconds < 120) {
    return [{ label: 'Session', start: 0, end: durationSeconds, color: '#334466' }];
  }
  const ramp = Math.min(60, Math.round(durationSeconds * 0.05));
  return [
    { label: 'Ramp', start: 0, end: ramp, color: '#334466' },
    { label: 'Main', start: ramp, end: durationSeconds - ramp, color: '#446688' },
    { label: 'Ramp-down', start: durationSeconds - ramp, end: durationSeconds, color: '#334466' },
  ];
}

function buildModalities(def: NPProtocolDefinition, durationSeconds: number) {
  const out: Record<string, any> = {};

  const pbm = findParam(def.modalities, 'pbm_transcranial');
  if (pbm) {
    const dutyCycle = pbm.dutyCyclePercent / 100;
    const avgIrradianceMWcm2 = PBM_PEAK_MW_CM2 * (pbm.intensityPercent / 100) * dutyCycle;
    const dose_jcm2 = (avgIrradianceMWcm2 * durationSeconds) / 1000; // mW/cm² * s -> mJ/cm² /1000 = J/cm²
    out.pbm = {
      active: true,
      zones: pbm.zoneRefs ?? [],
      wavelengths: splitWavelength(pbm.wavelength),
      frequency: pbm.frequencyHz,
      dutyCycle,
      dose_jcm2: Math.round(dose_jcm2 * 10) / 10,
    };
  }

  const eeg = findParam(def.modalities, 'eeg_neurofeedback');
  if (eeg) {
    out.eeg = {
      active: true,
      channels: ['Fp1', 'Fp2', 'F3', 'F4', 'C3', 'C4', 'P3', 'P4'],
      band: eeg.band,
    };
  }

  const bes = findParam(def.modalities, 'bes_tacs');
  if (bes) {
    out.bes = { active: true, frequency: bes.frequencyHz, intensity_ma: bes.intensityMilliamps };
  }

  const tdcs = findParam(def.modalities, 'tdcs');
  if (tdcs) {
    out.tdcs = { active: true, intensity_ma: tdcs.intensityMilliamps };
  }

  const vns = findParam(def.modalities, 'vns_hrv');
  if (vns) {
    out.vns = {
      active: true,
      frequency: vns.frequencyHz,
      intensity_ma: vns.intensityMilliamps,
      hrv_sync: vns.hrvProtocol !== 'standalone',
    };
  }

  const audio = findParam(def.modalities, 'audio_entrainment');
  if (audio) {
    out.audio = {
      active: true,
      binaural_hz: audio.binauralBeatsHz ?? audio.isochronicTonesHz ?? 10,
      base_hz: audio.carrierHz,
      type: audio.binauralBeatsHz != null ? 'binaural' : 'isochronic',
      breathing_pacer: audio.boneConductionPacer,
      breathing_bpm: vns?.resonanceBreathingRate ?? 6,
    };
  }

  const visual = findParam(def.modalities, 'visual_stimulation');
  if (visual) {
    out.visual = { active: true, frequency: visual.frequencyHz, mode: visual.mode };
  }

  const tms = findParam(def.modalities, 'tms');
  if (tms) {
    out.tms = { active: true, frequency: tms.frequencyHz, target: tms.target, pattern: tms.tmsProtocol };
  }

  const hdTdcs = findParam(def.modalities, 'hd_tdcs');
  if (hdTdcs) {
    out.hd_tdcs = { active: true, target: hdTdcs.target, intensity_ma: hdTdcs.intensityMilliamps };
  }

  return out;
}

// ── Socket geometry: project the documented row/col lattice (hardware/np_socket_map.json)
// onto the dome as spherical (phi, theta), matching simulator/js/helmet.js's existing
// convention (phi: azimuth from +Z front, 0=front, π=back; theta: polar angle from +Y
// crown, 0=crown). This is a projection of real, sourced lattice data — not invented
// geometry. See NP-HEX-ZM-001 §3.4 for the lattice's own provisional status.
//
// hardware/np_socket_map.json's x/y are a proper offset hex lattice, not two
// independently-scaled axes: verified nearest-neighbor center-to-center distance is
// exactly 1.0 unit (= moduleWidthMm, 40mm) everywhere, same-row or cross-row. Any
// projection that normalizes the sagittal (row/y) and lateral (x) components by
// different constants before combining them breaks that real, uniform spacing —
// which is exactly what produced overlapping/non-adjacent hex tiles in the first
// version of this script. The fix: recenter x/y on a single shared origin (the
// crown) and take ONE radial distance (rho, in real lattice units) from it, so
// equal real distances always map to equal angular distances regardless of
// direction — a standard azimuthal-equidistant projection from the crown point.
function toSpherical(x: number, y: number, yCrown: number, angularScale: number) {
  const lateralUnits = -x;              // sign-flipped: anatomical LEFT -> +X (mirrored clinical view, matches EEG_POSITIONS convention in helmet.js)
  const forwardUnits = yCrown - y;      // +front (toward Fp/row0) .. -back (toward O/row11)

  const rho = Math.sqrt(lateralUnits * lateralUnits + forwardUnits * forwardUnits); // real lattice units (1 unit = 40mm)
  const theta = rho * angularScale;
  const phi = Math.atan2(lateralUnits, forwardUnits);

  return { phi, theta, rho };
}

// A fixed-size hexagon stamped at each tile's projected CENTER can't tile
// correctly: this projection's tangential distortion (theta/sin(theta), the
// standard azimuthal-equidistant distortion factor) grows with distance from
// the crown pole, so no single hex size is simultaneously correct for tiles
// near the crown and tiles out at the temporal/occipital rim — the result was
// visibly overlapping tiles with z-fighting "bites" out of them.
//
// The actual fix: hexagon CORNERS in the real 2D lattice are shared between
// neighboring tiles by construction (it's a proper hex tiling — verified
// nearest-neighbor spacing is exactly 1.0 unit everywhere, see toSpherical's
// header comment). So instead of projecting each tile's CENTER and stamping a
// locally-flat hexagon there, project each tile's 6 CORNER points individually
// through the same toSpherical(). Two adjacent tiles' shared lattice corner is
// then the exact same (x,y) input, so it projects to the exact same (phi,
// theta) output — the tiles share that vertex exactly, no matter how much the
// projection distorts elsewhere. This is what makes it a true tiling instead
// of an approximation.
//
// Standard "pointy-top" hex geometry (points up/down, flat vertical edges
// left/right — confirmed against the data: same-row neighbor spacing (pure
// horizontal) equals the nearest-neighbor distance, 1.0 unit; row-to-row
// spacing of 0.8660254 = 1.5 * circumradius confirms it). Circumradius in
// lattice units for flat-to-flat width 1.0: R = 1/sqrt(3).
const HEX_CIRCUMRADIUS_UNITS = 1 / Math.sqrt(3);

function hexCornerOffsets(): Array<[number, number]> {
  const offsets: Array<[number, number]> = [];
  for (let i = 0; i < 6; i++) {
    const a = (Math.PI / 3) * i + Math.PI / 6; // 30°, 90°, 150°, ... — pointy-top
    offsets.push([HEX_CIRCUMRADIUS_UNITS * Math.cos(a), HEX_CIRCUMRADIUS_UNITS * Math.sin(a)]);
  }
  return offsets;
}

function generateSockets() {
  const socketMap = JSON.parse(readFileSync(SOCKET_MAP_PATH, 'utf8'));
  const rows: number[] = socketMap.rowWidths;
  const rowCount = rows.length;
  const THETA_MAX = 0.58 * Math.PI; // stays within the shell's 0.62π dome coverage (helmet.js SHELL)

  // Row-to-row y advances by sqrt(3)/2 per row (standard offset-hex packing,
  // confirmed against the actual data: row1.y/row0.y step = 0.8660254). The
  // crown sits at the mid-row (~50% central-sulcus landmark), not a real row.
  const HEX_ROW_Y_STEP = Math.sqrt(3) / 2;
  const CROWN_ROW = (rowCount - 1) / 2; // 5.5 for 12 rows
  const yCrown = CROWN_ROW * HEX_ROW_Y_STEP;

  // Single global angular scale (radians per lattice unit), calibrated so the
  // single farthest-from-crown socket CENTER lands exactly at THETA_MAX.
  // (Corners of that outermost tile land slightly beyond THETA_MAX — harmless,
  // the shell dome's own polar cutoff has margin above THETA_MAX for this.)
  const rhosRaw = socketMap.sockets.map((s: any) => Math.hypot(-s.x, yCrown - s.y));
  const rhoMax = Math.max(...rhosRaw);
  const angularScale = THETA_MAX / rhoMax;

  const cornerOffsets = hexCornerOffsets();

  let thetaMax = 0;
  const sockets = socketMap.sockets.map((s: any) => {
    const { phi, theta } = toSpherical(s.x, s.y, yCrown, angularScale);
    thetaMax = Math.max(thetaMax, theta);
    const corners = cornerOffsets.map(([dx, dy]) => {
      const c = toSpherical(s.x + dx, s.y + dy, yCrown, angularScale);
      return { phi: c.phi, theta: c.theta };
    });
    return { id: s.id, lobe: s.lobe, side: s.side, row: s.row, phi, theta, corners };
  });
  console.log(`  Sockets: ${sockets.length}, max theta = ${(thetaMax / Math.PI).toFixed(3)}π`);
  return { sockets };
}

function generateZonesAndProtocols() {
  const files = readdirSync(PROTOCOLS_DIR).filter(f => f.endsWith('.npps'));
  const parsedFiles = files.map(f => ({
    filename: f,
    parsed: parseNPPSFile(readFileSync(join(PROTOCOLS_DIR, f), 'utf8')),
  }));

  const { namespace, warnings } = buildNamespace(parsedFiles.map(p => p.parsed));
  if (warnings.length) {
    console.warn('  Namespace warnings:', warnings);
  }

  const zones: NPZoneDefinition[] = [...namespace.zones.values()];

  const protocols: Record<string, any> = {};
  let composites = 0;
  for (const { filename, parsed } of parsedFiles) {
    if (parsed.entries.length === 0) continue; // 00-zones.npps / 00-conditions.npps
    const entry = parsed.entries[0];
    if (entry.kind === 'composite') {
      // Composite protocols reference other protocols by name with time-offset layers.
      // Visualizing them needs cross-referencing + merging constituent modality configs
      // by layer, which is real additional work — out of scope for this pass. Flagged,
      // not silently dropped.
      composites++;
      continue;
    }
    const def = entry.protocol;
    const slug = slugFromFilename(filename);
    const duration = def.timingMode.type === 'duration' ? def.timingMode.seconds : 1200;
    protocols[slug] = {
      id: slug,
      name: def.name,
      description: def.description,
      tier: deriveTier(def),
      duration,
      modalities: buildModalities(def, duration),
      phases: derivePhases(duration),
      conditions: def.conditions ?? [],
    };
  }
  console.log(`  Protocols: ${Object.keys(protocols).length} (${composites} composite protocols skipped — see script header)`);
  console.log(`  Zones: ${zones.length}`);
  return { zones, protocols };
}

// ── Emit ──────────────────────────────────────────────────────────────────────

function emitSocketsModule(sockets: any[], zones: NPZoneDefinition[]) {
  const banner = `// GENERATED by scripts/generate-simulator-data.ts — DO NOT EDIT BY HAND.
// Source of truth: hardware/np_socket_map.json (socket geometry) +
// protocols/predefined/00-zones.npps (named zones), both parsed with the real
// app/web/src/lib/nppsParser.ts. Regenerate with: bun scripts/generate-simulator-data.ts
// Socket lattice is PROVISIONAL v1 (NP-HEX-ZM-001 §3.4) pending gates REG-1/ACT-1.
`;
  const body = `${banner}
/**
 * All 80 hex-tile sockets, with 3D dome position (phi, theta — see
 * helmet.js _sph()) plus each tile's 6 hex corners, individually projected
 * through the same function as the center. Neighboring tiles share literal
 * lattice corner coordinates (it's a proper hex tiling — see toSpherical()'s
 * header comment in scripts/generate-simulator-data.ts), so their shared
 * corner always projects to the identical (phi, theta) — that's what makes
 * helmet.js's rendered tiles actually share edges instead of a fixed-size
 * hexagon approximating each tile's projected center.
 */
export const SOCKETS = ${JSON.stringify(sockets, null, 2)};

/** Named zones (sets of socket ids), from protocols/predefined/00-zones.npps. */
export const ZONES = ${JSON.stringify(
    zones.map(z => ({ name: z.name, sockets: z.sockets, description: z.description ?? '' })),
    null, 2
  )};
`;
  writeFileSync(OUT_SOCKETS, body);
  console.log(`  Wrote ${OUT_SOCKETS}`);
}

function emitProtocolsModule(protocols: Record<string, any>) {
  const banner = `// GENERATED by scripts/generate-simulator-data.ts — DO NOT EDIT BY HAND.
// Source of truth: protocols/predefined/*.npps, parsed with the real
// app/web/src/lib/nppsParser.ts. Regenerate with: bun scripts/generate-simulator-data.ts
// Composite protocols (composite-*.npps) are not included — see script header for why.
`;
  const body = `${banner}
export const PROTOCOLS = ${JSON.stringify(protocols, null, 2)};

export const PROTOCOL_IDS = Object.keys(PROTOCOLS);
`;
  writeFileSync(OUT_PROTOCOLS, body);
  console.log(`  Wrote ${OUT_PROTOCOLS}`);
}

// ── Main ──────────────────────────────────────────────────────────────────────

console.log('Generating simulator data...');
const { sockets } = generateSockets();
const { zones, protocols } = generateZonesAndProtocols();
emitSocketsModule(sockets, zones);
emitProtocolsModule(protocols);
console.log('Done.');
