#!/usr/bin/env bun
/**
 * sync-constants.ts — common/npps/constants.json → the constants every runtime reads.
 *
 * One source (OI-NPPS-CORE-01). A constant is UPPER_SNAKE_CASE and is spelled the same in every language, so
 * `PBM_DEEP_MAX_MW_CM2` is recognisably one thing on the web, in Kotlin, in Swift and in Rust. The Rust core takes them at
 * build time (common/npps-core/build.rs) and has no output to go stale; the rest are written here:
 *
 *   - common/lib/constants.generated.ts                                          (web app, simulator bundle)
 *   - app/android/core/src/main/kotlin/life/neurone/core/protocol/NppsConstants.generated.kt
 *   - app/ios/NeurOne/Protocol/NppsConstants.generated.swift
 *   - app/windows/NeurOne/Protocol/NppsConstants.generated.cs
 *   - common/npps-ffi/include/neurone_npps_status.h                              (the C ABI's return codes)
 *
 *   bun scripts/sync-constants.ts           # rewrite the outputs
 *   bun scripts/sync-constants.ts --check   # fail, writing nothing, if any is stale (CI)
 *
 * The outputs are committed, as SocketLattice.generated.* are: Xcode, Gradle and MSBuild build from the tree. Edit the JSON,
 * never an output.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const SOURCE = 'common/npps/constants.json';

type Target = 'ts' | 'kotlin' | 'swift' | 'csharp' | 'c' | 'rust';
interface Constant { name: string; value: number; int?: boolean; note?: string }
interface Group { name: string; rust: string; cPrefix?: string; targets: Target[]; intTypes?: Partial<Record<Target, string>>; note?: string; constants: Constant[] }
const groups = (JSON.parse(readFileSync(join(ROOT, SOURCE), 'utf8')) as { groups: Group[] }).groups;

const UPPER_SNAKE = /^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$/;
{
  const seen = new Map<string, string>();
  for (const g of groups) for (const c of g.constants) {
    if (!UPPER_SNAKE.test(c.name)) fail(`${g.name}.${c.name} is not UPPER_SNAKE_CASE`);
    const prior = seen.get(c.name);
    if (prior) fail(`${c.name} is in both ${prior} and ${g.name}: one name, one meaning`);
    seen.set(c.name, g.name);
    if (c.int && !Number.isInteger(c.value)) fail(`${g.name}.${c.name} is marked int and is ${c.value}`);
  }
}

function fail(msg: string): never {
  console.error(`sync-constants: ${msg}`);
  process.exit(1);
}

/** A numeric literal every target accepts: a whole-number Double keeps its `.0`. */
function literal(c: Constant): string {
  if (c.int) return String(c.value);
  return Number.isInteger(c.value) ? `${c.value}.0` : String(c.value);
}

/** The language's type for a constant: its whole numbers default to the usual integer, the rest to a double. */
function type(g: Group, target: Target, c: Constant): string {
  const defaults: Partial<Record<Target, [string, string]>> = { kotlin: ['Int', 'Double'], swift: ['Int', 'Double'], csharp: ['int', 'double'] };
  const [whole, fraction] = defaults[target]!;
  return c.int ? (g.intTypes?.[target] ?? whole) : fraction;
}

/** Wrap prose to a width, keeping the author's own line breaks. */
function wrap(text: string, width: number): string[] {
  const out: string[] = [];
  for (const para of text.split('\n')) {
    let line = '';
    for (const word of para.split(/\s+/).filter(Boolean)) {
      if (line && line.length + 1 + word.length > width) { out.push(line); line = word; }
      else line = line ? `${line} ${word}` : word;
    }
    out.push(line);
  }
  return out;
}

const BANNER = `GENERATED by scripts/sync-constants.ts from ${SOURCE}. DO NOT EDIT: change the JSON and re-run it.`;
const forTarget = (t: Target) => groups.filter(g => g.targets.includes(t));
const comment = (text: string | undefined, prefix: string, indent: string, width: number) =>
  text ? wrap(text, width).map(l => `${indent}${prefix} ${l}`).join('\n') + '\n' : '';

function ts(): string {
  const body = forTarget('ts').map(g => {
    const rows = g.constants.map(c => `${comment(c.note, '//', '  ', 110)}  ${c.name}: ${literal(c)},`).join('\n');
    return `${comment(g.note, '//', '', 118)}export const ${g.name} = {\n${rows}\n} as const;\n`;
  }).join('\n');
  return `// ${BANNER}\n\n${body}`;
}

function kotlin(): string {
  const body = forTarget('kotlin').map(g => {
    const rows = g.constants.map(c => `${comment(c.note, '//', '    ', 100)}    const val ${c.name}: ${type(g, 'kotlin', c)} = ${literal(c)}`).join('\n');
    return `${comment(g.note, '//', '', 118)}object ${g.name} {\n${rows}\n}\n`;
  }).join('\n');
  return `package life.neurone.core.protocol\n\n// ${BANNER}\n\n${body}`;
}

function swift(): string {
  const body = forTarget('swift').map(g => {
    const rows = g.constants.map(c => `${comment(c.note, '///', '    ', 100)}    static let ${c.name}: ${type(g, 'swift', c)} = ${literal(c)}`).join('\n');
    return `${comment(g.note, '///', '', 118)}enum ${g.name} {\n${rows}\n}\n`;
  }).join('\n');
  return `import Foundation\n\n// ${BANNER}\n\n${body}`;
}

function csharp(): string {
  const body = forTarget('csharp').map(g => {
    const rows = g.constants.map(c => `${comment(c.note, '///', '    ', 100)}    public const ${type(g, 'csharp', c)} ${c.name} = ${literal(c)};`).join('\n');
    return `${comment(g.note, '///', '', 118)}static class ${g.name}\n{\n${rows}\n}\n`;
  }).join('\n');
  return `// ${BANNER}\n\nnamespace NeurOne.Protocol;\n\n${body}`;
}

/** C has no namespaces, so a macro carries its group's prefix. */
function c(): string {
  const body = forTarget('c').map(g => {
    const rows = g.constants.map(k => `${comment(k.note, '*', ' ', 100).replace(/^ \*/gm, ' *').replace(/^/, '/*\n').replace(/\n$/, '\n */\n')}#define ${g.cPrefix ?? ''}${k.name} ${literal(k)}`).join('\n');
    return `${rows}\n`;
  }).join('\n');
  return `/* ${BANNER} */\n#ifndef NEURONE_NPPS_STATUS_H\n#define NEURONE_NPPS_STATUS_H\n\n${body}\n#endif /* NEURONE_NPPS_STATUS_H */\n`;
}

const OUTPUTS: Array<[string, string]> = [
  ['common/lib/constants.generated.ts', ts()],
  ['app/android/core/src/main/kotlin/life/neurone/core/protocol/NppsConstants.generated.kt', kotlin()],
  ['app/ios/NeurOne/Protocol/NppsConstants.generated.swift', swift()],
  ['app/windows/NeurOne/Protocol/NppsConstants.generated.cs', csharp()],
  ['common/npps-ffi/include/neurone_npps_status.h', c()],
];

if (process.argv.includes('--check')) {
  const stale = OUTPUTS.filter(([p, text]) => !existsSync(join(ROOT, p)) || readFileSync(join(ROOT, p), 'utf8') !== text).map(([p]) => p);
  if (stale.length) fail(`stale (run: bun scripts/sync-constants.ts)\n  ${stale.join('\n  ')}`);
  console.log(`sync-constants: ${groups.reduce((n, g) => n + g.constants.length, 0)} constants in ${groups.length} groups, ${OUTPUTS.length} outputs up to date`);
} else {
  for (const [p, text] of OUTPUTS) writeFileSync(join(ROOT, p), text);
  console.log(`sync-constants: wrote ${OUTPUTS.length} files from ${groups.length} groups`);
}
