#!/usr/bin/env bun
/**
 * sync-use-cases.ts — app/NeurOneShared/Resources/clinician-use-cases.json → the use-case library both apps hold.
 *
 * The library (CLAUDE.md §6.1) was written out twice, in ConsentEngine.swift and ConsentEngine.kt, with a comment saying
 * they "must stay identical": a grant records the use-case IDs it was made from and the two platforms read each other's
 * grants. It is one table now, and each app gets it as a generated file:
 *
 *   - app/ios/NeurOne/Consent/ClinicalUseCaseLibrary.generated.swift
 *   - app/android/core/src/main/kotlin/life/neurone/core/consent/ClinicalUseCaseLibrary.generated.kt
 *
 * Both declare a top-level `USE_CASE_LIBRARY`. The generator also refuses a table the apps could not honour: a
 * duplicate or malformed id, a tier or element the apps do not define, and a name or description key missing from the
 * canonical locale (locales/en.json).
 *
 *   bun scripts/sync-use-cases.ts           # rewrite the outputs
 *   bun scripts/sync-use-cases.ts --check   # fail, writing nothing, if any is stale (CI)
 *   bun scripts/sync-use-cases.ts --self-test
 *
 * CI-Kind: gate
 * CI-Self-Test: bun scripts/sync-use-cases.ts --self-test
 * CI-Scans: app/NeurOneShared/Resources/clinician-use-cases.json against the UHDR element table (uhdr-elements.json), the canonical locale, and both generated library files
 * CI-Scan-Paths: app/NeurOneShared/Resources/clinician-use-cases.json app/ios/NeurOne/Consent/ClinicalUseCaseLibrary.generated.swift app/android/core/src/main/kotlin/life/neurone/core/consent/ClinicalUseCaseLibrary.generated.kt app/NeurOneShared/Resources/uhdr-elements.json locales/en.json scripts/sync-use-cases.ts
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const SOURCE = 'app/NeurOneShared/Resources/clinician-use-cases.json';
const SWIFT_OUT = 'app/ios/NeurOne/Consent/ClinicalUseCaseLibrary.generated.swift';
const KOTLIN_OUT = 'app/android/core/src/main/kotlin/life/neurone/core/consent/ClinicalUseCaseLibrary.generated.kt';
const ELEMENTS_SOURCE = 'app/NeurOneShared/Resources/uhdr-elements.json';
const LOCALE = 'locales/en.json';

/** The tiers a library entry may name. RESEARCH is not one: its elements are IRB-defined per study (§6.3). */
const TIERS = ['MONITOR', 'ASSESS', 'FULL_CLINICAL'] as const;
type Tier = (typeof TIERS)[number];

interface UseCase { id: string; tier: Tier; requiredElements: string[] }

/** Two lines: one would pass SwiftLint's 140-column limit, which counts comments. */
const BANNER = `GENERATED by scripts/sync-use-cases.ts from ${SOURCE}.\n// DO NOT EDIT: change the JSON and re-run it.`;

const upperSnake = (id: string) => id.toUpperCase();
const camel = (name: string) => name.toLowerCase().replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
const titleKey = (u: UseCase) => `CLINICIAN_USECASE_${upperSnake(u.id)}_NAME`;
const descriptionKey = (u: UseCase) => `CLINICIAN_USECASE_${upperSnake(u.id)}_DESC`;

export function validate(useCases: UseCase[], elements: string[], locale: Record<string, unknown>): string[] {
  const problems: string[] = [];
  const seen = new Set<string>();
  for (const u of useCases) {
    if (!/^[a-z][a-z0-9_]*$/.test(u.id)) problems.push(`${u.id}: an id is lower_snake_case`);
    if (seen.has(u.id)) problems.push(`${u.id}: listed twice`);
    seen.add(u.id);
    if (!TIERS.includes(u.tier)) problems.push(`${u.id}: tier ${u.tier} is not one of ${TIERS.join(', ')}`);
    if (u.requiredElements.length === 0) problems.push(`${u.id}: a use case with no elements decides nothing`);
    if (new Set(u.requiredElements).size !== u.requiredElements.length) problems.push(`${u.id}: an element is listed twice`);
    for (const e of u.requiredElements) {
      if (!elements.includes(e)) problems.push(`${u.id}: ${e} is not a UHDRElement in ${ELEMENTS_SOURCE}`);
    }
    for (const k of [titleKey(u), descriptionKey(u)]) {
      if (!(k in locale)) problems.push(`${u.id}: the locale key ${k} is not in ${LOCALE}`);
    }
  }
  return problems;
}

/** Wrap a comma-separated list to a width, indenting continuation lines. */
function wrapList(items: string[], indent: string, width: number): string {
  const lines: string[] = [];
  let line = indent;
  for (const item of items) {
    const piece = `${item},`;
    if (line.trim() && line.length + 1 + piece.length > width) { lines.push(line.trimEnd()); line = indent; }
    line += (line.trim() ? ' ' : '') + piece;
  }
  lines.push(line.trimEnd());
  return lines.join('\n');
}

export function swift(useCases: UseCase[]): string {
  const rows = useCases.map(u => `    ClinicalUseCase(
        id: "${u.id}",
        titleKey: "${titleKey(u)}",
        descriptionKey: "${descriptionKey(u)}",
        requiredElements: [
${wrapList(u.requiredElements.map(e => `.${camel(e)}`), '            ', 110)}
        ],
        tier: .${camel(u.tier)}
    ),`).join('\n');
  return `// ${BANNER}

/// All available clinical use cases — clinicians select from this library (CLAUDE.md §6.1). The same table, from the same
/// source, is Android's \`USE_CASE_LIBRARY\`: a grant records the IDs it was made from and the platforms read each other's
/// grants.
let USE_CASE_LIBRARY: [ClinicalUseCase] = [
${rows}
]
`;
}

export function kotlin(useCases: UseCase[]): string {
  const rows = useCases.map(u => `    ClinicalUseCase(
        id = "${u.id}",
        titleKey = "${titleKey(u)}",
        descriptionKey = "${descriptionKey(u)}",
        requiredElements = setOf(
${wrapList(u.requiredElements.map(e => `UHDRElement.${e}`), '            ', 100)}
        ),
        tier = ClinicianUseCaseTier.${u.tier},
    ),`).join('\n');
  return `package life.neurone.core.consent

import life.neurone.core.models.ClinicianUseCaseTier
import life.neurone.core.models.UHDRElement

// ${BANNER}

/**
 * All available clinical use cases (CLAUDE.md §6.1). The same table, from the same source, is iOS's \`USE_CASE_LIBRARY\`: a
 * grant records the IDs it was made from and the platforms read each other's grants.
 */
val USE_CASE_LIBRARY: List<ClinicalUseCase> = listOf(
${rows}
)
`;
}

function load(): { useCases: UseCase[]; problems: string[] } {
  const read = (rel: string) => readFileSync(join(ROOT, rel), 'utf8');
  const useCases = (JSON.parse(read(SOURCE)) as { useCases: UseCase[] }).useCases;
  const elements = (JSON.parse(read(ELEMENTS_SOURCE)) as { elements: Array<{ name: string }> }).elements.map(e => e.name);
  const problems = validate(useCases, elements, JSON.parse(read(LOCALE)));
  return { useCases, problems };
}

function selfTest(): void {
  const good: UseCase[] = [{ id: 'a_b', tier: 'MONITOR', requiredElements: ['X_Y'] }];
  const locale = { CLINICIAN_USECASE_A_B_NAME: 'n', CLINICIAN_USECASE_A_B_DESC: 'd' };
  const cases: Array<[string, UseCase[], string[], Record<string, unknown>, string]> = [
    ['a clean table passes', good, ['X_Y'], locale, ''],
    ['an element the table lacks', good, [], locale, 'is not a UHDRElement in app/NeurOneShared'],
    ['a missing locale key', good, ['X_Y'], {}, 'is not in locales/en.json'],
    ['a duplicate id', [...good, ...good], ['X_Y'], locale, 'listed twice'],
    ['a tier outside the library', [{ ...good[0]!, tier: 'RESEARCH' as Tier }], ['X_Y'], locale, 'is not one of'],
    ['a use case with no elements', [{ ...good[0]!, requiredElements: [] }], ['X_Y'], locale, 'decides nothing'],
  ];
  let failed = 0;
  for (const [name, table, k, l, expect] of cases) {
    const got = validate(table, k, l).join('\n');
    const ok = expect === '' ? got === '' : got.includes(expect);
    if (!ok) { failed++; console.error(`self-test FAIL: ${name}: ${got || '(no problem found)'}`); }
  }
  if (!swift(good).includes('.xY') || !kotlin(good).includes('UHDRElement.X_Y')) { failed++; console.error('self-test FAIL: emitters'); }
  if (failed) process.exit(1);
  console.log(`sync-use-cases self-test: ${cases.length + 1} cases, all correct.`);
}

if (import.meta.main) {
  if (process.argv.includes('--self-test')) { selfTest(); process.exit(0); }
  const { useCases, problems } = load();
  if (problems.length) {
    console.error(`sync-use-cases: ${SOURCE} is not a table the apps can honour:\n  ${problems.join('\n  ')}`);
    process.exit(1);
  }
  const outputs: Array<[string, string]> = [[SWIFT_OUT, swift(useCases)], [KOTLIN_OUT, kotlin(useCases)]];
  if (process.argv.includes('--check')) {
    const stale = outputs.filter(([p, text]) => !existsSync(join(ROOT, p)) || readFileSync(join(ROOT, p), 'utf8') !== text).map(([p]) => p);
    if (stale.length) { console.error(`sync-use-cases: stale (run: bun scripts/sync-use-cases.ts)\n  ${stale.join('\n  ')}`); process.exit(1); }
    console.log(`sync-use-cases: ${useCases.length} use cases, ${outputs.length} outputs up to date`);
  } else {
    for (const [p, text] of outputs) writeFileSync(join(ROOT, p), text);
    console.log(`sync-use-cases: wrote ${outputs.length} files from ${useCases.length} use cases`);
  }
}
