#!/usr/bin/env bun
/**
 * sync-uhdr-elements.ts — app/NeurOneShared/Resources/uhdr-elements.json → the UHDRElement enum both apps hold.
 *
 * The 11 UHDR elements (CLAUDE.md §5, §6), their wire strings and the lowest clinician tier for each were written out
 * twice, in ConsentModels.swift and ConsentModels.kt, with comments saying they "must match": a signed study descriptor
 * names its elements by wire string and the signature covers those names. It is one table now, and each app gets the enum
 * as a generated file:
 *
 *   - app/ios/NeurOne/Models/UHDRElement.generated.swift
 *   - app/android/core/src/main/kotlin/life/neurone/core/models/UHDRElement.generated.kt
 *
 * The generator refuses a table the apps could not honour: a malformed or duplicate name or wire string, a tier the apps
 * do not define, and a display or description key missing from the canonical locale (locales/en.json).
 *
 *   bun scripts/sync-uhdr-elements.ts           # rewrite the outputs
 *   bun scripts/sync-uhdr-elements.ts --check   # fail, writing nothing, if any is stale (CI)
 *   bun scripts/sync-uhdr-elements.ts --self-test
 *
 * CI-Kind: gate
 * CI-Self-Test: bun scripts/sync-uhdr-elements.ts --self-test
 * CI-Scans: app/NeurOneShared/Resources/uhdr-elements.json against the canonical locale and both generated UHDRElement files
 * CI-Scan-Paths: app/NeurOneShared/Resources/uhdr-elements.json app/ios/NeurOne/Models/UHDRElement.generated.swift app/android/core/src/main/kotlin/life/neurone/core/models/UHDRElement.generated.kt locales/en.json scripts/sync-uhdr-elements.ts
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
export const SOURCE = 'app/NeurOneShared/Resources/uhdr-elements.json';
const SWIFT_OUT = 'app/ios/NeurOne/Models/UHDRElement.generated.swift';
const KOTLIN_OUT = 'app/android/core/src/main/kotlin/life/neurone/core/models/UHDRElement.generated.kt';
const LOCALE = 'locales/en.json';

/** The tiers an element may name. RESEARCH is not one: its elements are IRB-defined per study (§6.3). */
const TIERS = ['MONITOR', 'ASSESS', 'FULL_CLINICAL'] as const;
type Tier = (typeof TIERS)[number];

export interface Element { name: string; wireName: string; minimumTier: Tier }

/** Two lines: one would pass SwiftLint's 140-column limit, which counts comments. */
const BANNER = `GENERATED by scripts/sync-uhdr-elements.ts from ${SOURCE}.\n// DO NOT EDIT: change the JSON and re-run it.`;

const camel = (name: string) => name.toLowerCase().replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
const keySuffix = (e: Element) => e.name.replace(/_/g, '');
const displayKey = (e: Element) => `CONSENT_ELEMENT_${keySuffix(e)}`;
const descriptionKey = (e: Element) => `CONSENT_ELEMENT_DESC_${keySuffix(e)}`;
const quote = (s: string) => JSON.stringify(s);

export function validate(elements: Element[], locale: Record<string, unknown>): string[] {
  const problems: string[] = [];
  const names = new Set<string>();
  const wires = new Set<string>();
  const keys = new Set<string>();
  for (const e of elements) {
    if (!/^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$/.test(e.name)) problems.push(`${e.name}: a name is UPPER_SNAKE_CASE`);
    if (names.has(e.name)) problems.push(`${e.name}: listed twice`);
    names.add(e.name);
    if (!e.wireName.trim() || e.wireName !== e.wireName.trim()) problems.push(`${e.name}: a wire name is non-empty with no edge whitespace`);
    if (wires.has(e.wireName)) problems.push(`${e.name}: wire name ${quote(e.wireName)} is already another element's`);
    wires.add(e.wireName);
    if (!TIERS.includes(e.minimumTier)) problems.push(`${e.name}: tier ${e.minimumTier} is not one of ${TIERS.join(', ')}`);
    if (keys.has(keySuffix(e))) problems.push(`${e.name}: its locale keys collide with another element's once underscores are dropped`);
    keys.add(keySuffix(e));
    for (const k of [displayKey(e), descriptionKey(e)]) {
      if (!(k in locale)) problems.push(`${e.name}: the locale key ${k} is not in ${LOCALE}`);
    }
  }
  return problems;
}

export function swift(elements: Element[]): string {
  const cases = elements.map(e => `    case ${camel(e.name)} = ${quote(e.wireName)}`).join('\n');
  const tierCase = (t: Tier) => elements.filter(e => e.minimumTier === t).map(e => `.${camel(e.name)}`);
  const tiers = TIERS.filter(t => tierCase(t).length > 0)
    .map(t => `        case ${tierCase(t).join(', ')}:\n            return .${camel(t)}`).join('\n');
  const display = elements.map(e => `        case .${camel(e.name)}: return String(localized: "${displayKey(e)}")`).join('\n');
  const description = elements.map(e => `        case .${camel(e.name)}: return String(localized: "${descriptionKey(e)}")`).join('\n');
  return `// ${BANNER}

// UHDR data elements (per NP-FW-EMMC-001 §12). The same table, from the same source, is Android's \`UHDRElement\`: the
// raw value here is its \`wireName\`, and a signed study descriptor names its requested elements by it.

enum UHDRElement: String, CaseIterable, Codable {
${cases}

    /// Lowest clinician tier that may access this element (ISC-137).
    var minimumTier: ClinicianUseCaseTier {
        switch self {
${tiers}
        }
    }

    /// Display text. \`rawValue\` stays the persisted Codable value: it is written
    /// into stored consent records, so it cannot double as the thing on screen.
    var displayName: String {
        switch self {
${display}
        }
    }

    var plainLanguageDescription: String {
        switch self {
${description}
        }
    }
}
`;
}

export function kotlin(elements: Element[]): string {
  const entries = elements.map(e => `    ${e.name}(${quote(e.wireName)})`).join(',\n');
  const tierCase = (t: Tier) => elements.filter(e => e.minimumTier === t).map(e => e.name);
  const tiers = TIERS.filter(t => tierCase(t).length > 0)
    .map(t => `            ${tierCase(t).join(', ')} ->\n                ClinicianUseCaseTier.${t}`).join('\n');
  return `package life.neurone.core.models

// ${BANNER}

/**
 * UHDR data elements (per NP-FW-EMMC-001 §12).
 *
 * [wireName] is the **identity**, for the reason given on [ResearchCategory]: a signed study
 * descriptor names its requested elements by it, and the signature covers those names. It matches
 * iOS \`UHDRElement.rawValue\`, which is that platform's persisted Codable value, so the two agree
 * on what a descriptor says by construction rather than by coincidence —
 * \`StudyDescriptorCanonicalForm\` is where that agreement is used and tested.
 */
enum class UHDRElement(val wireName: String) {
${entries};

    /** Display text. Same string as [wireName] today; see the note on this enum. */
    val displayName: String get() = wireName

    /** Lowest clinician tier that may access this element. */
    val minimumTier: ClinicianUseCaseTier
        get() = when (this) {
${tiers}
        }
}
`;
}

function load(): { elements: Element[]; problems: string[] } {
  const read = (rel: string) => readFileSync(join(ROOT, rel), 'utf8');
  const elements = (JSON.parse(read(SOURCE)) as { elements: Element[] }).elements;
  return { elements, problems: validate(elements, JSON.parse(read(LOCALE))) };
}

function selfTest(): void {
  const good: Element[] = [{ name: 'X_Y', wireName: 'X Y', minimumTier: 'MONITOR' }];
  const locale = { CONSENT_ELEMENT_XY: 'n', CONSENT_ELEMENT_DESC_XY: 'd' };
  const cases: Array<[string, Element[], Record<string, unknown>, string]> = [
    ['a clean table passes', good, locale, ''],
    ['a lowercase name', [{ ...good[0]!, name: 'x_y' }], locale, 'UPPER_SNAKE_CASE'],
    ['a duplicate name', [...good, ...good], locale, 'listed twice'],
    ['a duplicate wire name', [...good, { ...good[0]!, name: 'Z' }], { ...locale, CONSENT_ELEMENT_Z: 'n', CONSENT_ELEMENT_DESC_Z: 'd' }, 'already another element'],
    ['a tier outside the table', [{ ...good[0]!, minimumTier: 'RESEARCH' as Tier }], locale, 'is not one of'],
    ['a missing locale key', good, {}, 'is not in locales/en.json'],
    ['colliding locale keys', [...good, { name: 'XY', wireName: 'XY', minimumTier: 'MONITOR' }], locale, 'collide'],
  ];
  let failed = 0;
  for (const [name, table, l, expect] of cases) {
    const got = validate(table, l).join('\n');
    const ok = expect === '' ? got === '' : got.includes(expect);
    if (!ok) { failed++; console.error(`self-test FAIL: ${name}: ${got || '(no problem found)'}`); }
  }
  if (!swift(good).includes('case xY = "X Y"') || !kotlin(good).includes('X_Y("X Y")')) { failed++; console.error('self-test FAIL: emitters'); }
  if (failed) process.exit(1);
  console.log(`sync-uhdr-elements self-test: ${cases.length + 1} cases, all correct.`);
}

if (import.meta.main) {
  if (process.argv.includes('--self-test')) { selfTest(); process.exit(0); }
  const { elements, problems } = load();
  if (problems.length) {
    console.error(`sync-uhdr-elements: ${SOURCE} is not a table the apps can honour:\n  ${problems.join('\n  ')}`);
    process.exit(1);
  }
  const outputs: Array<[string, string]> = [[SWIFT_OUT, swift(elements)], [KOTLIN_OUT, kotlin(elements)]];
  if (process.argv.includes('--check')) {
    const stale = outputs.filter(([p, text]) => !existsSync(join(ROOT, p)) || readFileSync(join(ROOT, p), 'utf8') !== text).map(([p]) => p);
    if (stale.length) { console.error(`sync-uhdr-elements: stale (run: bun scripts/sync-uhdr-elements.ts)\n  ${stale.join('\n  ')}`); process.exit(1); }
    console.log(`sync-uhdr-elements: ${elements.length} elements, ${outputs.length} outputs up to date`);
  } else {
    for (const [p, text] of outputs) writeFileSync(join(ROOT, p), text);
    console.log(`sync-uhdr-elements: wrote ${outputs.length} files from ${elements.length} elements`);
  }
}
