#!/usr/bin/env bun
/**
 * sync-hardware-limits.ts — common/npps/hardware-limits.json → the hardware-limit constants every runtime reads.
 *
 * One source (OI-NPPS-CORE-01): the shared NPPS core reads the JSON directly (common/npps-core/src/validate.rs, `hw()`),
 * and this writes the constants the editors read, so an editor's slider range and the validator's ceiling cannot differ:
 *
 *   - common/lib/hardwareLimits.generated.ts                                   (web app, simulator bundle)
 *   - app/android/core/src/main/kotlin/life/neurone/core/protocol/NPHardwareLimits.generated.kt
 *   - app/ios/NeurOne/Protocol/NPHardwareLimits.generated.swift
 *
 *   bun scripts/sync-hardware-limits.ts           # rewrite the three files
 *   bun scripts/sync-hardware-limits.ts --check   # fail, writing nothing, if any is stale (CI)
 *
 * The outputs are committed, as SocketLattice.generated.* are: Xcode and Gradle build from the tree. Edit the JSON, never
 * an output.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const SOURCE = 'common/npps/hardware-limits.json';

interface Limit { name: string; value: number; int?: boolean; note?: string }
const limits = (JSON.parse(readFileSync(join(ROOT, SOURCE), 'utf8')) as { limits: Limit[] }).limits;

/**
 * The Kotlin constant for a camelCase name: UPPER_SNAKE_CASE, with the unit suffixes kept whole (`MWcm2` is `MW_CM2`, `UCcm2`
 * is `UC_CM2`, `Am2` is `A_M2`). One rule for every limit, so no platform spells a limit its own way.
 */
function kotlinName(name: string): string {
  return name
    .replace(/(MW|UC|MC)cm2$/, '$1_CM2')
    .replace(/Am2$/, '_A_M2')
    .replace(/cm2$/, '_CM2')
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .toUpperCase();
}

const kotlinNames = limits.map(l => kotlinName(l.name));
if (new Set(kotlinNames).size !== limits.length || new Set(limits.map(l => l.name)).size !== limits.length) {
  console.error('sync-hardware-limits: two limits would share a name; rename one in the JSON');
  process.exit(1);
}

/** A numeric literal every target accepts: a whole-number Double keeps its `.0`. */
function literal(l: Limit): string {
  if (l.int) return String(l.value);
  return Number.isInteger(l.value) ? `${l.value}.0` : String(l.value);
}

/** Wrap prose to a width, keeping the author's own line breaks. */
function wrap(text: string, width: number): string[] {
  const out: string[] = [];
  for (const para of text.split('\n')) {
    let line = '';
    for (const word of para.split(/\s+/).filter(Boolean)) {
      if (line && line.length + 1 + word.length > width) { out.push(line); line = word; }
      else line = line ? `${line} ${word}` : word;
    }
    out.push(line);
  }
  return out;
}

const BANNER = `GENERATED by scripts/sync-hardware-limits.ts from ${SOURCE}. DO NOT EDIT: change the JSON and re-run it.`;

function ts(): string {
  const body = limits.map(l => {
    const note = l.note ? wrap(l.note, 110).map(n => `  // ${n}`).join('\n') + '\n' : '';
    return `${note}  ${l.name}: ${literal(l)},`;
  }).join('\n');
  return `// ${BANNER}
// These are the absolute physical constraints of the NeurOne hardware. No software configuration can override them.

export const NPHardwareLimits = {
${body}
} as const;
`;
}

function kotlin(): string {
  const body = limits.map(l => {
    const note = l.note ? wrap(l.note, 100).map(n => `    // ${n}`).join('\n') + '\n' : '';
    return `${note}    const val ${kotlinName(l.name)}: ${l.int ? 'Int' : 'Double'} = ${literal(l)}`;
  }).join('\n');
  return `package life.neurone.core.protocol

// ${BANNER}
// Non-overridable firmware-enforced constraints from CLAUDE.md. These are absolute ceilings: no dosage limit or clinician
// override can exceed them. The shared NPPS core's validator enforces them as errors; the firmware enforces them independently.
object NPHardwareLimits {
${body}
}
`;
}

function swift(): string {
  const body = limits.map(l => {
    const note = l.note ? wrap(l.note, 100).map(n => `    /// ${n}`).join('\n') + '\n' : '';
    return `${note}    static let ${l.name}: ${l.int ? 'Int' : 'Double'} = ${literal(l)}`;
  }).join('\n');
  return `import Foundation

// ${BANNER}
// Non-overridable firmware-enforced constraints from CLAUDE.md. These are absolute ceilings: no dosage limit or clinician
// override can exceed them. The shared NPPS core's validator enforces them as errors; the firmware enforces them independently.

enum NPHardwareLimits {
${body}
}
`;
}

const OUTPUTS: Array<[string, string]> = [
  ['common/lib/hardwareLimits.generated.ts', ts()],
  ['app/android/core/src/main/kotlin/life/neurone/core/protocol/NPHardwareLimits.generated.kt', kotlin()],
  ['app/ios/NeurOne/Protocol/NPHardwareLimits.generated.swift', swift()],
];

if (process.argv.includes('--check')) {
  const stale = OUTPUTS.filter(([p, text]) => !existsSync(join(ROOT, p)) || readFileSync(join(ROOT, p), 'utf8') !== text).map(([p]) => p);
  if (stale.length) {
    console.error(`sync-hardware-limits: stale (run: bun scripts/sync-hardware-limits.ts)\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log(`sync-hardware-limits: ${limits.length} limits, ${OUTPUTS.length} outputs up to date`);
} else {
  for (const [p, text] of OUTPUTS) writeFileSync(join(ROOT, p), text);
  console.log(`sync-hardware-limits: wrote ${OUTPUTS.length} files from ${limits.length} limits`);
}
