#!/usr/bin/env bun
/**
 * sync-conditions.ts — Canonical NPPS condition registry → platform-native tables.
 *
 * Source of truth: protocols/predefined/00-conditions.npps
 * Targets:
 *   - Apple:   app/ios/NeurOne/Protocol/NPBundledConditions.swift
 *   - Android: app/android/core/src/main/kotlin/life/neurone/core/protocol/NPBundledConditions.kt
 *   - Windows: app/windows/NeurOne/Protocol/NPBundledConditions.cs
 *
 * Web reads the .npps file directly through its own NPPS parser, so it needs no
 * generated table.
 *
 * Why generate rather than parse on each platform: the Swift, Kotlin, and C#
 * NPPS parsers have no `condition` block support, and adding it three times
 * would mean three hand-written parsers to keep in step with the grammar for
 * what is a flat name → link table. Generating keeps 00-conditions.npps the
 * single source of truth (mirroring the existing NPBundledProtocols pattern)
 * and gives each platform a typed, compile-checked table with no parser risk.
 *
 * Run after editing 00-conditions.npps:
 *   bun scripts/sync-conditions.ts
 * Pass --check to fail without writing when the generated files are stale (CI).
 */

import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "..");
const REGISTRY = join(ROOT, "protocols", "predefined", "00-conditions.npps");

const SWIFT_OUT = join(ROOT, "app", "ios", "NeurOne", "Protocol", "NPBundledConditions.swift");
const KOTLIN_OUT = join(
  ROOT, "app", "android", "core", "src", "main", "kotlin", "life", "neurone", "core",
  "protocol", "NPBundledConditions.kt",
);
const CSHARP_OUT = join(ROOT, "app", "windows", "NeurOne", "Protocol", "NPBundledConditions.cs");

interface Condition {
  name: string;
  id?: string;
  link: string;
  code?: string;
  description?: string;
}

// ─── Parse ─────────────────────────────────────────────────────────────────────

/**
 * Read `condition "Name" { key: "value" ... }` blocks. This is the whole of the
 * condition grammar (npps/grammar/npps.peggy) — a name plus string fields — so a
 * targeted reader is sufficient and keeps the generator dependency-free.
 */
function parseConditions(source: string): Condition[] {
  const conditions: Condition[] = [];
  const blockRe = /condition\s+"((?:[^"\\]|\\.)*)"\s*\{([^}]*)\}/g;
  const fieldRe = /([A-Za-z_][A-Za-z0-9_]*)\s*:\s*"((?:[^"\\]|\\.)*)"/g;

  for (const block of source.matchAll(blockRe)) {
    const name = unescape(block[1]);
    const fields: Record<string, string> = {};
    for (const f of block[2].matchAll(fieldRe)) fields[f[1]] = unescape(f[2]);

    if (!fields.link) {
      throw new Error(`condition "${name}" has no link field`);
    }
    conditions.push({
      name,
      id: fields.id,
      link: fields.link,
      code: fields.code,
      description: fields.description,
    });
  }
  return conditions;
}

function unescape(s: string): string {
  return s.replace(/\\(.)/g, (_, c) => (c === "n" ? "\n" : c === "t" ? "\t" : c));
}

// ─── Emit ──────────────────────────────────────────────────────────────────────

const BANNER = (target: string) =>
  `// Generated by scripts/sync-conditions.ts from protocols/predefined/00-conditions.npps.\n` +
  `// DO NOT EDIT BY HAND — edit the .npps registry and re-run:\n` +
  `//     bun scripts/sync-conditions.ts\n` +
  `// ${target}\n`;

/** Escape for a double-quoted string literal in Swift, Kotlin, and C# alike. */
function lit(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n").replace(/\$/g, "\\$");
}

function optLit(s: string | undefined, nilKeyword: string): string {
  return s === undefined ? nilKeyword : `"${lit(s)}"`;
}

function emitSwift(cs: Condition[]): string {
  const rows = cs.map(c => `        NPConditionDefinition(
            name: "${lit(c.name)}",
            id: ${optLit(c.id, "nil")},
            link: "${lit(c.link)}",
            code: ${optLit(c.code, "nil")},
            description: ${optLit(c.description, "nil")}
        ),`).join("\n");

  return `${BANNER("Apple (iOS + macOS)")}
import Foundation

/// The bundled condition registry — standard condition names paired with an
/// external definition link. Protocols reference these by name through their
/// \`conditions\` field. See NP-COND-LINK-001.
enum NPBundledConditions {

    static let all: [NPConditionDefinition] = [
${rows}
    ]

    /// Name → definition, for resolving a protocol's \`conditions\` entries.
    static let byName: [String: NPConditionDefinition] =
        Dictionary(uniqueKeysWithValues: all.map { ($0.name, $0) })
}
`;
}

function emitKotlin(cs: Condition[]): string {
  const rows = cs.map(c => `        NPConditionDefinition(
            name = "${lit(c.name)}",
            id = ${optLit(c.id, "null")},
            link = "${lit(c.link)}",
            code = ${optLit(c.code, "null")},
            description = ${optLit(c.description, "null")},
        ),`).join("\n");

  return `${BANNER("Android")}
package life.neurone.core.protocol

/**
 * The bundled condition registry — standard condition names paired with an
 * external definition link. Protocols reference these by name through their
 * \`conditions\` field. See NP-COND-LINK-001.
 */
object NPBundledConditions {

    val all: List<NPConditionDefinition> = listOf(
${rows}
    )

    /** Name → definition, for resolving a protocol's \`conditions\` entries. */
    val byName: Map<String, NPConditionDefinition> = all.associateBy { it.name }
}
`;
}

function emitCSharp(cs: Condition[]): string {
  const rows = cs.map(c => `        new NPConditionDefinition(
            Name: "${lit(c.name)}",
            Id: ${optLit(c.id, "null")},
            Link: "${lit(c.link)}",
            Code: ${optLit(c.code, "null")},
            Description: ${optLit(c.description, "null")}),`).join("\n");

  return `${BANNER("Windows")}
using System.Collections.Generic;
using System.Linq;

namespace NeurOne.Protocol;

/// <summary>
/// The bundled condition registry — standard condition names paired with an
/// external definition link. Protocols reference these by name through their
/// <c>conditions</c> field. See NP-COND-LINK-001.
/// </summary>
public static class NPBundledConditions
{
    public static readonly IReadOnlyList<NPConditionDefinition> All = new[]
    {
${rows}
    };

    /// <summary>Name → definition, for resolving a protocol's conditions entries.</summary>
    public static readonly IReadOnlyDictionary<string, NPConditionDefinition> ByName =
        All.ToDictionary(c => c.Name);
}
`;
}

// ─── Main ──────────────────────────────────────────────────────────────────────

const checkOnly = process.argv.includes("--check");

const conditions = parseConditions(readFileSync(REGISTRY, "utf-8"));
if (conditions.length === 0) {
  console.error(`No condition blocks found in ${REGISTRY}`);
  process.exit(1);
}

const duplicates = conditions
  .map(c => c.name)
  .filter((n, i, a) => a.indexOf(n) !== i);
if (duplicates.length > 0) {
  console.error(`Duplicate condition names in registry: ${duplicates.join(", ")}`);
  process.exit(1);
}

const outputs: Array<[string, string]> = [
  [SWIFT_OUT, emitSwift(conditions)],
  [KOTLIN_OUT, emitKotlin(conditions)],
  [CSHARP_OUT, emitCSharp(conditions)],
];

let stale = 0;
for (const [path, content] of outputs) {
  let existing: string | null = null;
  try {
    existing = readFileSync(path, "utf-8");
  } catch {
    existing = null;
  }

  if (existing === content) continue;

  if (checkOnly) {
    console.error(`STALE: ${path}`);
    stale++;
  } else {
    writeFileSync(path, content, "utf-8");
    console.log(`wrote ${path}`);
  }
}

if (checkOnly) {
  if (stale > 0) {
    console.error(`\n${stale} generated file(s) out of date — run: bun scripts/sync-conditions.ts`);
    process.exit(1);
  }
  console.log(`${conditions.length} conditions — all generated files up to date.`);
} else {
  console.log(`${conditions.length} conditions synced to 3 platform targets.`);
}
