#!/usr/bin/env bun
/**
 * sync-clinician-tiers.ts — app/NeurOneShared/Resources/clinician-tiers.json → the ClinicianUseCaseTier enum both apps hold.
 *
 * The four clinician tiers (CLAUDE.md §6.1), their persisted labels, ranks, prices and UHDR element sets were written out
 * twice, in ConsentModels.swift and ConsentModels.kt, with comments saying they "must match". It is one table now, and each
 * app gets the enum as a generated file:
 *
 *   - app/ios/NeurOne/Models/ClinicianUseCaseTier.generated.swift
 *   - app/android/core/src/commonMain/kotlin/life/neurone/core/models/ClinicianUseCaseTier.generated.kt
 *
 * A tier's element set is derived from uhdr-elements.json (every element whose minimumTier ranks at or below the tier,
 * less the tier file's withheld elements), so the element table and the tier table cannot disagree. The generator refuses a
 * table the apps could not honour: a duplicate name, label or rank, an element table naming a tier this file lacks, a
 * withheld element that does not exist, and a price or label key missing from the canonical locale (locales/en.json).
 *
 *   bun scripts/sync-clinician-tiers.ts           # rewrite the outputs
 *   bun scripts/sync-clinician-tiers.ts --check   # fail, writing nothing, if any is stale (CI)
 *   bun scripts/sync-clinician-tiers.ts --self-test
 *
 * CI-Kind: gate
 * CI-Self-Test: bun scripts/sync-clinician-tiers.ts --self-test
 * CI-Scans: app/NeurOneShared/Resources/clinician-tiers.json against uhdr-elements.json, the canonical locale and both generated ClinicianUseCaseTier files
 * CI-Scan-Paths: app/NeurOneShared/Resources/clinician-tiers.json app/NeurOneShared/Resources/uhdr-elements.json app/ios/NeurOne/Models/ClinicianUseCaseTier.generated.swift app/android/core/src/commonMain/kotlin/life/neurone/core/models/ClinicianUseCaseTier.generated.kt locales/en.json scripts/sync-clinician-tiers.ts
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const SOURCE = 'app/NeurOneShared/Resources/clinician-tiers.json';
const ELEMENTS_SOURCE = 'app/NeurOneShared/Resources/uhdr-elements.json';
const SWIFT_OUT = 'app/ios/NeurOne/Models/ClinicianUseCaseTier.generated.swift';
const KOTLIN_OUT = 'app/android/core/src/commonMain/kotlin/life/neurone/core/models/ClinicianUseCaseTier.generated.kt';
const LOCALE = 'locales/en.json';

const UNITS = ['PATIENT', 'STUDY'] as const;
type Unit = (typeof UNITS)[number];

export interface Tier {
  name: string; label: string; rank: number; priceUsd: number; priceUnit: Unit;
  withheldElements?: string[]; elementsFromStudy?: boolean;
}
export interface Element { name: string; minimumTier: string }

/** Two lines: one would pass SwiftLint's 140-column limit, which counts comments. */
const BANNER = `GENERATED by scripts/sync-clinician-tiers.ts from ${SOURCE}.\n// DO NOT EDIT: change the JSON and re-run it.`;

const camel = (name: string) => name.toLowerCase().replace(/_([a-z0-9])/g, (_, c: string) => c.toUpperCase());
const quote = (s: string) => JSON.stringify(s);
const priceKey = (t: Tier) => `CLINICIAN_TIER_PRICE_PER_${t.priceUnit}`;
const labelKey = (t: Tier) => `CLINICIAN_TIER_${t.name}`;
const KOTLIN_UNIT: Record<Unit, string> = { PATIENT: 'patient', STUDY: 'study' };

/** The elements a tier reaches, in element-table order. */
export function elementsOf(tier: Tier, tiers: Tier[], elements: Element[]): string[] {
  if (tier.elementsFromStudy) return [];
  const rank = new Map(tiers.map(t => [t.name, t.rank]));
  return elements
    .filter(e => (rank.get(e.minimumTier) ?? Infinity) <= tier.rank && !(tier.withheldElements ?? []).includes(e.name))
    // A withheld element is withheld from every tier at or above the one that withholds it, never admitted again higher up.
    .filter(e => !tiers.some(t => t.rank <= tier.rank && (t.withheldElements ?? []).includes(e.name)))
    .map(e => e.name);
}

export function validate(tiers: Tier[], elements: Element[], locale: Record<string, unknown>): string[] {
  const problems: string[] = [];
  const seen = { name: new Set<string>(), label: new Set<string>(), rank: new Set<number>() };
  const elementNames = new Set(elements.map(e => e.name));
  for (const t of tiers) {
    if (!/^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$/.test(t.name)) problems.push(`${t.name}: a name is UPPER_SNAKE_CASE`);
    if (seen.name.has(t.name)) problems.push(`${t.name}: listed twice`);
    seen.name.add(t.name);
    if (!t.label.trim() || t.label !== t.label.trim()) problems.push(`${t.name}: a label is non-empty with no edge whitespace`);
    if (seen.label.has(t.label)) problems.push(`${t.name}: label ${quote(t.label)} is already another tier's`);
    seen.label.add(t.label);
    if (!Number.isInteger(t.rank) || t.rank < 0) problems.push(`${t.name}: a rank is a non-negative integer`);
    if (seen.rank.has(t.rank)) problems.push(`${t.name}: rank ${t.rank} is already another tier's`);
    seen.rank.add(t.rank);
    if (!UNITS.includes(t.priceUnit)) problems.push(`${t.name}: price unit ${t.priceUnit} is not one of ${UNITS.join(', ')}`);
    if (!Number.isInteger(t.priceUsd) || t.priceUsd < 0) problems.push(`${t.name}: a price is a non-negative whole number of dollars`);
    for (const w of t.withheldElements ?? []) {
      if (!elementNames.has(w)) problems.push(`${t.name}: withheld element ${w} is not in ${ELEMENTS_SOURCE}`);
    }
    for (const k of [labelKey(t), priceKey(t)]) {
      if (!(k in locale)) problems.push(`${t.name}: the locale key ${k} is not in ${LOCALE}`);
    }
  }
  const tierNames = new Set(tiers.map(t => t.name));
  for (const e of elements) {
    if (!tierNames.has(e.minimumTier)) problems.push(`${e.name}: minimumTier ${e.minimumTier} is not a tier in ${SOURCE}`);
  }
  return problems;
}

/** Wrap a comma-separated list to a width, indenting continuation lines. */
function wrapList(items: string[], indent: string, width: number): string {
  const lines: string[] = [];
  let line = indent;
  for (const item of items) {
    const piece = `${item},`;
    if (line.trim() && line.length + 1 + piece.length > width) { lines.push(line.trimEnd()); line = indent; }
    line += (line.trim() ? ' ' : '') + piece;
  }
  lines.push(line.trimEnd());
  return lines.join('\n');
}

export function swift(tiers: Tier[], elements: Element[]): string {
  const sw = (fn: (t: Tier) => string) => tiers.map(t => `        case .${camel(t.name)}:${fn(t)}`).join('\n');
  const cases = tiers.map(t => `    case ${camel(t.name)} = ${quote(t.label)}`).join('\n');
  const sets = tiers.map(t => {
    const els = elementsOf(t, tiers, elements);
    const body = els.length ? `[\n${wrapList(els.map(e => `.${camel(e)}`), '                ', 110)}\n            ]` : '[]';
    return `        case .${camel(t.name)}:\n            return ${body}`;
  }).join('\n');
  return `// ${BANNER}

// Clinician use-case tiers (CLAUDE.md §6.1). The same table, from the same source, is Android's \`ClinicianUseCaseTier\`.

enum ClinicianUseCaseTier: String, CaseIterable, Codable {
${cases}

    /// Display text. \`rawValue\` stays the persisted Codable value: it is written
    /// into stored grants, so it cannot double as the thing on screen.
    var displayName: String {
        switch self {
${sw(t => ` return String(localized: "${labelKey(t)}")`)}
        }
    }

    var monthlyPrice: String {
        switch self {
${sw(t => ` return String(format: String(localized: "${priceKey(t)}"), "$${t.priceUsd}")`)}
        }
    }

    /// Ordering for "does this tier reach that one". Not \`allCases.firstIndex(of:)\`, which would
    /// silently re-rank if a case were ever reordered or inserted, and not \`uhdrElements.count\`,
    /// which puts \`.research\` — empty by design — below \`.monitor\`.
    var rank: Int {
        switch self {
${sw(t => ` return ${t.rank}`)}
        }
    }

    /// Minimum necessary UHDR elements for this tier. Derived from \`UHDRElement.minimumTier\`; \`.research\` is
    /// IRB-defined and populated per study descriptor.
    var uhdrElements: Set<UHDRElement> {
        switch self {
${sets}
        }
    }
}
`;
}

export function kotlin(tiers: Tier[], elements: Element[]): string {
  const entries = tiers.map(t => `    ${t.name}(${quote(t.label)}, ${quote(`$${t.priceUsd}/month/${KOTLIN_UNIT[t.priceUnit]}`)})`).join(',\n');
  const ranks = tiers.map(t => `            ${t.name} -> ${t.rank}`).join('\n');
  const sets = tiers.map(t => {
    const els = elementsOf(t, tiers, elements);
    const body = els.length ? `setOf(\n${wrapList(els.map(e => `UHDRElement.${e}`), '                ', 100)}\n            )` : 'emptySet()';
    return `            ${t.name} -> ${body}`;
  }).join('\n');
  return `package life.neurone.core.models

// ${BANNER}

/**
 * Clinician use-case tiers (CLAUDE.md §6.1). The same table, from the same source, is iOS's \`ClinicianUseCaseTier\`.
 * [displayName] is iOS's persisted raw value.
 */
enum class ClinicianUseCaseTier(val displayName: String, val monthlyPrice: String) {
${entries};

    /**
     * Ordering for "does this tier reach that one". Not [ordinal], which silently re-ranks if a
     * case is reordered or inserted, and not \`uhdrElements.size\`, which puts [RESEARCH] — empty
     * by design — below [MONITOR].
     */
    val rank: Int
        get() = when (this) {
${ranks}
        }

    /** Minimum necessary UHDR elements for this tier. Derived from [UHDRElement.minimumTier]; [RESEARCH] is IRB-defined. */
    val uhdrElements: Set<UHDRElement>
        get() = when (this) {
${sets}
        }
}
`;
}

function load(): { tiers: Tier[]; elements: Element[]; problems: string[] } {
  const read = (rel: string) => readFileSync(join(ROOT, rel), 'utf8');
  const tiers = (JSON.parse(read(SOURCE)) as { tiers: Tier[] }).tiers;
  const elements = (JSON.parse(read(ELEMENTS_SOURCE)) as { elements: Element[] }).elements;
  return { tiers, elements, problems: validate(tiers, elements, JSON.parse(read(LOCALE))) };
}

function selfTest(): void {
  const a: Tier = { name: 'LOW', label: 'Low', rank: 0, priceUsd: 1, priceUnit: 'PATIENT' };
  const b: Tier = { name: 'HIGH_ONE', label: 'High One', rank: 1, priceUsd: 2, priceUnit: 'STUDY', withheldElements: ['E3'] };
  const tiers = [a, b];
  const els: Element[] = [{ name: 'E1', minimumTier: 'LOW' }, { name: 'E2', minimumTier: 'HIGH_ONE' }, { name: 'E3', minimumTier: 'LOW' }];
  const locale = { CLINICIAN_TIER_LOW: '', CLINICIAN_TIER_HIGH_ONE: '', CLINICIAN_TIER_PRICE_PER_PATIENT: '', CLINICIAN_TIER_PRICE_PER_STUDY: '' };
  const cases: Array<[string, Tier[], Element[], Record<string, unknown>, string]> = [
    ['a clean table passes', tiers, els, locale, ''],
    ['a duplicate name', [a, a], els, locale, 'listed twice'],
    ['a duplicate label', [a, { ...b, label: 'Low' }], els, locale, 'already another tier'],
    ['a duplicate rank', [a, { ...b, rank: 0 }], els, locale, 'rank 0 is already'],
    ['an unknown price unit', [a, { ...b, priceUnit: 'SEAT' as Unit }], els, locale, 'is not one of'],
    ['a withheld element that does not exist', [a, { ...b, withheldElements: ['NOPE'] }], els, locale, 'withheld element NOPE'],
    ['an element naming a missing tier', tiers, [...els, { name: 'E4', minimumTier: 'GONE' }], locale, 'is not a tier'],
    ['a missing locale key', tiers, els, {}, 'is not in locales/en.json'],
  ];
  let failed = 0;
  for (const [name, t, e, l, expect] of cases) {
    const got = validate(t, e, l).join('\n');
    const ok = expect === '' ? got === '' : got.includes(expect);
    if (!ok) { failed++; console.error(`self-test FAIL: ${name}: ${got || '(no problem found)'}`); }
  }
  // E3 is withheld from HIGH_ONE and so is withheld from every tier at or above it, but LOW still reaches it.
  const derived: Array<[string, string[]]> = [['LOW', ['E1', 'E3']], ['HIGH_ONE', ['E1', 'E2']]];
  for (const [n, want] of derived) {
    const got = elementsOf(tiers.find(t => t.name === n)!, tiers, els).join(',');
    if (got !== want.join(',')) { failed++; console.error(`self-test FAIL: elementsOf ${n}: ${got}`); }
  }
  if (elementsOf({ ...b, elementsFromStudy: true }, tiers, els).length) { failed++; console.error('self-test FAIL: a study tier has no library elements'); }
  if (!swift(tiers, els).includes('case highOne = "High One"') || !kotlin(tiers, els).includes('HIGH_ONE("High One", "$2/month/study")')) { failed++; console.error('self-test FAIL: emitters'); }
  if (failed) process.exit(1);
  console.log(`sync-clinician-tiers self-test: ${cases.length + derived.length + 2} cases, all correct.`);
}

if (import.meta.main) {
  if (process.argv.includes('--self-test')) { selfTest(); process.exit(0); }
  const { tiers, elements, problems } = load();
  if (problems.length) {
    console.error(`sync-clinician-tiers: ${SOURCE} is not a table the apps can honour:\n  ${problems.join('\n  ')}`);
    process.exit(1);
  }
  const outputs: Array<[string, string]> = [[SWIFT_OUT, swift(tiers, elements)], [KOTLIN_OUT, kotlin(tiers, elements)]];
  if (process.argv.includes('--check')) {
    const stale = outputs.filter(([p, text]) => !existsSync(join(ROOT, p)) || readFileSync(join(ROOT, p), 'utf8') !== text).map(([p]) => p);
    if (stale.length) { console.error(`sync-clinician-tiers: stale (run: bun scripts/sync-clinician-tiers.ts)\n  ${stale.join('\n  ')}`); process.exit(1); }
    console.log(`sync-clinician-tiers: ${tiers.length} tiers, ${outputs.length} outputs up to date`);
  } else {
    for (const [p, text] of outputs) writeFileSync(join(ROOT, p), text);
    console.log(`sync-clinician-tiers: wrote ${outputs.length} files from ${tiers.length} tiers`);
  }
}
