/* GENERATED by scripts/sync-constants.ts from common/npps/constants.json. DO NOT EDIT: change the JSON and re-run it. */
#ifndef NP_APP_WIRE_CONSTANTS_H
#define NP_APP_WIRE_CONSTANTS_H

/*
 * 4E455550-0000-1000-8000-00805F9B34FB, least-significant byte first. The id of a characteristic
 * replaces the two bytes at NP_GATT_UUID_ID_OFFSET.
 */
#define NP_GATT_UUID_BASE_INIT { 0xFBu, 0x34u, 0x9Bu, 0x5Fu, 0x80u, 0x00u, 0x00u, 0x80u, 0x00u, 0x10u, 0x00u, 0x00u, 0x50u, 0x55u, 0x45u, 0x4Eu }
#define NP_GATT_UUID_ID_OFFSET 10

/*
 * The NeurOne custom service.
 */
#define NP_GATT_SERVICE_ID 0x0001u
/*
 * READ/NOTIFY 8 B, WRITE 1 B (OI-ACC-08).
 */
#define NP_GATT_CONSUMABLE_STATUS_ID 0x0007u
/*
 * READ 32 B, hub-provisioned TRNG warranty token (OI-WA-03).
 */
#define NP_GATT_WARRANTY_TOKEN_ID 0x0010u
/*
 * READ/NOTIFY 4+8n B, cervical VNS offline-fault summary and re-enable state (NP-SW-FAULTMSG-001).
 */
#define NP_GATT_CVNS_FAULT_STATUS_ID 0x0014u
/*
 * WRITE 1 B 0x01, the wearer's re-enable confirmation after a cardiac cutoff.
 */
#define NP_GATT_CVNS_REENABLE_CONFIRM_ID 0x0015u
/*
 * WRITE 4 B, little-endian opaque tag of the person using the device.
 */
#define NP_GATT_ACTIVE_USER_ID 0x0016u
/*
 * READ 32 B, encrypted link only (NP-FW-HUB-001 §4.2, OI-AND-WIRE-02).
 */
#define NP_GATT_DEVICE_SERIAL_ID 0x0017u

/*
 * The hub's replay-guard serial (DEVICE_SERIAL characteristic, NP-FW-HUB-001 §4.2): exactly this many
 * bytes, never padded or truncated.
 */
#define NP_GATT_DEVICE_SERIAL_LEN 32U
/*
 * Byte 0 of the frame.
 */
#define NP_CVFS_WIRE_VERSION 1U
/*
 * Header bytes before the first record.
 */
#define NP_CVFS_HEADER_LEN 4U
/*
 * Bytes in one fault record.
 */
#define NP_CVFS_RECORD_LEN 8U
/*
 * Most records one frame carries.
 */
#define NP_CVFS_MAX_WIRE_RECORDS 4U
/*
 * Byte 0 of every frame.
 */
#define NP_ZN_FORMAT_VERSION 0x02U
/*
 * Header bytes before the first record: byte 0 format version, byte 1 flags (including the frame kind
 * bit), byte 2 fragment index (0-based), byte 3 record count in this fragment.
 */
#define NP_ZN_HEADER_BYTES 4U
/*
 * Status record: socket id (1-based), module type, flags.
 */
#define NP_ZN_STATUS_REC_BYTES 3U
/*
 * Map record: socket id (1-based), flags, then x_mm, y_mm, z_mm as int16 little-endian.
 */
#define NP_ZN_MAP_REC_BYTES 8U
/*
 * Largest 1-based socket id the wire can carry. Firmware ids are 0-based over NP_HEXMAP_MAX_SOCKETS
 * (128), so the 1-based domain is 1..128, exactly a uint8_t's usable range above zero. Pinned by a
 * static assert in np_zone_notify.c against NP_HEXMAP_MAX_SOCKETS.
 */
#define NP_ZN_MAX_SOCKET_ID 128U
/*
 * Frame flag (byte 1): this fragment belongs to a full snapshot. Clear = incremental delta naming only
 * the sockets that changed. Socket-map frames are always snapshots.
 */
#define NP_ZN_FLAG_SNAPSHOT 0x01U
/*
 * Frame flag (byte 1): final fragment of this frame sequence. A snapshot is committed by the app only
 * when a fragment carrying this flag arrives.
 */
#define NP_ZN_FLAG_LAST 0x02U
/*
 * Frame flag (byte 1), the frame KIND: set = socket-map records, clear = status records. The two
 * shapes differ in size, so a decoder that assumed the wrong one would misparse rather than fail; the
 * kind is on the wire so it can be checked, not inferred from which characteristic delivered it.
 */
#define NP_ZN_FLAG_MAP 0x04U
/*
 * Status-record flag (record byte 2): a module is seated and confirmed in this socket. Clear = socket
 * is empty (a removal, or an empty socket in a snapshot).
 */
#define NP_ZN_REC_PRESENT 0x01U
/*
 * Status-record flag (record byte 2): the module failed identification (unrecognised type, bad
 * contact, failed debounce). PRESENT is clear whenever FAULT is set: an unidentified module is never
 * reported as usable.
 */
#define NP_ZN_REC_FAULT 0x02U
/*
 * Map-record flag (record byte 1): this socket is physically wired in this shell. Clear = the address
 * exists in the geometry table but the shell does not populate it.
 */
#define NP_ZN_MAP_WIRED 0x01U
/*
 * The session UUID, the UHDR key.
 */
#define NP_HUB_PROTO_UUID_LEN 16U
/*
 * The Ed25519 signature at the end of the blob.
 */
#define NP_HUB_PROTO_SIG_LEN 64U
/*
 * Descriptor flag bit 0, computed by the app. It carries no authority: no firmware decision reads it,
 * because whether a protocol is T2 comes from its modality set and whether this unit may run one is
 * the safety MCU's signed tier identity (RISK-PWRSRC-10).
 */
#define NP_PROTO_FLAG_T2_TIER 1U
/*
 * Pads checked every session: the bilateral gel-pad assembly, left and right.
 */
#define NP_CVNS_ELECTRODE_COUNT 2U

#endif /* NP_APP_WIRE_CONSTANTS_H */
