// Generated by scripts/sync-conditions.ts from protocols/predefined/00-conditions.npps.
// DO NOT EDIT BY HAND — edit the .npps registry and re-run:
//     bun scripts/sync-conditions.ts
// Windows

using System.Collections.Generic;
using System.Linq;

namespace NeurOne.Protocol;

/// <summary>
/// The bundled condition registry — standard condition names paired with an
/// external definition link. Protocols reference these by name through their
/// <c>conditions</c> field. See NP-COND-LINK-001.
/// </summary>
public static class NPBundledConditions
{
    public static readonly IReadOnlyList<NPConditionDefinition> All = new[]
    {
        new NPConditionDefinition(
            Name: "Alzheimer's Disease",
            Id: "41000001-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Alzheimer%27s_disease",
            Code: "8A20",
            Description: null),
        new NPConditionDefinition(
            Name: "Dementia",
            Id: "41000002-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Dementia",
            Code: "6D8Z",
            Description: null),
        new NPConditionDefinition(
            Name: "Mild Cognitive Impairment",
            Id: "41000003-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Mild_cognitive_impairment",
            Code: "6D71",
            Description: null),
        new NPConditionDefinition(
            Name: "Major Depressive Disorder",
            Id: "41000004-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Major_depressive_disorder",
            Code: "6A70",
            Description: null),
        new NPConditionDefinition(
            Name: "Generalized Anxiety Disorder",
            Id: "41000005-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Generalized_anxiety_disorder",
            Code: "6B00",
            Description: null),
        new NPConditionDefinition(
            Name: "Traumatic Brain Injury",
            Id: "41000006-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Traumatic_brain_injury",
            Code: "NA07",
            Description: null),
        new NPConditionDefinition(
            Name: "Post-Concussion Syndrome",
            Id: "41000007-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Post-concussion_syndrome",
            Code: "8A8E",
            Description: null),
        new NPConditionDefinition(
            Name: "Autism Spectrum Disorder",
            Id: "41000008-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Autism_spectrum_disorder",
            Code: "6A02",
            Description: null),
        new NPConditionDefinition(
            Name: "Parkinson's Disease",
            Id: "41000009-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Parkinson%27s_disease",
            Code: "8A00.0",
            Description: null),
        new NPConditionDefinition(
            Name: "Stroke",
            Id: "41000010-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Stroke",
            Code: "8B20",
            Description: null),
        new NPConditionDefinition(
            Name: "Aphasia",
            Id: "41000011-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Aphasia",
            Code: "MA80.1",
            Description: null),
        new NPConditionDefinition(
            Name: "Epilepsy",
            Id: "41000012-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Epilepsy",
            Code: "8A6Z",
            Description: null),
        new NPConditionDefinition(
            Name: "Post-Traumatic Stress Disorder",
            Id: "41000013-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Post-traumatic_stress_disorder",
            Code: "6B40",
            Description: null),
        new NPConditionDefinition(
            Name: "Substance Use Disorder",
            Id: "41000014-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Substance_use_disorder",
            Code: "6C4Z",
            Description: null),
        new NPConditionDefinition(
            Name: "Attention Deficit Hyperactivity Disorder",
            Id: "41000015-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Attention_deficit_hyperactivity_disorder",
            Code: "6A05",
            Description: null),
        new NPConditionDefinition(
            Name: "Schizophrenia",
            Id: "41000016-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Schizophrenia",
            Code: "6A20",
            Description: null),
        new NPConditionDefinition(
            Name: "Tinnitus",
            Id: "41000017-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Tinnitus",
            Code: "MC41",
            Description: null),
        new NPConditionDefinition(
            Name: "Fibromyalgia",
            Id: "41000018-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Fibromyalgia",
            Code: "MG30.01",
            Description: null),
        new NPConditionDefinition(
            Name: "Chronic Pain",
            Id: "41000019-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Chronic_pain",
            Code: "MG30",
            Description: null),
        new NPConditionDefinition(
            Name: "Neuropathic Pain",
            Id: "41000020-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Neuropathic_pain",
            Code: "8E43",
            Description: null),
        new NPConditionDefinition(
            Name: "Multiple Sclerosis",
            Id: "41000021-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Multiple_sclerosis",
            Code: "8A40",
            Description: null),
        new NPConditionDefinition(
            Name: "Insomnia",
            Id: "41000022-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Insomnia",
            Code: "7A00",
            Description: null),
        new NPConditionDefinition(
            Name: "Migraine",
            Id: "41000023-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Migraine",
            Code: "8A80",
            Description: null),
        new NPConditionDefinition(
            Name: "Cluster Headache",
            Id: "41000024-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Cluster_headache",
            Code: "8A81",
            Description: null),
        new NPConditionDefinition(
            Name: "Essential Tremor",
            Id: "41000025-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Essential_tremor",
            Code: "8A04.1",
            Description: null),
        new NPConditionDefinition(
            Name: "Disorders of Consciousness",
            Id: "41000026-0000-0000-0000-000000000000",
            Link: "https://en.wikipedia.org/wiki/Disorders_of_consciousness",
            Code: null,
            Description: null),
    };

    /// <summary>Name → definition, for resolving a protocol's conditions entries.</summary>
    public static readonly IReadOnlyDictionary<string, NPConditionDefinition> ByName =
        All.ToDictionary(c => c.Name);
}
