// GENERATED by scripts/sync-constants.ts from common/npps/constants.json. DO NOT EDIT: change the JSON and re-run it.

namespace NeurOne.Protocol;

/// Every hardware ceiling and fixed device figure the apps and the shared validator use. The firmware enforces them
/// independently; no dosage limit or clinician override can exceed them.
static class NPHardwareLimits
{
    /// PBM Transcranial / Intranasal (shared firmware limit)
    public const int PBM_DUTY_CYCLE_MAX_PERCENT = 25;
    /// pending RISK-03 regulatory opinion
    public const double PBM_PULSED_PEAK_MW_CM2 = 400.0;
    public const double PBM_CW_MAX_MW_CM2 = 200.0;
    /// Deep 1170 nm PBM ceiling (CLAUDE.md §3: ≤1,000 mW/cm², TEC-stabilised).
    public const double PBM_DEEP_MAX_MW_CM2 = 1000.0;
    /// Aggregate PBM irradiance ceiling (OI-PBM-05, three-channel combined). Pending RISK-03 regulatory
    /// opinion scope expansion (Q4–Q6).
    public const double PBM_AGGREGATE_MAX_MW_CM2 = 600.0;
    /// BES / tACS (consumer: Brainwave Entrainment Stimulation)
    public const double BES_TACS_MAX_MILLIAMPS = 1.0;
    public const double BES_TACS_MIN_HZ = 0.5;
    public const double BES_TACS_MAX_HZ = 40.0;
    /// tDCS (consumer: Cortical Priming Stimulation)
    public const double TDCS_MIN_MILLIAMPS = 0.1;
    public const double TDCS_MAX_MILLIAMPS = 2.0;
    /// OI-CHARGE-04 (closed 2026-09-09): this IS checked here now. There is no web electrode-area constant
    /// to add, because there is no longer a global electrode area on any client — the area is authored per
    /// protocol (TDCSParams.electrodeAreaCm2), travels in the signed session descriptor, and the safety MCU
    /// derives its charge limit from that same declared number. What used to be a 35-vs-25 disagreement
    /// between the app's assumption and the enforcer's is now one transmitted value. OI-CHARGE-05 (a)(d)
    /// 2026-09-15: RENAMED AND RE-SOURCED. This used to be `tdcsMaxChargeDensityUCcm2: 40.0`, a misnomer
    /// that concealed a 1000× divergence — `I(mA) × t(s) / A(cm²)` is mC/cm², so the clients enforced 40
    /// mC/cm² while the safety MCU enforced 40 µC/cm². The name now states the unit AND the period, because
    /// both were ambiguous and each hid a different defect: the unit hid the 1000×, and the missing period
    /// hid that a per-phase pulsed figure was being applied to a DC session dose. 150 mC/cm² per session
    /// per electrode, derived rather than asserted (the old 40 had no source anywhere in the tree — the
    /// citation chain was circular). Bounds the conventional large-pad human tDCS envelope: the
    /// most-exposed large RCT protocol in docs/tdcs_database_full.csv is Brunoni ELECT-TDCS 2013/2017 at 2
    /// mA × 30 min on 25 cm² = 144 mC/cm². Margin check: 35× below Liebetanz 2009's measured rat epicranial
    /// DC lesion threshold of 5,240 mC/cm². Full derivation: NP-DT-001 DI-SAFE-01.
    public const double TDCS_MAX_SESSION_CHARGE_DENSITY_MC_CM2 = 150.0;
    /// Per-PHASE ceiling for the charge-balanced biphasic modalities — BES/tACS, VNS, cervical VNS,
    /// clinical tACS (OI-CHARGE-05 (b)). 40 µC/cm² is a real and correct figure in this form (Shannon 1992
    /// / McCreery 1990 pulsed charge-injection limits); it is the number the tree has always carried, now
    /// applied to the waveform class it is actually about. Net charge on these modalities is ~zero by
    /// construction, so a session-cumulative dose is not a physical quantity for them and is not checked.
    public const double PULSED_MAX_PHASE_CHARGE_DENSITY_UC_CM2 = 40.0;
    /// Electrode areas for the modalities whose electrodes are FIXED PARTS OF THE PRODUCT rather than a
    /// user-chosen consumable. The tDCS pad is authored per protocol precisely because the user picks it
    /// (OI-CHARGE-04); the BES pads, auricular clip and cervical collar are not swappable, so their area is
    /// a device property both the app and firmware may hold. ⚠ PROVISIONAL — NOT MEASURED (OI-CHARGE-07).
    /// Mirrors firmware/hub_control/include/np_hub_config.h. A SMALLER area is a SMALLER charge budget, so
    /// these may be revised down freely and may only be revised up against a measurement.
    public const double BES_ELECTRODE_AREA_CM2 = 25.0;
    public const double VNS_ELECTRODE_AREA_CM2 = 0.5;
    public const double CERVICAL_VNS_ELECTRODE_AREA_CM2 = 2.0;
    /// Pulse width (seconds) the firmware substitutes when a descriptor declares none: np_mod_cvns.c and
    /// np_session_runner.c both default to 250 µs. The pre-flight must use the same number or it validates
    /// a different waveform than the one that runs.
    public const double VNS_DEFAULT_PULSE_WIDTH_SECONDS = 0.00025;
    /// Largest declarable per-electrode area: the wire field (np_mod_tdcs_params_t.electrode_area_mcm2) is
    /// a uint16 of milli-cm², so 65535 mcm². Not a clinical limit — an encoding ceiling, well above any
    /// real pad (a large sponge is 35 cm²).
    public const double TDCS_MAX_ELECTRODE_AREA_CM2 = 65.535;
    /// What a NEW tDCS block is seeded with in an editor (a large sponge pad). It is not a limit: the area
    /// is authored per protocol, travels in the signed descriptor, and the safety MCU derives its charge
    /// limit from that declared number (OI-CHARGE-04).
    public const double TDCS_DEFAULT_ELECTRODE_AREA_CM2 = 35.0;
    /// hardware-enforced minimum ramp
    public const int TDCS_RAMP_SECONDS = 30;
    public const int TDCS_MAX_ELECTRODE_PAIRS = 3;
    /// VNS (auricular)
    public const double VNS_MAX_MILLIAMPS = 2.0;
    public const double VNS_MIN_HZ = 1.0;
    public const double VNS_MAX_HZ = 25.0;
    /// Visual stimulation
    public const double VISUAL_MAX_HZ = 100.0;
    /// photoparoxysmal risk zone — clinician unlock required
    public const double VISUAL_HIGH_RISK_MIN_HZ = 3.0;
    /// firmware halts goggles, <200ms, if EEG shows photoparoxysmal response
    public const double VISUAL_HIGH_RISK_MAX_HZ = 30.0;
    /// Clinical tACS (T2 only)
    public const double CLINICAL_TACS_MAX_MILLIAMPS = 4.0;
    /// One driver channel per T2 cap electrode (NP-FW-HD-001 §6.4, NP_HD_DRIVER_CHANNELS). OI-TACS-01: the
    /// hub wire mask carried only 16 bits until 2026-09-07, so every encoder clamped here;
    /// np_mod_clin_tacs_params_t now has a third mask byte and 21 is deliverable, not just authorable.
    public const int CLINICAL_TACS_MAX_CHANNELS = 21;
    /// HD-tDCS (T2 only, sLORETA-guided 4×1 ring montage)
    public const double HD_TDCS_MAX_MILLIAMPS_PER_ELECTRODE = 2.0;
    /// Bikson lab 3.5mm electrode safety limit
    public const double HD_TDCS_MAX_CURRENT_DENSITY_A_M2 = 6.0;
    /// Per-phase ceiling on the HD electrode (µC/cm²); Class B np_hd_stim.c aborts at 95% of it. Same
    /// quantity as pulsedMaxPhaseChargeDensityUCcm2, kept separate because the T2 software abort is a
    /// distinct control from the Class C interlock.
    public const double HD_TDCS_MAX_CHARGE_DENSITY_UC_CM2 = 40.0;
    /// HD-tDCS 3.5mm Ag/AgCl sintered electrode: π × (0.175 cm)². Mirrors NP_HD_ELECTRODE_AREA_CM2.
    /// Measured geometry, unlike the three above.
    public const double HD_TDCS_ELECTRODE_AREA_CM2 = 0.0962;
    /// Cervical VNS (T2 accessory, cardiac interlock always active)
    public const double CERVICAL_VNS_MAX_MILLIAMPS = 2.0;
    /// 40Hz Vibrotactile (provisional accessory)
    public const double VIBROTACTILE_FREQUENCY_HZ = 40.0;
    public const double VIBROTACTILE_FREQ_TOLERANCE_HZ = 0.5;
    public const double VIBROTACTILE_MAX_G = 1.2;
    public const double VIBROTACTILE_MIN_G = 0.6;
}

/// Return codes of the shared core's C ABI (common/npps-ffi/include/neurone_npps.h). A refusal (1) and an internal error
/// (2) carry a UTF-8 message in the output buffer; a bad argument (3) carries none.
static class NppsStatus
{
    /// Success: the output buffer holds the result.
    public const int OK = 0;
    /// The core refused the input; the buffer holds the refusal message.
    public const int REFUSED = 1;
    /// The core panicked; the buffer holds a message.
    public const int INTERNAL_ERROR = 2;
    /// A null pointer or non-UTF-8 input; no buffer.
    public const int BAD_ARGUMENT = 3;
}
