package life.neurone.core.protocol

/**
 * The bundled condition registry — standard condition names paired with an
 * external definition link. Protocols reference these by name through their
 * `conditions` field. See NP-COND-LINK-001.
 *
 * Read from `protocols/predefined/00-conditions.npps` on the resource path, via
 * the same namespace the protocol library is built from. This used to be a
 * Kotlin transcription generated by `scripts/sync-conditions.ts`, which existed
 * only because this parser had no `condition` block; it gained one in
 * NP-NPPS-REF-001 Rev 10, so the registry now has one representation rather
 * than two that a forgotten script run could separate.
 */
object NPBundledConditions {

    /** Sorted by name so the order is stable for pickers and tests. */
    val all: List<NPConditionDefinition>
        get() = NPBundledProtocols.namespace.conditions.values.sortedBy { it.name }

    /** Name -> definition, for resolving a protocol's `conditions` entries. */
    val byName: Map<String, NPConditionDefinition>
        get() = NPBundledProtocols.namespace.conditions
}
