/* GENERATED by scripts/sync-constants.ts from common/npps/constants.json. DO NOT EDIT: change the JSON and re-run it. */
#ifndef NEURONE_NPPS_STATUS_H
#define NEURONE_NPPS_STATUS_H

/*
 * Success: the output buffer holds the result.
 */
#define NPPS_STATUS_OK 0
/*
 * The core refused the input; the buffer holds the refusal message.
 */
#define NPPS_STATUS_REFUSED 1
/*
 * The core panicked; the buffer holds a message.
 */
#define NPPS_STATUS_INTERNAL_ERROR 2
/*
 * A null pointer or non-UTF-8 input; no buffer.
 */
#define NPPS_STATUS_BAD_ARGUMENT 3

#endif /* NEURONE_NPPS_STATUS_H */
